### ISSUE TITLE
CI: Move notifications to separate channel

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1005]
It was suggested in the IRC channel that we have too much noise from CI builds. We do have more builds now, since we added freedom-maker and enabled daily builds. Also if someone forks the repository and has builds enabled, it will notify the same channel.

Suggestion to move the notifications to #freedombox-ci. That way only those interested can join and receive the notifications.

**Comment by JoKeyser** [comment]
I agree, and especially like the idea to have a builds-only channel, to not further fragment the number of information channels.

**Comment by SunilMohanAdapa** [comment]
Okay, let's do it.  Perhaps it would be good to document the channel in the coding/contributor wiki page and perhaps with a title change on the IRC channel.
