### ISSUE TITLE
Implement ability to handle a long running task

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#101]
Some tasks spawn a command that take a long time to run.  For example the unattended upgrades command could take a long time based on the number of packages to update and network speed.  Currently the request times out and click on the task again spawns another task.  Instead we should implement the ability to show progress of a long running process.  We should implement it as follows:

- A view declares that it is dependent on a task.
- If task is running, then show the progress instead of the task page.
- Keep updating the progress of a running task.
- If task is not running, show the page to start the task.
- Task is identified uniquely so that multiple visitor to the same page sees the same update.
- Tasks can't be spawned multiple times accidentally.

This is similar to how the Plinth package manager installs various packages.

**Comment by jvalleroy** [comment]
I think this is completed. It works well for Diagnostics and OpenVPN.
