### ISSUE TITLE
ejabberd: Use dynamic reload after config change

### ISSUE THREAD

**Issue by JoKeyser** [freedombox/Plinth#1010]
When ejabberd's configuration is changed through a Plinth action, ejabberd is currently restarted. That takes several seconds on small machines (which is annoying and may confuse clients). Instead, we should use its new dynamic reload function, see https://blog.process-one.net/ejabberd-17-03/:
> ## Dynamic configuration reload
> Using `reload_config` ejabberd’s command it is now possible to reload modules, database connections, listeners, ACLs and global options without restarting ejabberd.
> Thanks to this improvement, it’s now possible to add and remove virtual hosts via configuration reload.

**Comment by johnfrancismccann** [comment]
Any chance I could give this a try?

**Comment by SunilMohanAdapa** [comment]
@johnfrancismccann Please go ahead. Let us know if you need any help or clarifications.
