### ISSUE TITLE
apache: not starting anymore

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#1016]
When trying to log into plinth I noticed the web UI wasn't available but the services seemed to still run.
Updating via `apt-get udate/upgrade` thre this "interesting" bit about Apache at me:

```
...
Processing triggers for systemd (234-3) ...
Setting up apache2 (2.4.27-6) ...
Job for apache2.service failed because the control process exited with error code.
See "systemctl  status apache2.service" and "journalctl  -xe" for details.
invoke-rc.d: initscript apache2, action "start" failed.
● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-09-24 14:24:12 UTC; 178ms ago
  Process: 3938 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)

Sep 24 14:24:11 freedombox systemd[1]: Starting The Apache HTTP Server...
Sep 24 14:24:12 freedombox apachectl[3938]: AH00526: Syntax error on line 1 of /etc/apache2/includes/freedombox-single-sign-on.conf:
Sep 24 14:24:12 freedombox apachectl[3938]: unable to open public key file '/etc/apache2/auth-pubtkt-keys/pubkey.pem'
Sep 24 14:24:12 freedombox apachectl[3938]: Action 'start' failed.
Sep 24 14:24:12 freedombox apachectl[3938]: The Apache error log may have more information.
Sep 24 14:24:12 freedombox systemd[1]: apache2.service: Control process exited, code=exited status=1
Sep 24 14:24:12 freedombox systemd[1]: Failed to start The Apache HTTP Server.
Sep 24 14:24:12 freedombox systemd[1]: apache2.service: Unit entered failed state.
Sep 24 14:24:12 freedombox systemd[1]: apache2.service: Failed with result 'exit-code'.
Setting up libbinutils:armhf (2.29.1-3) ...
...
```

what now?!

**Comment by mray** [comment]
My limited skills to research this allow me to say this: the disk does not seem to be flooded by logs.
Jabber server is still running. Synapse is running but does not seem to be reachable by riot.

**Comment by jvalleroy** [comment]
Did you install plinth from unstable / sid?

**Comment by mray** [comment]
Yes, I think so.

**Comment by jvalleroy** [comment]
There are some serious issues in the plinth 0.15.1+ds-1 package in unstable:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876627
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876640
Since these are reported, it will prevent that package version from migrating to testing.

I think the best option is for us to upload a new plinth package, that fixes those issues. Then you can upgrade plinth, and it will generate the missing keys.

**Comment by mray** [comment]
So all I would have to do is wait, and then `sudo apt-get update` & `sudo apt-get upgrade` right?

**Comment by jvalleroy** [comment]
Yes, I think that will work, it should restart plinth after upgrade.

**Comment by mray** [comment]
Thanks! I can now access plinth again after upgrading.
