### ISSUE TITLE
Don't create empty first-run.d folder

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1017]
https://github.com/freedombox/Plinth/blob/c9d03e8597d57a03c81ea2b69aa7ccb1de428a3c/setup.py#L231

When building the plinth 0.15.2 debian package, I got this lintian warning:
package-contains-empty-directory usr/lib/freedombox/first-run.d/

Plinth no longer installs files into /usr/lib/freedombox/first-run.d/. So there is no need to create this folder.

**Comment by JosephKiranBabu** [comment]
Fixed in #1023.
