### ISSUE TITLE
front page label issues

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1018]
In 0.15.2, some shortcut labels on the front page are shown incorrectly:
- (Chat Client (jsxc)) with extra parentheses
- (infinoted) with no descriptive name
- ikiwiki sites are shown just as (name)

**Comment by isaeef** [comment]
I want to work on this issue

**Comment by JosephKiranBabu** [comment]
@isaeef Thanks for your interest in FreedomBox. A pull request has already been submitted for this. #1021

Please look for other issues labeled [beginner](https://github.com/freedombox/Plinth/labels/beginner).

**Comment by jvalleroy** [comment]
Fixed in #1021.
