### ISSUE TITLE
Implement first time setup mechanism for modules

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#103]
We should have a mechanism in Plinth where in modules can setup themselves for the first time.  

Motivation:
- Move a lot of freedombox-setup/firstrun.d stuff to Plinth #34.
- Proper unified code for handling all the setup and configuration for each module.
- Easier testing with Plinth compared to freedombox-setup.

The following are details on how it should work:

Basics:
- Each module declares a setup() function that is called by the module manager when the module is enabled.
- The setup() function has be to idempotent so that calling it multiple times does not lead to errors. Installing required packages, first time configuration setup and enabling operations should happen here.
- The key/value model shall be used to store the state of whether a module has been enabled.
- Each module also implements a disable()

Plinth setup operation:
- During installation of Plinth, `plinth --setup` will be executed.  During this setup, all the modules which are essential (for FreedomBox operations such as DNS, DHCP, firewall) will be automatically setup().
- Each module can suggest if it is an essential module.
- All optional modules such as ownCloud and XMPP wait until Plinth first run to be setup.

Plinth first run:
- During Plinth's first run wizard, all modules which are not yet enabled (optional modules) will be displayed as a list and user can select which ones to enable.
- When the first run wizard is executed, each selected module's setup() will be called.

Version management: for smooth upgrades
- Each module will declare a version number.
- Version number for which setup() has been executed will be stored in key/value model.
- When Plinth starts, if it finds that the enabled version number is lower than the current code version, it calls setup() again.
- setup() will have arguments telling what the previously enabled version number.

**Comment by fonfon** [comment]
Markus suggested to use one debian package for each module.
I.e. the package freedombox-owncloud would have owncloud as dependency, and the postinstall/.. scripts to set it up for the freedombox. The scripts might change some of the config values or even replace the whole config in some cases. And they would have to take care of uninstalling and upgrading.
What do you think about that?

**Comment by jvalleroy** [comment]
Will ```plinth --setup``` be run by plinth's postinst script? Am I correct in thinking that we should not be installing any packages in this step?

I'm wondering specifically when packages like tor and apt-transport-tor should be installed. If I think it's important to have them available even during first-boot, should they be dependencies of freedombox-setup?

**Comment by SunilMohanAdapa** [comment]
On Saturday 09 January 2016 11:22 PM, James Valleroy wrote:
> Will |plinth --setup| be run by plinth's postinst script? Am I correct
> in thinking that we should not be installing any packages in this step?
> 
> I'm wondering specifically when packages like tor and apt-transport-tor
> should be installed. If I think it's important to have them available
> even during first-boot, should they be dependencies of freedombox-setup?

We could trigger automatic setup upgrades as soon as Plinth starts.
However, this will detect that the package manager is locked and would
postpone the upgrade process by, say, about 5 minutes.  This would be
repeated until the package manager is free to perform upgrades and will
then perform upgrades.  If no special package installations are
necessary, modules will be upgrade immediately.

While a module is awaiting upgrade, that module will not be accessible.

To ease with the above plan, list of required packages for a module will
no longer be an internal matter of a module, but will be well known to
the module manager.

It won't be necessary to run --setup from postinst in this plan.  Just
the regular restart of Plinth that happens during an upgrade is
sufficient.  --setup can be used for first time setup.

Plans of having dependencies on freedombox-setup look like they may
cause issues.  For one, all the apps will need to have their package
dependencies added to freedombox-setup which will complicate a module
development process (as the setup mechanism is not only of default
modules).  We will also loose true modularity when those modules are not
required by some users.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
Most of the  targets here will be satisfied by #398 .

**Comment by jvalleroy** [comment]
I've copied the remaining items to #412.
