### ISSUE TITLE
[873947] plinth: Move setting up /var/{lib,log}/plinth to postinst script

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1032]

**Comment by jvalleroy** [comment]
BTS_msg_id: <150427336349.30751.1578677410358877573.reportbug@towel>
BTS author: Sunil Mohan Adapa <sunil@medhas.org>

Package: plinth
Version: 0.14.0+ds-1
Severity: normal

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Currently in plinth/data/usr/lib/freedombox/setup/86_plinth script the
following happens:

# Ensure that DB and log file permissions are correct
chown -R plinth: /var/lib/plinth /var/log/plinth

Do this to plinth/debian/postint.  After recent changes, freedombox-setup will
no longer run any setup scripts so this has to be done here.  And the duty
rightfully belongs here.



- -- System Information:
Debian Release: 9.1
  APT prefers stable
  APT policy: (500, 'stable')
Architecture: amd64 (x86_64)

Kernel: Linux 4.9.0-3-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN.UTF-8, LC_CTYPE=en_IN.UTF-8 (charmap=UTF-8), LANGUAGE=en_IN.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages plinth depends on:
ii  adduser                    3.115
ii  augeas-tools               1.8.0-1+deb9u1
ii  avahi-daemon               0.6.32-2
pn  batctl                     <none>
ii  firewalld                  0.4.4.2-1
ii  gettext                    0.19.8.1-2
ii  gir1.2-glib-2.0            1.50.0-1+b1
ii  gir1.2-networkmanager-1.0  1.6.2-3
ii  init-system-helpers        1.48
ii  javascript-common          11
ii  ldap-utils                 2.4.44+dfsg-5
ii  ldapscripts                2.0.7-2
ii  libjs-bootstrap            3.3.7+dfsg-2
ii  libjs-jquery               3.1.1-2
ii  libjs-modernizr            2.6.2+ds1-1
pn  libnss-ldapd               <none>
pn  libpam-ldapd               <none>
ii  network-manager            1.6.2-3
pn  nslcd                      <none>
pn  ntp                        <none>
ii  ppp                        2.4.7-1+4
ii  pppoe                      3.12-1.1
ii  python3                    3.5.3-1
ii  python3-apt                1.4.0~beta3
ii  python3-augeas             0.5.0-1
ii  python3-bootstrapform      3.2.1-2
ii  python3-cherrypy3          3.5.0-2
ii  python3-django             1:1.10.7-2
ii  python3-django-stronghold  0.2.7+debian-3
ii  python3-gi                 3.22.0-2
ii  python3-psutil             5.0.1-1
ii  python3-requests           2.12.4-1
ii  python3-ruamel.yaml        0.13.4-2
pn  slapd                      <none>
ii  sudo                       1.8.19p1-2.1
ii  unattended-upgrades        0.93.1+nmu1

plinth recommends no packages.

plinth suggests no packages.

-----BEGIN PGP SIGNATURE-----

iQJFBAEBCgAvFiEE5xPDY9ZyWnWupXSBQ+oc/wqnxfIFAlmpY9ARHHN1bmlsQG1l
ZGhhcy5vcmcACgkQQ+oc/wqnxfLDBxAAgBX+CPvOp+9QygcU9UXkDUzaF8fWfGn/
b02Zd+PINfwN/9XDDOCo+8E+tExeFAT/k7v6Y85DgddYbHidhDGkQtGjTrgaGhST
kuo5OXP15rJYPuu1rUVfrEFZva+sy4B+3vrOmiP6C500rdqc4eY54Wjdf+9DhTTU
bfszX/TpbaxS4phRTEFmTfBYZ9Hnfi05r6zYwdPDgY2AJUVK460DWPYC2hwelm8g
Y0STqB0JBYZPHeeADgiepStJpI2XFNHGGOYl1qzpJXsuup/1BRqtZq+o5LGhLtov
7enkV9kBJ3J0ZhhkLTq4DPFiDsNPFqhU6XJFT9xtzqS8xB3//7dts/XDBqaJSxXG
8MRsXeCo3PW1PQwSqXwIhkPSizHZeAwYfrx4fERE3os2C4Rei03EFq+pDeEFlTCE
RFUH0RJcG/t+WsJ4rpcJrqUJOF2Fgu+GPhNMnB4STiUCellANPyxI8KQc7uuaEp0
CW8yOG/QP2/bVA8WG5XYdaE2JCoxDjUvjDaJRsLSLDfrvTRKLwi4rgEdyAtTGteD
MSKy/aXwbGx5UWyeEfVBD/jFB8GMtaiTv6i7aSjB1OjJYgTPDC03Sr0Dxh2cMroR
XXhw84ejRS9JjgsmFoPP3wdaS2jkN9vyOUMTCUUP2lPWPj/nM5Y5Kc94YgpDQc/2
TX1MC6i5Okg=
=a0GX
-----END PGP SIGNATURE-----

**Comment by jvalleroy** [comment]
Only applies to debian package.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <150427336349.30751.1578677410358877573.reportbug@towel>
BTS author: Sunil Mohan Adapa <sunil@medhas.org>

Package: plinth
Version: 0.14.0+ds-1
Severity: normal

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Currently in plinth/data/usr/lib/freedombox/setup/86_plinth script the
following happens:

# Ensure that DB and log file permissions are correct
chown -R plinth: /var/lib/plinth /var/log/plinth

Do this to plinth/debian/postint.  After recent changes, freedombox-setup will
no longer run any setup scripts so this has to be done here.  And the duty
rightfully belongs here.



- -- System Information:
Debian Release: 9.1
  APT prefers stable
  APT policy: (500, 'stable')
Architecture: amd64 (x86_64)

Kernel: Linux 4.9.0-3-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN.UTF-8, LC_CTYPE=en_IN.UTF-8 (charmap=UTF-8), LANGUAGE=en_IN.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages plinth depends on:
ii  adduser                    3.115
ii  augeas-tools               1.8.0-1+deb9u1
ii  avahi-daemon               0.6.32-2
pn  batctl                     <none>
ii  firewalld                  0.4.4.2-1
ii  gettext                    0.19.8.1-2
ii  gir1.2-glib-2.0            1.50.0-1+b1
ii  gir1.2-networkmanager-1.0  1.6.2-3
ii  init-system-helpers        1.48
ii  javascript-common          11
ii  ldap-utils                 2.4.44+dfsg-5
ii  ldapscripts                2.0.7-2
ii  libjs-bootstrap            3.3.7+dfsg-2
ii  libjs-jquery               3.1.1-2
ii  libjs-modernizr            2.6.2+ds1-1
pn  libnss-ldapd               <none>
pn  libpam-ldapd               <none>
ii  network-manager            1.6.2-3
pn  nslcd                      <none>
pn  ntp                        <none>
ii  ppp                        2.4.7-1+4
ii  pppoe                      3.12-1.1
ii  python3                    3.5.3-1
ii  python3-apt                1.4.0~beta3
ii  python3-augeas             0.5.0-1
ii  python3-bootstrapform      3.2.1-2
ii  python3-cherrypy3          3.5.0-2
ii  python3-django             1:1.10.7-2
ii  python3-django-stronghold  0.2.7+debian-3
ii  python3-gi                 3.22.0-2
ii  python3-psutil             5.0.1-1
ii  python3-requests           2.12.4-1
ii  python3-ruamel.yaml        0.13.4-2
pn  slapd                      <none>
ii  sudo                       1.8.19p1-2.1
ii  unattended-upgrades        0.93.1+nmu1

plinth recommends no packages.

plinth suggests no packages.

-----BEGIN PGP SIGNATURE-----

iQJFBAEBCgAvFiEE5xPDY9ZyWnWupXSBQ+oc/wqnxfIFAlmpY9ARHHN1bmlsQG1l
ZGhhcy5vcmcACgkQQ+oc/wqnxfLDBxAAgBX+CPvOp+9QygcU9UXkDUzaF8fWfGn/
b02Zd+PINfwN/9XDDOCo+8E+tExeFAT/k7v6Y85DgddYbHidhDGkQtGjTrgaGhST
kuo5OXP15rJYPuu1rUVfrEFZva+sy4B+3vrOmiP6C500rdqc4eY54Wjdf+9DhTTU
bfszX/TpbaxS4phRTEFmTfBYZ9Hnfi05r6zYwdPDgY2AJUVK460DWPYC2hwelm8g
Y0STqB0JBYZPHeeADgiepStJpI2XFNHGGOYl1qzpJXsuup/1BRqtZq+o5LGhLtov
7enkV9kBJ3J0ZhhkLTq4DPFiDsNPFqhU6XJFT9xtzqS8xB3//7dts/XDBqaJSxXG
8MRsXeCo3PW1PQwSqXwIhkPSizHZeAwYfrx4fERE3os2C4Rei03EFq+pDeEFlTCE
RFUH0RJcG/t+WsJ4rpcJrqUJOF2Fgu+GPhNMnB4STiUCellANPyxI8KQc7uuaEp0
CW8yOG/QP2/bVA8WG5XYdaE2JCoxDjUvjDaJRsLSLDfrvTRKLwi4rgEdyAtTGteD
MSKy/aXwbGx5UWyeEfVBD/jFB8GMtaiTv6i7aSjB1OjJYgTPDC03Sr0Dxh2cMroR
XXhw84ejRS9JjgsmFoPP3wdaS2jkN9vyOUMTCUUP2lPWPj/nM5Y5Kc94YgpDQc/2
TX1MC6i5Okg=
=a0GX
-----END PGP SIGNATURE-----

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <1c6ea359-7736-e4d2-51f9-8cbf7cd636a5@mailbox.org>
BTS author: James Valleroy <jvalleroy@mailbox.org>

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--2ch7Ev7MHFQlHlx3tEtvxjSWpS1EKkNLv
Content-Type: multipart/mixed; boundary="DCCjB9qD0s9QjBkAlvQeE05ec8sAQuDdW";
 protected-headers="v1"
From: James Valleroy <jvalleroy@mailbox.org>
To: 873947@bugs.debian.org
Message-ID: <1c6ea359-7736-e4d2-51f9-8cbf7cd636a5@mailbox.org>
Subject: Re: plinth: Move setting up /var/{lib,log}/plinth to postinst script
References: <150427336349.30751.1578677410358877573.reportbug@towel>
 <150427336349.30751.1578677410358877573.reportbug@towel>
In-Reply-To: <150427336349.30751.1578677410358877573.reportbug@towel>

--DCCjB9qD0s9QjBkAlvQeE05ec8sAQuDdW
Content-Type: text/plain; charset=utf-8
Content-Language: en-US
Content-Transfer-Encoding: quoted-printable

On Fri, 01 Sep 2017 19:12:43 +0530 Sunil Mohan Adapa <sunil@medhas.org>
wrote:
> # Ensure that DB and log file permissions are correct
> chown -R plinth: /var/lib/plinth /var/log/plinth
>=20
> Do this to plinth/debian/postint.  After recent changes, freedombox-set=
up will
> no longer run any setup scripts so this has to be done here.  And the d=
uty
> rightfully belongs here.

Looks like this is already handled in plinth's postinst. I guess this
can be closed then?


--DCCjB9qD0s9QjBkAlvQeE05ec8sAQuDdW--

--2ch7Ev7MHFQlHlx3tEtvxjSWpS1EKkNLv
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----

iQJKBAEBCgA0FiEEfWrbdQ+RCFWJSEvmd8DHXntlCAgFAlnY4boWHGp2YWxsZXJv
eUBtYWlsYm94Lm9yZwAKCRB3wMdee2UICBT/D/oDaCvp1wnhzFqpegjbV3AOnPJU
tgH8UAQDLq9HyjXzVVJOrqwSGIjSaSWeh/mo9Xe7lpQB/4wEy53pHJ1d7YO3wZXx
Af/rdsv3EOTeTIABBYuSwP+OmwhgGZS4gUXgAv0AdMCigHYLBFobPlHpyAondewn
WHN+ejIL5nqPIiaW6dOofGZeajPJPNP/X2pTRZrLUrwCeIuy1XPgVcB5BHNODfJq
aJuJwFGo7/F3VjWPxnmbcyIBG0Vbt2N9EF1N3l7+XMMXLc7x0TowU9SgZRxwrM4n
PFLFdxJiNO31/0UVyLYWQq1b1V6cchDPyJ2OTtUCMN7DNVHVlYUjJtWoIeSSl3xj
DEg+tFaXARka7ZQ8qzP7S/aIDJrXBs2FNuuv8n7UqCHNgZabeBN8WW8u6GEfgJda
0vj9baw4Jcbm/9neLxSIYaTL09kqwziHXfxViUMnFo8HECdu7DlJa+AT956M/oHv
iVGqsZjlIDrleViw4Ah4j50aJ/YaD9O2qpz0vaQen8DC/59pO0eR+k/ys5zrpY4o
iWzeEw5Kh/bi4isDppBie0P2eJua8ICJtacEttwYXPz+3b3fNdBi/g8OXo//vDN0
THeZpDQBQTBcY98cfHoNUGkGFZpz3mUFi2EV/+QQoNGRPDJWZkWQwwajhKPZuqII
RiCM6XxCD4qHDTAFyQ==
=k+vY
-----END PGP SIGNATURE-----

--2ch7Ev7MHFQlHlx3tEtvxjSWpS1EKkNLv--

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <a7c179c9-798b-910b-0874-e518be557d92@medhas.org>
BTS author: Sunil Mohan Adapa <sunil@medhas.org>

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--1Hrc1nspikFTxffOjCUEF9waTU7lxfwBU
Content-Type: multipart/mixed; boundary="NqStFvOmUKtUW9IboihkfePcd25xQm6jv";
 protected-headers="v1"
From: Sunil Mohan Adapa <sunil@medhas.org>
To: James Valleroy <jvalleroy@mailbox.org>, 873947-done@bugs.debian.org
Message-ID: <a7c179c9-798b-910b-0874-e518be557d92@medhas.org>
Subject: Re: Bug#873947: plinth: Move setting up /var/{lib,log}/plinth to
 postinst script
References: <150427336349.30751.1578677410358877573.reportbug@towel>
 <150427336349.30751.1578677410358877573.reportbug@towel>
 <150427336349.30751.1578677410358877573.reportbug@towel>
 <1c6ea359-7736-e4d2-51f9-8cbf7cd636a5@mailbox.org>
In-Reply-To: <1c6ea359-7736-e4d2-51f9-8cbf7cd636a5@mailbox.org>

--NqStFvOmUKtUW9IboihkfePcd25xQm6jv
Content-Type: text/plain; charset=utf-8
Content-Language: en-US
Content-Transfer-Encoding: quoted-printable

On Saturday 07 October 2017 07:46 PM, James Valleroy wrote:
[...]
>=20
> Looks like this is already handled in plinth's postinst. I guess this
> can be closed then?
>=20

Indeed. This is already handled, no changes required and bug can be close=
d.

--=20
Sunil


--NqStFvOmUKtUW9IboihkfePcd25xQm6jv--

--1Hrc1nspikFTxffOjCUEF9waTU7lxfwBU
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----

iQJFBAEBCgAvFiEE5xPDY9ZyWnWupXSBQ+oc/wqnxfIFAlnd8V0RHHN1bmlsQG1l
ZGhhcy5vcmcACgkQQ+oc/wqnxfLuqQ/9Eb3dG1YOpNlosSgyiN56iqZQg1ZnR5Ly
T2X/LZuG3mhSrpV4BQpDyIONww+z2BZxBya4d9wZx7uGbqO2CmqVH16pIGm7gia0
ksAQQ4K0qY2EBmTbJ8xyqGW7B8q1joiXdg+bWn4yyUL4ZgCAAk1YDqOH7s9PmTpK
tB9p9jlL++e6qMjZf3mWlTwmPj528y0EWkgktYBMaP3l5tfw+pB97F5d+9ApYzNq
BG087fb1Z2o6oHwzR0o1jkEamFo43JzVKB+Ji81zomdEbgY/xgcYHiY6P6k52x1e
WPACs6q7rj8Qm720CwLUp8Q3HIVr7PPTLrBwGGC6xLJ+0CzANomO9ivV8UWAaFKx
vI6S66SGE4L5Z8uhsdw6jfJX0CeqUKPNZvJUYymUPh+36kCS74pf+fqHj/uFYaY+
6xuR42eAuTm9PYkkxbv8yC3VHkbGhSCCyR2p31eBhJBgg8YDWW8RLbVZdYYSTC57
WHoYGjNmjpx0muNpJhKv6VnkV/Mar5B6EBaOP01RbnRDswTNHdguxZewvuur1LY6
tumzrh+XuDJpVOHI6VpoMq/lNW1wsrEvwiiLve3pzUCsZvNQbhvN/Mxz13SE2+4E
D5Bxc880WCcLLyeA5jW1ngJ5E3yJr7PQsvZ/bZ6GTqjz+iPq6J8r9sW67rgUnJia
7dIqyoAudE8=
=BWYL
-----END PGP SIGNATURE-----

--1Hrc1nspikFTxffOjCUEF9waTU7lxfwBU--
