### ISSUE TITLE
[876516] plinth: .../plinth/sys/pagekite/configure/ return 500 internal server error

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1036]

**Comment by jvalleroy** [comment]
BTS_msg_id: <2fl8th5kheu.fsf@diskless.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Package: plinth
Version: 0.14.0+ds-1

When visiting Configuration->Plinth->Configure Pagekite in the web
interface, I get a 500 internal server error back.

This is the content in /var/log/syslog when it happen:

Sep 23 07:20:19 freedombox plinth[535]: [2017-09-23 07:20:19,147] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'is-disabled']
Sep 23 07:20:20 freedombox plinth[535]: [2017-09-23 07:20:20,576] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-kite']
Sep 23 07:20:21 freedombox plinth[535]: [2017-09-23 07:20:21,011] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-frontend']
Sep 23 07:20:21 freedombox plinth[535]: [2017-09-23 07:20:21,531] django.request ERROR    Internal Server Error: /plinth/sys/pagekite/configure/
Sep 23 07:20:21 freedombox plinth[535]: Traceback (most recent call last):
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 41, in inner
Sep 23 07:20:21 freedombox plinth[535]:     response = get_response(request)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
Sep 23 07:20:21 freedombox plinth[535]:     response = self._get_response(request)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 217, in _get_response
Sep 23 07:20:21 freedombox plinth[535]:     response = self.process_exception_by_middleware(e, request)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 215, in _get_response
Sep 23 07:20:21 freedombox plinth[535]:     response = response.render()
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/response.py", line 107, in render
Sep 23 07:20:21 freedombox plinth[535]:     self.content = self.rendered_content
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/response.py", line 84, in rendered_content
Sep 23 07:20:21 freedombox plinth[535]:     content = template.render(context, self._request)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 66, in render
Sep 23 07:20:21 freedombox plinth[535]:     return self.template.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 207, in render
Sep 23 07:20:21 freedombox plinth[535]:     return self._render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
Sep 23 07:20:21 freedombox plinth[535]:     return self.nodelist.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
Sep 23 07:20:21 freedombox plinth[535]:     bit = node.render_annotated(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
Sep 23 07:20:21 freedombox plinth[535]:     return self.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 177, in render
Sep 23 07:20:21 freedombox plinth[535]:     return compiled_parent._render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
Sep 23 07:20:21 freedombox plinth[535]:     return self.nodelist.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
Sep 23 07:20:21 freedombox plinth[535]:     bit = node.render_annotated(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
Sep 23 07:20:21 freedombox plinth[535]:     return self.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
Sep 23 07:20:21 freedombox plinth[535]:     result = block.nodelist.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
Sep 23 07:20:21 freedombox plinth[535]:     bit = node.render_annotated(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
Sep 23 07:20:21 freedombox plinth[535]:     return self.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
Sep 23 07:20:21 freedombox plinth[535]:     result = block.nodelist.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
Sep 23 07:20:21 freedombox plinth[535]:     bit = node.render_annotated(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
Sep 23 07:20:21 freedombox plinth[535]:     return self.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 1040, in render
Sep 23 07:20:21 freedombox plinth[535]:     output = self.filter_expression.resolve(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 736, in resolve
Sep 23 07:20:21 freedombox plinth[535]:     new_obj = func(obj, *arg_vals)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/bootstrapform/templatetags/bootstrap.py", line 46, in bootstrap_horizontal
Sep 23 07:20:21 freedombox plinth[535]:     return render(element, markup_classes)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/bootstrapform/templatetags/bootstrap.py", line 83, in render
Sep 23 07:20:21 freedombox plinth[535]:     return template.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 64, in render
Sep 23 07:20:21 freedombox plinth[535]:     context = make_context(context, request, autoescape=self.backend.engine.autoescape)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/context.py", line 287, in make_context
Sep 23 07:20:21 freedombox plinth[535]:     raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
Sep 23 07:20:21 freedombox plinth[535]: TypeError: context must be a dict rather than Context.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by jvalleroy** [comment]
Same as #900.

**Comment by jvalleroy** [comment]
BTS_msg_id: <2fl8th5kheu.fsf@diskless.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Package: plinth
Version: 0.14.0+ds-1

When visiting Configuration->Plinth->Configure Pagekite in the web
interface, I get a 500 internal server error back.

This is the content in /var/log/syslog when it happen:

Sep 23 07:20:19 freedombox plinth[535]: [2017-09-23 07:20:19,147] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'is-disabled']
Sep 23 07:20:20 freedombox plinth[535]: [2017-09-23 07:20:20,576] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-kite']
Sep 23 07:20:21 freedombox plinth[535]: [2017-09-23 07:20:21,011] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-frontend']
Sep 23 07:20:21 freedombox plinth[535]: [2017-09-23 07:20:21,531] django.request ERROR    Internal Server Error: /plinth/sys/pagekite/configure/
Sep 23 07:20:21 freedombox plinth[535]: Traceback (most recent call last):
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 41, in inner
Sep 23 07:20:21 freedombox plinth[535]:     response = get_response(request)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
Sep 23 07:20:21 freedombox plinth[535]:     response = self._get_response(request)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 217, in _get_response
Sep 23 07:20:21 freedombox plinth[535]:     response = self.process_exception_by_middleware(e, request)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 215, in _get_response
Sep 23 07:20:21 freedombox plinth[535]:     response = response.render()
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/response.py", line 107, in render
Sep 23 07:20:21 freedombox plinth[535]:     self.content = self.rendered_content
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/response.py", line 84, in rendered_content
Sep 23 07:20:21 freedombox plinth[535]:     content = template.render(context, self._request)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 66, in render
Sep 23 07:20:21 freedombox plinth[535]:     return self.template.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 207, in render
Sep 23 07:20:21 freedombox plinth[535]:     return self._render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
Sep 23 07:20:21 freedombox plinth[535]:     return self.nodelist.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
Sep 23 07:20:21 freedombox plinth[535]:     bit = node.render_annotated(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
Sep 23 07:20:21 freedombox plinth[535]:     return self.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 177, in render
Sep 23 07:20:21 freedombox plinth[535]:     return compiled_parent._render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
Sep 23 07:20:21 freedombox plinth[535]:     return self.nodelist.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
Sep 23 07:20:21 freedombox plinth[535]:     bit = node.render_annotated(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
Sep 23 07:20:21 freedombox plinth[535]:     return self.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
Sep 23 07:20:21 freedombox plinth[535]:     result = block.nodelist.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
Sep 23 07:20:21 freedombox plinth[535]:     bit = node.render_annotated(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
Sep 23 07:20:21 freedombox plinth[535]:     return self.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
Sep 23 07:20:21 freedombox plinth[535]:     result = block.nodelist.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
Sep 23 07:20:21 freedombox plinth[535]:     bit = node.render_annotated(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
Sep 23 07:20:21 freedombox plinth[535]:     return self.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 1040, in render
Sep 23 07:20:21 freedombox plinth[535]:     output = self.filter_expression.resolve(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/base.py", line 736, in resolve
Sep 23 07:20:21 freedombox plinth[535]:     new_obj = func(obj, *arg_vals)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/bootstrapform/templatetags/bootstrap.py", line 46, in bootstrap_horizontal
Sep 23 07:20:21 freedombox plinth[535]:     return render(element, markup_classes)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/bootstrapform/templatetags/bootstrap.py", line 83, in render
Sep 23 07:20:21 freedombox plinth[535]:     return template.render(context)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 64, in render
Sep 23 07:20:21 freedombox plinth[535]:     context = make_context(context, request, autoescape=self.backend.engine.autoescape)
Sep 23 07:20:21 freedombox plinth[535]:   File "/usr/lib/python3/dist-packages/django/template/context.py", line 287, in make_context
Sep 23 07:20:21 freedombox plinth[535]:     raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
Sep 23 07:20:21 freedombox plinth[535]: TypeError: context must be a dict rather than Context.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by JosephKiranBabu** [comment]
Fixed in python-django-bootstrap-form 3.3-1
https://tracker.debian.org/news/894656
