### ISSUE TITLE
ejabberd: Disable Erlang crash dumps

### ISSUE THREAD

**Issue by JoKeyser** [freedombox/Plinth#1055]
If ejabberd crashes, often a crash dump file is generated at `/var/log/ejabberd/erl_crash_$DATE_$TIME.dump`. If a problem persists (e.g. a misconfiguration), systemd will keep restarting ejabberd, each time generating a new dump of ~3 MiB, at a rate of ~60/h, thus ~180 MiB per hour, or ~4.2 GiB per day. Without manual intervention, this fills up the entire root partition and thus eventually renders *all* services unusable.

A good solution would be to entirely disable ejabberd's dump-file generation (also because it's in line with [our goal to limit any logging](https://github.com/freedombox/freedombox-todos/issues/5), and because FreedomBox users are not expected to inspect them).

The only way I found to prevent the dumps is to edit `/etc/ejabberd/ejabberdctl.cfg` to set `ERL_OPTIONS="-env ERL_CRASH_DUMP_BYTES 0"`. This sets Erlang's environment variable `ERL_CRASH_DUMP_BYTES=0` - doing this in the "normal" (root) shell had no effect for me.
If editing `/etc/ejabberd/ejabberdctl.cfg` is the best choice to solve this, it has the (current) down-side of being a it symlink to `/etc/default/ejabberd`, which is a `conffile` (hence editing it would prevent `unattended-upgrades` from upgrading it without manual intervention).

**Comment by JoKeyser** [comment]
My questions are: Is editing `/etc/ejabberd/ejabberdctl.cfg` indeed the best solution? And if so, how to best prevent a `conffile` conflict? Maybe by asking the ejabberd maintainers to include that option into debconf, or by simply cutting the symlink and then copying and editing it?

**Comment by jvalleroy** [comment]
@JoKeyser I think the best solution is the one that involves the package maintainers. ejabberd package already uses debconf for some settings in ejabberd.yml. So we can ask (with a wishlist bug) for this setting to also be configurable through debconf.

If we replace the symlink, the main drawback is that we will no longer (automatically) receive updates that are made in the packaged file.

**Comment by JoKeyser** [comment]
@jvalleroy thanks for checking. I've filed a bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878034

**Comment by JoKeyser** [comment]
The ejabberd team replied, they're gonna make it a configurable debconf value *and* will make it the future detault :).
