### ISSUE TITLE
Convert docs to markdown files

### ISSUE THREAD

**Issue by palash25** [freedombox/Plinth#1106]
I noticed that a lot of docs like HACKING, CONTRIBUTING, etc don't have a .md extension and display information as a simple text file. I don't know whether this is intentional or not but I noticed that CHANGELOG and README are markdown files and this doesn't look symmetric.

If this is a valid issue I would like to work on this and become a part of this organization.

**Comment by JoKeyser** [comment]
Hi @palash25 , this seems a good idea, and I see no reason against it. Either wait for an (unlikely) veto from somebody else, or just go ahead and open a PR. There it could also be discussed. Would be great to welcome you as a contributor soon.
