### ISSUE TITLE
[750927] plinth fails to install due to file conflict with firewalld

### ISSUE THREAD

**Issue by FedericoCeratto** [freedombox/Plinth#111]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <CAG3_j1Q28dKPHh7xfCtx4RNpv_6trx_La0Q6TKTPx4PwUPxY9A@mail.gmail.com>
BTS author: James Valleroy <james.valleroy@gmail.com>

Package: plinth
Version: 0.3.2.0.git.20140504-2
Severity: important

Dear Maintainer,

While building a freedombox image using freedom-maker, plinth failed to install
inside the vmdebootstrap:

Unpacking plinth (0.3.2.0.git.20140504-2) ...
dpkg: error processing archive
/var/cache/apt/archives/plinth_0.3.2.0.git.20140504-2_all.deb (--unpack):
 trying to overwrite '/usr/lib/firewalld/services/xmpp-server.xml', which is
also in package firewalld 0.3.10-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
...
Errors were encountered while processing:
 /var/cache/apt/archives/plinth_0.3.2.0.git.20140504-2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

It looks like the firewalld service files have been added to the firewalld
package. The service files in plinth are duplicates that try to install to the
same location, which causes the failure.

(I was able to successfully install this plinth package on my desktop,
which doesn't have firewalld installed.)

-- System Information:
Debian Release: jessie/sid
  APT prefers testing-updates
  APT policy: (500, 'testing-updates'), (500, 'testing')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 3.14-1-amd64 (SMP w/8 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash

Versions of packages plinth depends on:
ii  adduser            3.113+nmu3
ii  libjs-jquery       1.7.2+dfsg-3
ii  libjs-modernizr    2.6.2+ds1-1
ii  python-bcrypt      0.4-2
ii  python-cheetah     2.4.4-3
ii  python-cherrypy3   3.2.2-2
ii  python-django      1.6.5-1
ii  python-passlib     1.6.1-1
ii  python-simplejson  3.5.2-1
ii  python-withsqlite  0.0.0~git.20130929-1
pn  python:any         <none>
ii  sudo               1.8.9p5-1

plinth recommends no packages.

plinth suggests no packages.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <1143780743.151.1402477764679.open-xchange@oxuslxltgw02.lxa.perfora.net>
BTS author: Sunil Mohan Adapa <sunil@medhas.org>

The conflicting files were added only temporarily to Plinth until FirewallD
upstream accepts them. They have been accepted upstream[1] and now there is no
need from them in Plinth. They should be removed. Then new Plinth Debian package
should depend on the newer FirewallD package. James, are you looking at this?

Links:

1) https://fedorahosted.org/firewalld/ticket/13

Thank you,

--
Sunil

**Comment by SunilMohanAdapa** [comment]
The original bug on BTS is closed.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <CAG3_j1Q28dKPHh7xfCtx4RNpv_6trx_La0Q6TKTPx4PwUPxY9A@mail.gmail.com>
BTS author: James Valleroy <james.valleroy@gmail.com>

Package: plinth
Version: 0.3.2.0.git.20140504-2
Severity: important

Dear Maintainer,

While building a freedombox image using freedom-maker, plinth failed to install
inside the vmdebootstrap:

Unpacking plinth (0.3.2.0.git.20140504-2) ...
dpkg: error processing archive
/var/cache/apt/archives/plinth_0.3.2.0.git.20140504-2_all.deb (--unpack):
 trying to overwrite '/usr/lib/firewalld/services/xmpp-server.xml', which is
also in package firewalld 0.3.10-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
...
Errors were encountered while processing:
 /var/cache/apt/archives/plinth_0.3.2.0.git.20140504-2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

It looks like the firewalld service files have been added to the firewalld
package. The service files in plinth are duplicates that try to install to the
same location, which causes the failure.

(I was able to successfully install this plinth package on my desktop,
which doesn't have firewalld installed.)

-- System Information:
Debian Release: jessie/sid
  APT prefers testing-updates
  APT policy: (500, 'testing-updates'), (500, 'testing')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 3.14-1-amd64 (SMP w/8 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash

Versions of packages plinth depends on:
ii  adduser            3.113+nmu3
ii  libjs-jquery       1.7.2+dfsg-3
ii  libjs-modernizr    2.6.2+ds1-1
ii  python-bcrypt      0.4-2
ii  python-cheetah     2.4.4-3
ii  python-cherrypy3   3.2.2-2
ii  python-django      1.6.5-1
ii  python-passlib     1.6.1-1
ii  python-simplejson  3.5.2-1
ii  python-withsqlite  0.0.0~git.20130929-1
pn  python:any         <none>
ii  sudo               1.8.9p5-1

plinth recommends no packages.

plinth suggests no packages.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <1143780743.151.1402477764679.open-xchange@oxuslxltgw02.lxa.perfora.net>
BTS author: Sunil Mohan Adapa <sunil@medhas.org>

The conflicting files were added only temporarily to Plinth until FirewallD
upstream accepts them. They have been accepted upstream[1] and now there is no
need from them in Plinth. They should be removed. Then new Plinth Debian package
should depend on the newer FirewallD package. James, are you looking at this?

Links:

1) https://fedorahosted.org/firewalld/ticket/13

Thank you,

--
Sunil
