### ISSUE TITLE
[769328] plinth: no web page when started form boot, work when started from command line

### ISSUE THREAD

**Issue by FedericoCeratto** [freedombox/Plinth#112]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <2flsiho2kyf.fsf@diskless.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Package: plinth
Version: 0.4.1-1
Severity: serious

I installed an unstable based FreedomBox using d-i and preseeding, but
the resulting installation do not give me a working plinth.  I installed
using 'url=http://www.reinholdtsen.name/freedombox/unstable.dat' which I
believe can be used to recreate the problem.

Running the test suite show that http://freedombox/plinth/ do not work
for IPv4 and IPv6.  There are also several problems with the tor
service.

I suspect the init.d script starting plinth isn't working as well as it
should.  When I start plinth with --debug --no-daemon as root from the
command line, it work and I could access the web pages.  When it is
started as a service, it do not work. :(

I tried both using sysvinit and systemd, and both gave me a non-working
plinth installation.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20141112211214.GV24773@ulrik.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Here is some more information collected after booting systemd:

root@freedombox:~# systemctl status plinth
* plinth.service - LSB: plinth web frontend
   Loaded: loaded (/etc/init.d/plinth)
   Active: active (running) since on. 2014-11-12 21:03:28 UTC; 6min ago
  Process: 542 ExecStart=/etc/init.d/plinth start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/plinth.service
           └─821 /usr/bin/python3 /usr/bin/plinth --pidfile=/var/run/plinth.pid --server_dir=/plinth

nov. 12 21:03:28 freedombox plinth[542]: Operations to perform:
nov. 12 21:03:28 freedombox plinth[542]: Synchronize unmigrated apps: bootstrapform, plinth
nov. 12 21:03:28 freedombox plinth[542]: Apply all migrations: contenttypes, auth
nov. 12 21:03:28 freedombox plinth[542]: Synchronizing apps without migrations:
nov. 12 21:03:28 freedombox plinth[542]: Creating tables...
nov. 12 21:03:28 freedombox plinth[542]: Installing custom SQL...
nov. 12 21:03:28 freedombox plinth[542]: Installing indexes...
nov. 12 21:03:28 freedombox plinth[542]: Running migrations:
nov. 12 21:03:28 freedombox plinth[542]: No migrations to apply.
nov. 12 21:03:28 freedombox plinth[542]: .
root@freedombox:~# 

root@freedombox:~# journalctl -u plinth
-- Logs begin at on. 2014-11-12 20:57:21 UTC, end at on. 2014-11-12 21:05:07 UTC. --
nov. 12 21:03:28 freedombox plinth[542]: Starting embedded web frontend: plinth[2014-11-12 21:03:28,632] pli
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,636] plinth.__main__ INFO     Creating or addi
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,736] plinth.__main__ INFO     Configuration lo
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,738] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,739] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,740] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,740] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,742] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,743] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,751] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,752] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,753] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,757] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,760] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,761] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,762] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,763] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,764] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,769] plinth.actions INFO     Executing command
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,781] plinth.__main__ INFO     Setting up Cherr
nov. 12 21:03:28 freedombox plinth[542]: Operations to perform:
nov. 12 21:03:28 freedombox plinth[542]: Synchronize unmigrated apps: bootstrapform, plinth
nov. 12 21:03:28 freedombox plinth[542]: Apply all migrations: contenttypes, auth
nov. 12 21:03:28 freedombox plinth[542]: Synchronizing apps without migrations:
nov. 12 21:03:28 freedombox plinth[542]: Creating tables...
nov. 12 21:03:28 freedombox plinth[542]: Installing custom SQL...
nov. 12 21:03:28 freedombox plinth[542]: Installing indexes...
nov. 12 21:03:28 freedombox plinth[542]: Running migrations:
nov. 12 21:03:28 freedombox plinth[542]: No migrations to apply.
nov. 12 21:03:28 freedombox plinth[542]: .
root@freedombox:~# 

-- 
Happy hacking
Petter Reinholdtsen

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <5464175C.5030807@medhas.org>
BTS author: Sunil Mohan Adapa <sunil@medhas.org>

On Thursday 13 November 2014 02:42 AM, Petter Reinholdtsen wrote:
> Here is some more information collected after booting systemd:
> 
> root@freedombox:~# systemctl status plinth
> * plinth.service - LSB: plinth web frontend

Thank you for the bug report and the information.

The init script seems to be fine and Plinth is running properly.  This
was the case that I checked in my setup.  I should be focusing on
accessing it via Apache.

If it works from command line then we can only suspect that the --debug
option allowed things to work.  One thing with --debug option is that
ALLOWED_HOSTS option in Django will be disabled.  This permits anyone
(Apache) trying to access it on addresses other then 127.0.0.1 or
localhost.  But all this should be reproducible on my setup.  So, let me
check.

-- 
Sunil

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <5469BC8A.8070606@medhas.org>
BTS author: Sunil Mohan Adapa <sunil@medhas.org>

Hello,

I have a good picture of the problem and I have revamped Plinth's Apache
configuration to fix various problems.  The pull request is waiting for
review.

https://github.com/freedombox/Plinth/pull/25

The attached patch cleans up Plinth's Apache configuration in
freedombox-setup.

This bug will be fixed in Plinth's upstream and freedombox-setup package.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
The original bug on BTS is closed. Looks like the last message of the bug which closes the bug was not imported.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <2flsiho2kyf.fsf@diskless.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Package: plinth
Version: 0.4.1-1
Severity: serious

I installed an unstable based FreedomBox using d-i and preseeding, but
the resulting installation do not give me a working plinth.  I installed
using 'url=http://www.reinholdtsen.name/freedombox/unstable.dat' which I
believe can be used to recreate the problem.

Running the test suite show that http://freedombox/plinth/ do not work
for IPv4 and IPv6.  There are also several problems with the tor
service.

I suspect the init.d script starting plinth isn't working as well as it
should.  When I start plinth with --debug --no-daemon as root from the
command line, it work and I could access the web pages.  When it is
started as a service, it do not work. :(

I tried both using sysvinit and systemd, and both gave me a non-working
plinth installation.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20141112211214.GV24773@ulrik.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Here is some more information collected after booting systemd:

root@freedombox:~# systemctl status plinth
* plinth.service - LSB: plinth web frontend
   Loaded: loaded (/etc/init.d/plinth)
   Active: active (running) since on. 2014-11-12 21:03:28 UTC; 6min ago
  Process: 542 ExecStart=/etc/init.d/plinth start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/plinth.service
           └─821 /usr/bin/python3 /usr/bin/plinth --pidfile=/var/run/plinth.pid --server_dir=/plinth

nov. 12 21:03:28 freedombox plinth[542]: Operations to perform:
nov. 12 21:03:28 freedombox plinth[542]: Synchronize unmigrated apps: bootstrapform, plinth
nov. 12 21:03:28 freedombox plinth[542]: Apply all migrations: contenttypes, auth
nov. 12 21:03:28 freedombox plinth[542]: Synchronizing apps without migrations:
nov. 12 21:03:28 freedombox plinth[542]: Creating tables...
nov. 12 21:03:28 freedombox plinth[542]: Installing custom SQL...
nov. 12 21:03:28 freedombox plinth[542]: Installing indexes...
nov. 12 21:03:28 freedombox plinth[542]: Running migrations:
nov. 12 21:03:28 freedombox plinth[542]: No migrations to apply.
nov. 12 21:03:28 freedombox plinth[542]: .
root@freedombox:~# 

root@freedombox:~# journalctl -u plinth
-- Logs begin at on. 2014-11-12 20:57:21 UTC, end at on. 2014-11-12 21:05:07 UTC. --
nov. 12 21:03:28 freedombox plinth[542]: Starting embedded web frontend: plinth[2014-11-12 21:03:28,632] pli
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,636] plinth.__main__ INFO     Creating or addi
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,736] plinth.__main__ INFO     Configuration lo
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,738] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,739] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,740] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,740] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,742] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,743] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,751] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,752] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,753] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,757] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,760] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,761] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,762] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,763] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,764] plinth.module_loader INFO     Importing p
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,769] plinth.actions INFO     Executing command
nov. 12 21:03:28 freedombox plinth[542]: [2014-11-12 21:03:28,781] plinth.__main__ INFO     Setting up Cherr
nov. 12 21:03:28 freedombox plinth[542]: Operations to perform:
nov. 12 21:03:28 freedombox plinth[542]: Synchronize unmigrated apps: bootstrapform, plinth
nov. 12 21:03:28 freedombox plinth[542]: Apply all migrations: contenttypes, auth
nov. 12 21:03:28 freedombox plinth[542]: Synchronizing apps without migrations:
nov. 12 21:03:28 freedombox plinth[542]: Creating tables...
nov. 12 21:03:28 freedombox plinth[542]: Installing custom SQL...
nov. 12 21:03:28 freedombox plinth[542]: Installing indexes...
nov. 12 21:03:28 freedombox plinth[542]: Running migrations:
nov. 12 21:03:28 freedombox plinth[542]: No migrations to apply.
nov. 12 21:03:28 freedombox plinth[542]: .
root@freedombox:~# 

-- 
Happy hacking
Petter Reinholdtsen
