### ISSUE TITLE
[768666] plinth: Fail to enable hidden services on freshly created FreedomBox

### ISSUE THREAD

**Issue by FedericoCeratto** [freedombox/Plinth#113]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <2fl61eovrbc.fsf@diskless.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Package: plinth
Version: 0.4.1-1

When trying to configure a tor hidden service on the fresly configured
Freedombox based on unstable, plinth gave this exception:

[2014-11-08 22:31:58,204] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/tor', 'get-hs'], , Traceback (most recent call last):
  File "/usr/share/plinth/actions/tor", line 194, in <module>
    main()
  File "/usr/share/plinth/actions/tor", line 190, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/tor", line 90, in subcommand_get_hs
    print(get_hidden_service())
  File "/usr/share/plinth/actions/tor", line 178, in get_hidden_service
    with open(os.path.join(hs_dir, 'hostname'), 'r') as conf_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/tor/hidden_service/hostname'

I was running plinth manually because it did not seem to work properly
when running from the boot system.

I tried running

  mkdir /var/lib/tor/hidden_service
  chown debian-tor:debian-tor /var/lib/tor/hidden_service
  service tor restart

but this did not work becuase this change was done to /etc/tor/torrc,
and the 10.0.2.16 IP address were not available on the Freedombox
machine.  Only the 192.168.122.102 address were active at the time.

diff --git a/tor/torrc b/tor/torrc
index 7af855e..0ff6f55 100644
--- a/tor/torrc
+++ b/tor/torrc
@@ -14,3 +14,9 @@ AutomapHostsOnResolve 1
 TransPort 127.0.0.1:9040
 DNSPort 127.0.0.1:53
 
+SocksPort 10.0.2.16:9050
+TransPort 10.0.2.16:9040
+DNSPort 10.0.2.16:53
+SocksPort 192.168.122.102:9050
+TransPort 192.168.122.102:9040
+DNSPort 192.168.122.102:53

After removing the lines with 10.0.2.16 and restarting, plinth was back
to showing the tor status web page again.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20141109205707.GP20295@ulrik.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Control: tags -1 + patch

I suspect this untested patch will solve the issue.

diff --git a/actions/tor b/actions/tor
index 5e9b49c..03fec5a 100755
--- a/actions/tor
+++ b/actions/tor
@@ -24,10 +24,13 @@ Configuration helper for the Tor service
 import argparse
 import os
 import subprocess
+import pwd
+import grp
 
 SERVICE_CONFIG = '/etc/default/tor'
 TOR_CONFIG = '/etc/tor/torrc'
 
+hiddenpath = "/var/lib/tor/hidden_service"
 
 def parse_arguments():
     """Return parsed command line arguments as dictionary"""
@@ -99,7 +102,7 @@ def subcommand_enable_hs(_):
         lines = conffile.readlines()
 
     lines.append('# Hidden Service configured by Plinth\n')
-    lines.append('HiddenServiceDir /var/lib/tor/hidden_service/\n')
+    lines.append('HiddenServiceDir %s/\n' % hiddenpath)
     lines.append('HiddenServicePort 80 127.0.0.1:80\n')
     lines.append('HiddenServicePort 443 127.0.0.1:443\n')
     lines.append('# end of Plinth Hidden Service config\n')
@@ -107,6 +110,16 @@ def subcommand_enable_hs(_):
     with open(TOR_CONFIG, 'w') as conffile:
         conffile.writelines(lines)
 
+    try:
+        os.makedirs(path, 0700)
+        os.chown(hiddenpath,
+                 getpwnam("debian-tor").pw_uid,
+                 grp.getgrnam("debian-tor").gr_gid=0)
+    except OSError as e:
+        if e.errno == errno.EEXIST and os.path.isdir(path):
+            pass
+        else: raise
+
     subprocess.call(['service', 'tor', 'restart'])
 
 
Is this a good approach for fixing the problem?  An alternative is to
do it in freedombox-setup at build time.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <367203305.7079.1415573119271.JavaMail.open-xchange@ox1app>
BTS author: James Valleroy <jvalleroy@mailbox.org>

I don't think it's necessary to create the folder for the hidden service.
Tor should do that when it starts up (but in your case it did not start
successfully).

I think we just need to add some guard code in case we can't open the
torrc or hidden service folder. (This doesn't solve the Tor configuration
problem but it should allow Plinth to keep working.)

diff --git a/actions/tor b/actions/tor
index f0744cc..955e12a 100755
--- a/actions/tor
+++ b/actions/tor
@@ -190,18 +190,24 @@ def get_hidden_service():
     hs_dir = None
     hs_ports = []
 
-    with open(TOR_CONFIG, 'r') as conf_file:
-        for line in conf_file:
-            if line.startswith('HiddenServiceDir'):
-                hs_dir = line.split()[1]
-            elif line.startswith('HiddenServicePort'):
-                hs_ports.append(line.split()[1])
+    try:
+        with open(TOR_CONFIG, 'r') as conf_file:
+            for line in conf_file:
+                if line.startswith('HiddenServiceDir'):
+                    hs_dir = line.split()[1]
+                elif line.startswith('HiddenServicePort'):
+                    hs_ports.append(line.split()[1])
+    except Exception:
+        return ''
 
     if not hs_dir:
         return ''
 
-    with open(os.path.join(hs_dir, 'hostname'), 'r') as conf_file:
-        hs_hostname = conf_file.read().strip()
+    try:
+        with open(os.path.join(hs_dir, 'hostname'), 'r') as conf_file:
+            hs_hostname = conf_file.read().strip()
+    except Exception:
+        return ''
 
     return hs_hostname + ' ' + ','.join(hs_ports)

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <54623B5E.1060203@medhas.org>
BTS author: Sunil Mohan Adapa <sunil@medhas.org>

On Monday 10 November 2014 04:15 AM, James Valleroy wrote:
> I don't think it's necessary to create the folder for the hidden service.
> Tor should do that when it starts up (but in your case it did not start
> successfully).
> 
> I think we just need to add some guard code in case we can't open the
> torrc or hidden service folder. (This doesn't solve the Tor configuration
> problem but it should allow Plinth to keep working.)
> 

I agree with James' approach.  Tor simply need to run at least once
before we start showing Hidden service information.  If hidden service
information is not available we need to show that state appropriately to
the user.

I have just merged a pull request made upstream by James along these
lines[1].  I have tested the changes and things seem to work okay.  I
have stopped tor, ensured hidden services are enabled and remove the
hidden service information directory and tried to view status in Plinth.
 This time we are handling the case properly.  Please check that this is
okay.

Links:

1) https://github.com/freedombox/Plinth/pull/21

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
The original bug on BTS is closed.  Looks like the last message of the bug which closes the bug was not imported.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <2fl61eovrbc.fsf@diskless.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Package: plinth
Version: 0.4.1-1

When trying to configure a tor hidden service on the fresly configured
Freedombox based on unstable, plinth gave this exception:

[2014-11-08 22:31:58,204] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/tor', 'get-hs'], , Traceback (most recent call last):
  File "/usr/share/plinth/actions/tor", line 194, in <module>
    main()
  File "/usr/share/plinth/actions/tor", line 190, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/tor", line 90, in subcommand_get_hs
    print(get_hidden_service())
  File "/usr/share/plinth/actions/tor", line 178, in get_hidden_service
    with open(os.path.join(hs_dir, 'hostname'), 'r') as conf_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/tor/hidden_service/hostname'

I was running plinth manually because it did not seem to work properly
when running from the boot system.

I tried running

  mkdir /var/lib/tor/hidden_service
  chown debian-tor:debian-tor /var/lib/tor/hidden_service
  service tor restart

but this did not work becuase this change was done to /etc/tor/torrc,
and the 10.0.2.16 IP address were not available on the Freedombox
machine.  Only the 192.168.122.102 address were active at the time.

diff --git a/tor/torrc b/tor/torrc
index 7af855e..0ff6f55 100644
--- a/tor/torrc
+++ b/tor/torrc
@@ -14,3 +14,9 @@ AutomapHostsOnResolve 1
 TransPort 127.0.0.1:9040
 DNSPort 127.0.0.1:53
 
+SocksPort 10.0.2.16:9050
+TransPort 10.0.2.16:9040
+DNSPort 10.0.2.16:53
+SocksPort 192.168.122.102:9050
+TransPort 192.168.122.102:9040
+DNSPort 192.168.122.102:53

After removing the lines with 10.0.2.16 and restarting, plinth was back
to showing the tor status web page again.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20141109205707.GP20295@ulrik.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Control: tags -1 + patch

I suspect this untested patch will solve the issue.

diff --git a/actions/tor b/actions/tor
index 5e9b49c..03fec5a 100755
--- a/actions/tor
+++ b/actions/tor
@@ -24,10 +24,13 @@ Configuration helper for the Tor service
 import argparse
 import os
 import subprocess
+import pwd
+import grp
 
 SERVICE_CONFIG = '/etc/default/tor'
 TOR_CONFIG = '/etc/tor/torrc'
 
+hiddenpath = "/var/lib/tor/hidden_service"
 
 def parse_arguments():
     """Return parsed command line arguments as dictionary"""
@@ -99,7 +102,7 @@ def subcommand_enable_hs(_):
         lines = conffile.readlines()
 
     lines.append('# Hidden Service configured by Plinth\n')
-    lines.append('HiddenServiceDir /var/lib/tor/hidden_service/\n')
+    lines.append('HiddenServiceDir %s/\n' % hiddenpath)
     lines.append('HiddenServicePort 80 127.0.0.1:80\n')
     lines.append('HiddenServicePort 443 127.0.0.1:443\n')
     lines.append('# end of Plinth Hidden Service config\n')
@@ -107,6 +110,16 @@ def subcommand_enable_hs(_):
     with open(TOR_CONFIG, 'w') as conffile:
         conffile.writelines(lines)
 
+    try:
+        os.makedirs(path, 0700)
+        os.chown(hiddenpath,
+                 getpwnam("debian-tor").pw_uid,
+                 grp.getgrnam("debian-tor").gr_gid=0)
+    except OSError as e:
+        if e.errno == errno.EEXIST and os.path.isdir(path):
+            pass
+        else: raise
+
     subprocess.call(['service', 'tor', 'restart'])
 
 
Is this a good approach for fixing the problem?  An alternative is to
do it in freedombox-setup at build time.

-- 
Happy hacking
Petter Reinholdtsen
