### ISSUE TITLE
login: Improper redirect

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1138]
After trying to login with the wrong password a few times, a captcha is displayed. But if I then login with correct password and solving captcha, then I end up at this url:
https://localhost:4430/plinth/accounts/login/locked/locked/locked/locked/locked/locked/locked/locked/locked/locked/locked/
And the browser says "The page isn’t redirecting properly".

**Comment by JosephKiranBabu** [comment]
@jvalleroy Is this with the new version of django-axes (3.0.1)?
