### ISSUE TITLE
[754117] plinth: broken from last update

### ISSUE THREAD

**Issue by FedericoCeratto** [freedombox/Plinth#114]

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20140707172914.19076.37057.reportbug@wheezy.localdomain>
BTS author: tester <humberto@example.com>

Package: plinth
Version: 0.3.2.0.git.20140621-1
Severity: normal

Dear Maintainer,

*** Reporter, please consider answering these questions, where appropriate ***

 I tried a few ways to make this work and had it working with the old version
that was in testing, as soon as the sid version hit testing, it reports missing
html files.
This is extremely annoying because it even breaks the where to find help part
of plinth, it does not show the first time login or any of that because it cant
find the files. I have found django to break things this way as updates have
broke my mumble admin page also, Im not sure where its broken sorry

*** End of the template - remove these template lines ***



-- System Information:
Debian Release: jessie/sid
  APT prefers testing
  APT policy: (500, 'testing'), (500, 'stable')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 3.14-0.bpo.1-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash

**Comment by SunilMohanAdapa** [comment]
The original bug on BTS is closed.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <20140707172914.19076.37057.reportbug@wheezy.localdomain>
BTS author: tester <humberto@example.com>

Package: plinth
Version: 0.3.2.0.git.20140621-1
Severity: normal

Dear Maintainer,

*** Reporter, please consider answering these questions, where appropriate ***

 I tried a few ways to make this work and had it working with the old version
that was in testing, as soon as the sid version hit testing, it reports missing
html files.
This is extremely annoying because it even breaks the where to find help part
of plinth, it does not show the first time login or any of that because it cant
find the files. I have found django to break things this way as updates have
broke my mumble admin page also, Im not sure where its broken sorry

*** End of the template - remove these template lines ***



-- System Information:
Debian Release: jessie/sid
  APT prefers testing
  APT policy: (500, 'testing'), (500, 'stable')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 3.14-0.bpo.1-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <E1XNcFo-0008NN-7k@franck.debian.org>
BTS author: Petter Reinholdtsen <pere@debian.org>

Source: plinth
Source-Version: 0.3.2.0.git.20140829-1

We believe that the bug you reported is fixed in the latest version of
plinth, which is due to be installed in the Debian FTP archive.

A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 754117@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Petter Reinholdtsen <pere@debian.org> (supplier of updated plinth package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@ftp-master.debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Format: 1.8
Date: Sat, 30 Aug 2014 08:26:06 +0200
Source: plinth
Binary: plinth
Architecture: source all
Version: 0.3.2.0.git.20140829-1
Distribution: unstable
Urgency: high
Maintainer: Tzafrir Cohen <tzafrir@debian.org>
Changed-By: Petter Reinholdtsen <pere@debian.org>
Description: 
 plinth     - web front end for administering every aspect of a Freedom Box
Closes: 754117
Changes: 
 plinth (0.3.2.0.git.20140829-1) unstable; urgency=high
 .
   * Updated to new git version from Nick Daly based on commit
     250b0100aab236fcf9dfa65eccf656fe037f9422.
     - Fixes broken web pages (Closes: #754117).
   * Updated patch program-paths.diff to include actions_dir setting,
     and drop now obsolete patch actions-path.diff.
Checksums-Sha1: 
 033abef555a5ed427b5554e4e46d850754bc11dc 1562 plinth_0.3.2.0.git.20140829-1.dsc
 8c1e15c91b674b0a146db75d1b7b091c66d57a72 1809035 plinth_0.3.2.0.git.20140829.orig.tar.gz
 29358e51a66a8d752f43e1153677bade30b37d38 5743 plinth_0.3.2.0.git.20140829-1.debian.tar.gz
 c63f84f7888ed65fc998e75f8e4491854f7efee0 1855674 plinth_0.3.2.0.git.20140829-1_all.deb
Checksums-Sha256: 
 a15e88f583d3a3176eeeaed65cdfc48d32ce5497bd9d1d14800c02ce1a8466d4 1562 plinth_0.3.2.0.git.20140829-1.dsc
 5b9f01e3911ed7e46ffdfc8b587597b5fd6252bc01d15605af06125112cc2582 1809035 plinth_0.3.2.0.git.20140829.orig.tar.gz
 0c8075362867df0fd538835e8c429e600d5c068ee97427a2b46eabb882d6c785 5743 plinth_0.3.2.0.git.20140829-1.debian.tar.gz
 40b460ef97b6a9d80844864c872e08c419193275b88107331450b2c1984253e1 1855674 plinth_0.3.2.0.git.20140829-1_all.deb
Files: 
 4180839367675559b366e0e4fec5c88d 1562 python optional plinth_0.3.2.0.git.20140829-1.dsc
 63ad3051dab04d9199df76f5caabf463 1809035 python optional plinth_0.3.2.0.git.20140829.orig.tar.gz
 485becde591db8ec12612c04090ad6a0 5743 python optional plinth_0.3.2.0.git.20140829-1.debian.tar.gz
 4cf8c8ec5b5411ea27733eaefa6fcdb5 1855674 python optional plinth_0.3.2.0.git.20140829-1_all.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.12 (GNU/Linux)

iD8DBQFUAW6a20zMSyow1ykRAvJ3AJ9BfpIjqUGr9ON3giENn0uxgudT/wCeKpyR
D2r24xJT2Yb278pe5BBmQew=
=RwGQ
-----END PGP SIGNATURE-----
