### ISSUE TITLE
action scripts:  Make handling parameters and return values more comfortable

### ISSUE THREAD

**Issue by fonfon** [freedombox/Plinth#115]
Passing parameters to and returning results from action scripts can be tedious.

There should be a more comfortable but still secure way. Something flexible and universal like JSON would be good, but it has to be safe (escaping malicious user input).

Any 'best practice' to pass around key-value pairs (or more) in a sane and safe way would be highly appreciated. Otherwise people writing action scripts will all try to solve the same problem (i.e. here: https://github.com/freedombox/Plinth/pull/81/files#diff-da929b508af4cef3e8859fb70d87330aR240)

**Comment by NickDaly** [comment]
JSON (YAML, or even good old XML) seems like a good choice for structured output, but shell scripts don't make using that easy.  We can write action scripts in any supported language, preferrably one that supports structured output better.

I don't see a need for complicated things like namespaces or custom DTDs right now.  XML seems most widely supported, but also the most complicated.  Not trying to start a format war here, so let's just pick something that's supported well-enough and roll with it.

**Comment by fonfon** [comment]
It's already possible to return JSON for a while now.
