### ISSUE TITLE
Please remove Google's DNS from BIND

### ISSUE THREAD

**Issue by marcdraco** [freedombox/Plinth#1158]
I'm still getting to know my way around here so please forgive my ignorance as to where to leave these.

I have fairly strong feelings toward Google (or any company that seeks to benefit from mining user data) so it was pretty shocking to see Google's DNS servers offered when BIND is installed. The Wikipedia page outlines some of what Google _admits_ to. 

https://en.wikipedia.org/wiki/Google_Public_DNS

OpenNIC appears to be a suitable alternative.

https://en.wikipedia.org/wiki/OpenNIC

I would imagine there are others owned and operated by companies which don't mine and do use open source. It seems to go against the spirit of FreedomBox to allow Google (or any other commercial) service to creep in when there are perfectly functional alternatives.

**Comment by jvalleroy** [comment]
Is a forwarder needed? What is the impact of not using forwarding?

**Comment by marcdraco** [comment]
I have to admit to being a bit blindsided by this whole thing. However, when I clicked the option to add BIND (everything seemed fine without it) Google's DNS fired off... Someone else on the maillist had the same point - something to do with Prism although this is all beyond me. I just resent Google's spying.

**Comment by testbird** [comment]
Such fallback defaults ("only for unconfigured states" Every device starts unconfigured!) are also an issue with systemd (and docker).
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761658

**Comment by testbird** [comment]
Note the stance of the debian maintainer and how such default fallbacks have not been removed upon request.
They are silently in use when whatever is manually configured is not available.

**Comment by SunilMohanAdapa** [comment]
@jvalleroy , because we have removed default forwarders, is this bug considered fixed? Existing users from whom the forwarders have been set will need to manually remove them, but new users will not have forwarders. I suppose it is not right for us to remove the forwarders for existing users.

**Comment by testbird** [comment]
This rather intrusive default dns resolving configuration in the interest of a third party should never have been introdroduced by a debian dev in the first place. It also makes broken or mis-configurations hard to detect. So notifying the user about what depependency had been shipped to him, and possibly switching to relying on dynamic dhcp configured dns for fallback instead of hard preconfigrations, could be preferable.

**Comment by SunilMohanAdapa** [comment]
On Thursday 11 January 2018 04:06 PM, testbird wrote:
> This rather intrusive default dns resolving configuration in the
> interest of a third party should never have been introdroduced by a
> debian dev in the first place.

Please assume good faith on part of the developer who introduced this. I
don't believe it was done in the interest of a third party (although it
may benefit them).

-- 
Sunil

**Comment by testbird** [comment]
Sorry, if it could be read differently, didn't mean to assume, just state the same as you wrote. I don't know who introduced this, in the thread linked above one only sees responsible persons raising and explaining issues and the reaction.

**Comment by marcdraco** [comment]
I raised an initial request regarding this so that might have been me (I know others have raised similar concerns).

Anything in Freedombox that directly benefits a large commercial outfit such as Google is completely contrary to the ideas promoted therein. Google does a lot of this sort of thing by stealth and clever purchasing: those guys are smart. 8.8.8.8 and 8.8.4.4 are pretty easy to remember over every other public DNS I can find.  I know my own ISP's because they are very similar to a 192.x.x.x address but that is unusual.

Google has been particularly clever in supporting the little guy developing Open Source with things like Summer of Code and (apparently) giving away huge amounts of free software. It's like a drug dealer, apparently smiling and benevolent as it gets you hooked more and more on its products. However, once those products fail to produce results, they are pulled without mercy. Picasa, for example, is no longer officially available and I know several people who are floundering without it - after becoming hooked on those easy-to-use features. Like "baby duck" addicts, they are unable to easily switch to a truly open system.

This cost has always been far too high for me and I strongly believe that Freedombox (and ultimately, Debian too) needs to take a stand against companies which seek to remove our freedoms. Google already gets a huge amount of private data via the back door through pretty much every Android box on the planet. Even the Chinese hacks that don't carry the GoS and branding seem to rely on GDNS.

This is simply a form of mass surveillance of the type Freedomboxes are supposed to avoid so someone needs to stand up and stay, "No it's NOT OK Google."

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by testbird** [comment]
Yes, thank you for raising the issue, and the FBX devs for actually fixing it! Everyone can compare with the (not fixed, marked done) debian bug.

@marcdraco It's not yet in debian/FBX, but should already be installable from upstream repository https://www.mailpile.is/faq/#enc-12

**Comment by SunilMohanAdapa** [comment]
@marcdraco @testbird Thank you both for contributing to this discussion. I am sure the rest of the FreedomBox community with you on protecting user privacy. Also many thanks to the devs who implemented this and updated it.

Let us create separate issues for other ideas raised such as using dynamic DHCP information. I am closing this issue, please feel free to reopen it if you feel necessary.
