### ISSUE TITLE
Update despite auto update?

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#1163]
Can somebody explain what kind of update this is: ?
![image](https://user-images.githubusercontent.com/164785/33689021-0bbd11ce-dade-11e7-89f8-e8df268d2cd6.png)

I enabled auto update and expected FreedomBox to either update automatically – OR –
 notify me if manual updates are necessary.

**Comment by mray** [comment]
Updating failed:

![image](https://user-images.githubusercontent.com/164785/33689102-6b80df00-dade-11e7-92a2-02369d4bd0c2.png)

**Comment by mray** [comment]
Looks like after trying this stunt my FreedomBox does not boot up properly anymore. Anybody knows what could be going on - or how to fix this? Booting with HDMI attached screen shows nothing, ssh login not possible either.

**Comment by jvalleroy** [comment]
To answer the first question: unattended-upgrades will upgrade all the Debian packages that it can. Each module in Plinth (which is not the same as a package) has a version number, and when the version number increases, it needs to run its setup process again. This part isn't automated yet.

**Comment by JosephKiranBabu** [comment]
> This part isn't automated yet.

@jvalleroy When Plinth starts up, it also looks for Apps that have been updated (incremented version number) and runs setup for them. I think this feature was available since 0.15.3.

**Comment by mray** [comment]
Looks like this has been taken care of then. Closing.
