### ISSUE TITLE
Outdated freedomboxfoundation.org website misleads new adopters

### ISSUE THREAD

**Issue by JosephKiranBabu** [freedombox/Plinth#1166]
People who just discovered FreedomBox are trying out the 0.9 images from the _News_ section of the freedomboxfoundation.org website and reporting issues. 
We should prevent this hassle in the first place by making the Foundation website point to the freedombox.org site where the latest images are available.

Linking freedombox.org was mentioned earlier in https://github.com/freedombox/freedombox.org/issues/39
There's also an issue to redesign the Foundation website. https://github.com/freedombox/freedombox.org/issues/41

But this is more urgent in my opinion as it is causing a lot of discomfort for new adopters.

**Comment by JosephKiranBabu** [comment]
A simple fix I can think of, is to move the _News_ section to another page and prompt the visitors to the Foundation website to go to freedombox.org to download their images.

**Comment by jvalleroy** [comment]
@gnoutchd Do you know who can help with this?

**Comment by SunilMohanAdapa** [comment]
We are planning to schedule the following tasks for the next release:
* Create git repo for the website
* Remove some redundant pages
* Link to freedombox.org

I believe we already have access to the website provided by @gnoutchd . Otherwise, we will seek it again.

**Comment by utilum** [comment]
What is the status of the site, please?

```$ ping -q freedombox.org
PING freedombox.org (207.237.164.240) 56(84) bytes of data.
^C
--- freedombox.org ping statistics ---
98 packets transmitted, 0 received, +1 errors, 100% packet loss, time 99361ms
pipe 5
```

**Comment by JosephKiranBabu** [comment]
@utilum There was a temporary outage of the websites.
See this message. https://lists.alioth.debian.org/pipermail/freedombox-discuss/2018-January/008237.html

Now they are up.

**Comment by JosephKiranBabu** [comment]
The links to the outdated images are now removed in the current version of the FreedomBox Foundation website. 
Closing this.

**Comment by JosephKiranBabu** [comment]
Moved the tasks mentioned above by @SunilMohanAdapa to https://github.com/freedombox/freedombox-todos/issues/51
