### ISSUE TITLE
storage: Remove beta-warning for root expansion

### ISSUE THREAD

**Issue by JoKeyser** [freedombox/Plinth#1176]
When expanding the root partition, there is this warning:
> This feature is still in beta. Use at your own risk.

Should this still be considered beta?
If so, we should also get this string translated - currently only English will be shown due to missing tags, see [plinth/modules/storage/templates/storage_expand.html#L31](https://github.com/freedombox/Plinth/blob/master/plinth/modules/storage/templates/storage_expand.html).
If it's not beta anymore, we should get rid of it!

**Comment by SunilMohanAdapa** [comment]
I have had good experiences with this feature an I think it is stable and reliable.  We should remove it now.

**Comment by SunilMohanAdapa** [comment]
Although I labeled it 'beginner', we can finish this up if we want it addressed immediately.

**Comment by SunilMohanAdapa** [comment]
Fixed in #1189 .
