### ISSUE TITLE
diagnostics: Disable button only when service is not enabled (not when it is not running)

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#1181]
This is a follow up of #829.

Currently, when app are not running, the diagnostics button is disabled. This should instead be changed such that diagnostics button is disabled when an app is disabled. Reasoning as follows:

- When an app is enabled but not running due to a grave system error, we would like to perform diagnostics and understand what is wrong. This would answer questions such as "Is something wrong with webserver configuration or with the daemon?".
- For applications such as ikiwiki, there is no concept of "running" daemons. For them currently the diagnostics button is always disabled.

**Comment by mray** [comment]
Maybe there is a problem? "Running" and "enabled" should be indistinguishable for a user (on/off state in the card UI). My understanding is that an application that gets enabled but does not run is **the** perfect candidate to run diagnostics on. Not sure if that matches your proposal.

**Comment by SunilMohanAdapa** [comment]
@mray, You are right, we should be able to run diagnostics on application that is enabled and not running.  This issue should address that.

When we have everything working smoothly we can look forward to removing "running" status display from the user. Because all the user need to know is whether something is enabled or disabled (on/off). Every enabled application must work.

**Comment by SunilMohanAdapa** [comment]
This is fixed in #1192. Now Diagnostics button is dependent on whether a service is enabled.
