### ISSUE TITLE
help: menu is hidden on smaller screens

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1185]
For the Apps and Configuration pages, the menu is shown above the content for narrow screens. But for the Help page, the menu is not shown.

**Comment by mray** [comment]
I guess you mean the text label is missing next to the question mark icon:

![image](https://user-images.githubusercontent.com/164785/34539511-0f08c9b4-f0d1-11e7-9252-d4ba048a5bac.png)

**Comment by jvalleroy** [comment]
Sorry, I meant that the sub-menu on the left side disappears.

Full width:
![plinth_help_1](https://user-images.githubusercontent.com/178876/34546635-1de91406-f0c3-11e7-9f6b-c2ed87d2ff05.png)

Half width:
![plinth_help_2](https://user-images.githubusercontent.com/178876/34546638-1fc2d352-f0c3-11e7-9560-5a62fdad3379.png)

**Comment by SunilMohanAdapa** [comment]
This is fixed in #1201. Please reopen otherwise.
