### ISSUE TITLE
Use ruamel.yaml for roundtrip editing for YAML files

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#119]
We are currently using python3-yaml for reading YAML files and writing them in a custom way (at least in xmpp module).  Instead using ruamel.yaml library to read and write YAML files so that comments, mapping item order etc. are preserved.

**Comment by SunilMohanAdapa** [comment]
Remove the unused dependency on YAML module after using this.

**Comment by jvalleroy** [comment]
I've opened an RFP for this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803007

**Comment by SunilMohanAdapa** [comment]
The RFP bug is now closed and python3-ruamel.yaml should be available soon in unstable.

**Comment by jvalleroy** [comment]
Using ruamel.yaml to do a round trip load + dump of ejabberd.yml, I found that it makes some changes that ejabberd can't handle (like removing " around strings). I think we will have to override some function as shown in https://stackoverflow.com/questions/27947653/force-quotes-in-yaml-dump-python.

**Comment by SunilMohanAdapa** [comment]
This is now fixed with #566. Ejabberd configuration is the only place where we are altering YAML files.  So, ruamel.yaml's usage is comprehensive.
