### ISSUE TITLE
Unable to obtain Let's Encrypt certificate

### ISSUE THREAD

**Issue by gemographist** [freedombox/Plinth#1198]
I've removed a few bits of trivial information for privacy reasons. I'm aware, my freedombox is indeed accessible from the internet using domain name and public ip address. I've forwarded ports 80 and 443. I've tried changing the domain name so that it included www. in front of it, in DNS Client and Configure in the Settings.

I received this error

> Failed to obtain certificate for domain www.blahblah.sds-ip.de: Saving debug log to /var/log/letsencrypt/letsencrypt.log Obtaining a new certificate Performing the following challenges: http-01 challenge for www.blahblah.sds-ip.de Using the webroot path /var/www/html for all unmatched domains. Waiting for verification... Cleaning up challenges Failed authorization procedure. www.blahblah.sds-ip.de (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://www.blahblah.sds-ip.de/.well-known/acme-challenge/LMDltMQn1bjD--Xhs880W4l5puZC3voim: Timeout 

I'm a beginner so I don't know how to get to the /var/ directory to grab the logs if these are necessary.

**Comment by JoKeyser** [comment]
Hi, thanks for reporting.
The leading `www.` should not be necessary, and is probably not a good idea.
I'm assuming you're connecting over IPv4?
Can you post which version of Plinth you're using? (Check e.g. at Help > About).
How did you determine that your box is indeed reachable? (It can be misleading if you're connecting from within your own network...)

**Comment by gemographist** [comment]
I believe I'm connecting over IPv4 - just assuming this because I can enter my public IP address (consisting of decimal, not hexadecimal). I'm also assuming I'm reaching the fbx from the net as I could enter in the domain name I registered with GNUDIP and can access it. I might be wrong though as I've only tried from within my own network. 

I'm running Plinth version 0.13.1.

**Comment by JoKeyser** [comment]
Thanks for the info so far. Certainly sounds good that the domain resolves to your IP, and it sounds like IPv4 indeed (if it's 4 numbers, e.g. 141.153.159.78).

Could you perform a portscan of ports 80 and 443 from somewhere outside of your network? That's the only way to be sure whether they're actually reachable. Pick any service you like, e.g. http://www.whatsmyip.org/port-scanner/server/ , or ask a friend.

**Comment by JoKeyser** [comment]
Oh, another thought: Depending on your router, you might have to whitelist the domain you're using. Some routers try to protect against "DNS rebinding attacks", see e.g. https://en.avm.de/service/fritzbox/fritzbox-7390/knowledge-base/publication/show/663_No-DNS-resolution-of-private-IP-addresses/

However that doesn't seem to be the problem, since you can resolve your domain from within the network...

**Comment by gemographist** [comment]
I am indeed running fbx behind a router. Portscanner shows that port 443 and 80 "timed out" but not closed, and DNS port 53 is open. This is odd because I put the freedombox in a DMZ, and the ports are supposedly forwarded to it according to my router.

**Comment by JoKeyser** [comment]
Okay but at least we now know that it's just a connection problem. In my router I have to create a port forwarding and 'apply' it in 2 steps. I also have to select that they are TCP ports, as opposed to UDP... Is the time-out of ports 80 and 443 special in the sense that others are just closed?
What does the `Diagnose` button say on the Freedombox Let's Encrypt page?

**Comment by gemographist** [comment]
I've double checked and they're definitely turned on and the router has been reset a couple of times since all the settings have been changed. 

The port scanners indicate that the ports that are closed, are labelled as "Closed". Whereas for port 80 and 443 they have "Timed out."

I did notice that UPNP, NAT-PMP and Secure Mode are enabled. I'm not sure if these are getting in the way of the portforwarding rules within the DMZ. I do recall that UPNP was an issue a few years ago but I'm no networking expert.

**Comment by gemographist** [comment]
I tried switching off UPNP, NAT-PMP and Secure Mode, and I put the firewall on my router to the lowest possible protection, I turned on ALG configuration as well and this doesn't appear to have made a difference. 

As an experiment I switched the DMZ destination to a laptop behind the router, and forwarded ports 80 and 443 to it, and the portscanner shows that port 80 and 443 timed out for the laptop as well. Put the router firewall on its lowest setting and switched on/off UPNP etc. as above - still nothing. No idea what's going on here. 

Port 53 is forwarded to the freedombox behind the router and the fbx diagnostic tool, an the online portscanner both show that this port "passed". I'm at a loss. I don't understand why port 53 would be forwarded, yet port 80 and 443 are not.

**Comment by JoKeyser** [comment]
Hm, all this is certainly mysterious. I'm also no networking expert by any means. I think the most useful bit of information would be to disentangle the router from the fbx, like you did by trying with the laptop. Did you actually run any service on the laptop? Otherwise it 

There are multiple `Diagnose` buttons in the freedombox interface, did you try the one in system configuration -> Diagnostics? It should report about all services running on your box. It seems really odd that port 53 is working but the others aren't...

How is your box connected to the router, and are there any other network connections with it?

**Comment by gemographist** [comment]
> Hm, all this is certainly mysterious. I'm also no networking expert by any means. I think the most useful bit of information would be to disentangle the router from the fbx, like you did by trying with the laptop. Did you actually run any service on the laptop? Otherwise it's a foregone conclusion that the ports seem closed or time out.

No I didn't run any service from the laptop. I'm not sure how to do that (fbx does it all automatically sparing me the embarrassment of not knowing how to!). Happy to try this though if guided.

> There are multiple Diagnose buttons in the freedombox interface, did you try the one in system configuration -> Diagnostics? It should report about all services running on your box. It seems really odd that port 53 is working but the others aren't...

I used the sys config->Diagnostics tool (and the whatsmyip portscanner). It did in show all the services running on the freedombox. There is no mention of either port 80 or 443 listed on the fbx diagnostics tool. There are other ports that have "failed" but presumably that's because I've disabled the apps (like Transmission, bind etc.).

> How is your box connected to the router, and are there any other network connections with it? What network connections do you see in System configuration -> Networks?

The fbx is connected by ethernet cable into port 1 on the router. The fbx is serving as a privoxy server to a couple other laptops - one which is ethernet-cabled to port 2 of, and the other is wirelessly conntected to the router.

> Edit: I'm mainly suspecting that your router is the problem, because a) your freedombox's web service is reachable from inside the network and b) your laptop experiment showed the same negative result. That business with port 53 is confusing. Did that also show up as OK when you forward to your laptop? Maybe that's just a fluke...?

Port 53 is not defined by me in the port forwarding table of my router. Looking at the Diagnostics tool in fbx, apparently it has "passed" and it's using the protocol UDP4. I'm guessing that this is the reason it's passing, whereas the other ports are tcp?

**Comment by JoKeyser** [comment]
Hm it's weird that port 53 is "open" pretty much irrespective of what your fbx does; maybe UDP is the explanation, but if the universe tries to give us a hint here, I don't get it.

I still think the best idea is to disentangle the (suspected) router from the box to make progress.

I see two relatively easy ways: Either set up a simple service on your laptop, or make another SD card(?) with a fresh fbx install on your box...
A simple service to setup on your laptop might be an SSH server; you can ssh into your fbx and from there ssh back into your laptop to verify it's working. Once that works, you should see port 22 show as "open" if you forward it to your laptop.
On the other hand, if you have another SD card, just install fbx, load it up and never press a button - if you can reach the web interface from within the network, and forward port 443 to it, should show up as "open".

Too bad this is such an ordeal, great that you're tenacious, I'm sure you can get there.

**Comment by gemographist** [comment]
I think it's an issue with my router but I have no idea how to fix it. I setup a minetest server on a different machine and forwarded port 30000 to it, and then after running a portscanner from a site on the internet, port 30000 came back as closed. I've no idea why though port 53 is open, which is a port that I've not defined in my router port table.  Considering getting a new router because I've read the manual multiple times and looked at forums and apparently I've done everything correctly, but obviously it's not forwarding.

**Comment by gemographist** [comment]
So as a last ditch effort, I called my ISP tech support and asked them what I was doing wrong with the router they sent out, and it turns out - nothing. The reason all the ports were timing out is because there was an ISP-level firewall that prevented all inbound requests. My ISP switched off that firewall, and now all the ports are open!

The certificate from Let's Encrypt went through.

**Comment by JoKeyser** [comment]
@gemographist great that it's finally solved. I wouldn't have thought that you ISP is the reason, good that you asked. For people of the future, it may be interesting which ISP this is (and from which country).
