### ISSUE TITLE
Cannot run tests, missing requirement

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#121]
I get the following error when running ./setup.py test:
```
running test
Searching for yaml
Reading https://pypi.python.org/simple/yaml/
Couldn't find index page for 'yaml' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for yaml
error: Could not find suitable distribution for Requirement.parse('yaml')
```
It looks like the module is named pyyaml on the pypi site.

**Comment by BobGirard** [comment]
This issue has been addressed as part of pull request #122, which has just been submitted.

Going forward, when Plinth has been integrated with Travis-CI, dependency installation issues such as this can be detected and publicized as soon as a given pull request is merged into the master branch.

**Comment by SunilMohanAdapa** [comment]
Sorry for introducing this bug.  This happened when I tried to add a dependency for @jvalleroy's changes for ejabberd.  I thought I tested the dependency but clearly didn't.

**Comment by SunilMohanAdapa** [comment]
This is now fixed in master.
