### ISSUE TITLE
package: Allow setting debconf selections before package is installed?

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#130]
When ejabberd and jwchat are setup by freedombox-setup, some debconf selections are set before the packages are installed:
https://github.com/petterreinholdtsen/freedombox-setup/blob/master/setup.d/85_jwchat#L8

I'm thinking that it would be useful if package.py allowed debconf selections to be specified somehow in the @package.required decorator.

**Comment by SunilMohanAdapa** [comment]
PackageKit provides for a way to interact with the installation process by providing a socket on which we can provide debconf answers.  That is one direction for exploration but there is scope for introducing some bugs.

Another possibility is that we implement a "before_install=" handler to @package.required decorator which will be called just before trying to install a package.  In this we can call a helper function in packages.py to set the debconf selections.  This will be more generic.

**Comment by SunilMohanAdapa** [comment]
This has been implemented as part of #143.
