### ISSUE TITLE
PackageKit error: Cannot refresh cache whilst offline

### ISSUE THREAD

**Issue by fonfon** [freedombox/Plinth#136]
I get a packagekit error when installing packages via Plinth, independent on the package (mumble-server, pagekite, ...). The exact error is:
`GLib.Error: pk_client_error: Cannot refresh cache whilst offline (257)`

When I comment out the packagekit `client.refresh_cache` in `plinth/package.py` lines 128-130 (https://github.com/freedombox/Plinth/blob/master/plinth/package.py#L128) it works again.

I got an up-and-running internet connection; `apt-get update` works fine but doesn't resolve the problem.

*update*
I'm running my FreedomBox in a Virtualbox and did a `aptitude sys-upgrade` recently, staying on sid.

**Comment by SunilMohanAdapa** [comment]
I faced this issue once myself.  I am suspecting that it has to do with network manager + some virtual network configuration.

Could you please try the following experiment?  Add another network interface to the virtual machine and configure it using 'nmcli'.  Try the above and see if things are okay now.

**Comment by fonfon** [comment]
I added another NAT adapter to the VM, then the upgrades worked immediately without any nmcli configuration.
I shutdown the VM and removed the adapter -- and upgrades were broken again.

My other adapters are one NAT and one host-only adapter.

**Comment by SunilMohanAdapa** [comment]
With 0.5 release, we are using network-manager for all types of connections making sure that an Internet connected system has at least one connection configured in network manager.  If packagekit is using network manager to query the online status of the system, this should fix the issue.

Could you please check if you are able to reproduce the problem with the FreedomBox 0.5?

**Comment by SunilMohanAdapa** [comment]
This bug and expected behavior of the packagekit is discussed here:
https://bugs.freedesktop.org/show_bug.cgi?id=71792

**Comment by jvalleroy** [comment]
Fixed in #493.
