### ISSUE TITLE
package: Install recommends.

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#139]
From my testing, I've observed that when a required package is installed, the recommends for that package are not installed. Would it be possible to add an option to also install the recommends?

**Comment by jvalleroy** [comment]
I'm not sure this is really needed after all. It's probably better to select the exact packages that we need, so we don't bring in a lot of extras.

**Comment by jvalleroy** [comment]
Sunil has pointed out a case where we might need to install recommends, that is when the app has recommended plugins (owncloud is one example).

**Comment by SunilMohanAdapa** [comment]
Also a lot of nice functionality for some applications is as part of recommends.

**Comment by jvalleroy** [comment]
Fixed in #493.
