### ISSUE TITLE
Add support to create a PPPoE connection

### ISSUE THREAD

**Issue by steglicd** [freedombox/Plinth#155]
The network configuration should be extended to configure a PPPoE based connection.
When creating a new network connection, there should be a Ip assignement protocol named PPPoE.

If this protocol is selected, the user needs to enter user credentials. Afterwards the networkmanager should bringup the PPPoE connection.

**Comment by steglicd** [comment]
@SunilMohanAdapa 
I'm working on this and want to change the HTML javascript form helper behaviour:
* currently fields that are not needed are greyed out
* I would like to change this and hide the fields that are not required 

This is because the form becomes a bit more clearly.

I try to keep the whole page working even with disabled javascript.

**Comment by steglicd** [comment]
@SunilMohanAdapa 
this feature requires the debian packages ppp and pppoe

should we add the packages to the fredom-maker? or should we dynamically install the packages?

**Comment by SunilMohanAdapa** [comment]
On 08/04/2015 01:10 AM, Daniel Steglich wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa>
> I'm working on this and want to change the HTML javascript form helper
> behaviour:
> 
>   * currently fields that are not needed are greyed out
>   * I would like to change this and hide the fields that are not required
> 
> This is because the form becomes a bit more clearly.
> 
> I try to keep the whole page working even with disabled javascript.

Hiding fields that are not needed sounds good.  We did this with
pagekite with page specific Javascript where many fields are shown only
when we enable the module first.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
On 08/04/2015 02:43 AM, Daniel Steglich wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa>
> this feature requires the debian packages ppp and pppoe
> 
> should we add the packages to the fredom-maker? or should we dynamically
> install the packages?

Asking a user to install packages from the Internet while she is trying
to connect to the Internet is not nice :)

We should add these two packages as dependencies to freedombox-setup so
that Debian users installing freedombox-setup package have the same
experience as users using pre-built images.

-- 
Sunil

**Comment by steglicd** [comment]
@SunilMohanAdapa 
My first though was to add a new IPv4 addressing method. Like: DHCP, manual, PPPoE and  add this functionality to the "Add a Ethernet connection" page (no new choice when adding a connection -> Ethernet or Wi-Fi).

When I was coding, I extended my understanding of Networkmanager way of doing PPPoE connections. It is a completely different type (even if it is only a IP addressing method - from the users point of view)

I pushed two branches:
network-pppoe
network-pppoe-type

network-pppoe isn't finished yet but as you can see, the code will be messed up (inside the network helper functions for adding a ethernet connection, there will be a lot of "if connection == pppoe").
And also javascript is needed to hide/unhide fields within the HTML form (username/password vs. IP address fields).

within network-pppoe-type the code  looks a lot cleaner, and no javascript is needed. The connection types are independent.

What do you think? Should I continue to work on network-pppoe-type? The user will get a choice box like:
* Wi-Fi
* Ethernet
* PPPoE

and the related settings will be requested.

**Comment by SunilMohanAdapa** [comment]
I think the current implementation is quite nice.  @steglicd, if you agree that the current implementation is satisfactory, we can close the bug.

**Comment by SunilMohanAdapa** [comment]
Closing after discussion with @steglicd .
