### ISSUE TITLE
Allow binding network connections to a linux device

### ISSUE THREAD

**Issue by steglicd** [freedombox/Plinth#156]
When adding a new Network connection there should be a selectbox with a list of linux devices where the network connection should be based on.

If Type is "Ethernet", the selectbox should only contain wired ethernet devices (i.e. eth0, eth1). If The Type is Wi-Fi, the selectbox should only contain Wi-Fi Interfaces (like ath0 or wlan0)

**Comment by steglicd** [comment]
Im just working on a solution like this.

![network-form-filled](https://cloud.githubusercontent.com/assets/7570118/8747111/3445a452-2c90-11e5-8abc-3f33474ac12e.png)
![network-form-default](https://cloud.githubusercontent.com/assets/7570118/8747113/36ce23fc-2c90-11e5-9eac-f683f8b946b3.png)

**Comment by steglicd** [comment]
I would like to check if a interface is used by a different connection and reject this configuration if this is the case. But when editing a connection, this always will be the case (and so editing form will always be invalid). For this reason I would like to disable the interface field on editing. If one would like to change the interface, he needs to delete the connection and create a new one.

![edit-form](https://cloud.githubusercontent.com/assets/7570118/8853372/907ac134-315a-11e5-91bd-5ddd0dadff07.png)

@SunilMohanAdapa @jvalleroy 
Any thoughts about this?

**Comment by SunilMohanAdapa** [comment]
On 07/23/2015 08:20 PM, Daniel Steglich wrote:
> I would like to check if a interface is used by a different connection
> and reject this configuration if this is the case. But when editing a
> connection, this always will be the case (and so editing form will
> always be invalid). For this reason I would like to disable the
> interface field on editing. If one would like to change the interface,
> he needs to delete the connection and create a new one.

This does not sound like a serious restriction.  It is okay to make the
interface disabled during editing.  We can relax this if required later.

However, I have two thoughts:

- Do we need to make sure that two connections are not created for the
same interface?  What happens when we are connecting to Wi-Fi access
points in regular mode and not AP mode?  We might have different
hotspots to connect to.  Usually network manager will simply prioritize
one connection over another.  Combine this with showing of current
status of connections that tells the user which of the connections is
active, I think it is not too bad if ignore the check.

- Perhaps we can add a simple check that during editing if initial_value
!= current_value then perform the check.

-- 
Sunil

**Comment by steglicd** [comment]
You are right, I did not had the wireless connections in mind but the wired connections. But even on a wired connection I may have multiple saved connections. And when I change my location I may want to activate a different connection.

The situation I want to avoid is that someone adds two IP addressing services on one ethernet device.

Because this may result in very difficult configuration requirements and the user will mess up his network config by accident.

I would suggest this:
* you can have as much wifi (client) connections on one device as you want (all enabled, to switch between wifi networks)
* you can have as much wifi (AP) connections on one device as you want. But when adding a wifi AP connection on a device, all other connections on this device wil be disabled (you only can have one active AP on a device)
* you can have multiple (wired) ethernet connections  but when adding connection on a device, all other connections on this device wil be disabled

Also if you enable a AP or a wired connection on the overview page, all other connections will be disabled if they are on the same device as the enabled connection.

This is mostly like the ubuntu networkmanager GUI does.

**Comment by SunilMohanAdapa** [comment]
On 07/23/2015 09:41 PM, Daniel Steglich wrote:
> You are right, I did not had the wireless connections in mind but the
> wired connections. But even on a wired connection I may have multiple
> saved connections. And when I change my location I may want to activate
> a different connection.
> 
> The situation I want to avoid is that someone adds two IP addressing
> services on one ethernet device.
> 
> Because this may result in very difficult configuration requirements and
> the user will mess up his network config by accident.
> 
> I would suggest this:
> 
>   * you can have as much wifi (client) connections on one device as you
>     want (all enabled, to switch between wifi networks)
>   * you can have as much wifi (AP) connections on one device as you
>     want. But when adding a wifi AP connection on a device, all other
>     connections on this device wil be disabled (you only can have one
>     active AP on a device)
>   * you can have multiple (wired) ethernet connections but when adding
>     connection on a device, all other connections on this device wil be
>     disabled
> 
> Also if you enable a AP or a wired connection on the overview page, all
> other connections will be disabled if they are on the same device as the
> enabled connection.
> 
> This is mostly like the ubuntu networkmanager GUI does.

I believe that Network Manager backend provides us with this
functionality already.  Ubuntu NM UI, as far as I can tell, just relies
on NM and we can do the same.  As soon as we try to active a connection
that conflicts with another connection, the other connection is
de-activated.  What you propose and expect, NM does.  Isn't NM beautiful? :)

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
I believe this issue is now done with the merging of #165.  Please re-open or create a new issue if there is any further discussion.
