### ISSUE TITLE
Don't pass passwords on command line

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#166]
Currently we are passing password on command line to various actions.  Recently we started passing them via STDIN instead of command line, example LDAP action.  There are some more actions to which we need to implement this. These are:

- Transmission
- Pagekite
- DynamicDNS
- Ikiwiki

**Comment by bharathCh** [comment]
Please assign this on my name.

**Comment by bharathCh** [comment]
do you want to commit these as bulk or individual?

**Comment by SunilMohanAdapa** [comment]
One commit per module would be good.

**Comment by stalexan** [comment]
I'm just seeing now that someone else is working on this so don't know if this is needed, but I just created a pull request that fixes this: 
https://github.com/freedombox/Plinth/pull/191

**Comment by SunilMohanAdapa** [comment]
The duplicated effort is quite unfortunate.  Thankfully this is a small patch.  Since there was no update/submission from original author and considering that this is @stalexan's first contribution, I merged @stalexan's patch.  Also @bharathCh is a close friend and he will surely forgive me :)

@stalexan, a warm welcome to the FreedomBox project! Hope to see many more contributions!

**Comment by stalexan** [comment]
My apologies for the confusion. I'm signed up for github notifications now, and will be paying more attention to issue discussions.

**Comment by bharathCh** [comment]
@SunilMohanAdapa Sean emailed if it was ok if he does pull request and i was ok with that. 

no apologies required. @stalexan welcome....
