### ISSUE TITLE
Update Apache auth config directives

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#171]
Both plinth.conf and jwchat-plinth.conf use auth config directives like "Allow". These are deprecated in Apache 2.4 and should be replaced with "Require" directives. See:
https://lintian.debian.org/tags/apache2-deprecated-auth-config.html
http://httpd.apache.org/docs/2.4/upgrading.html

**Comment by SunilMohanAdapa** [comment]
Pull request #238 fixed this. Please do a second review.
