### ISSUE TITLE
Generated TODO includes unwanted line

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#172]
After running ```sudo ./setup.py install```, a TODO file in generated but includes this extra line:
```Binary file ../plinth/modules/pagekite/__pycache__/utils.cpython-34.pyc matches```

This leads to a lintian warning when building the Debian package, because the plinth manpage will include TODO:
```W: plinth: manpage-has-errors-from-man usr/share/man/man1/plinth.1.gz 279: a special character is not allowed in a name```

**Comment by SunilMohanAdapa** [comment]
#232 fixes this issue.  Manual is downloaded from Wiki and is no longer generated from README.md.

**Comment by SunilMohanAdapa** [comment]
Sorry, I meant: TODOs are no longer auto-generated and remove.  That fixes the issue.

**Comment by SunilMohanAdapa** [comment]
#232 is merged.  I believe there are no more TODO items from this bug. Please reopen if you believe there are more fixes to be made as part of the bug.
