### ISSUE TITLE
Deluge is not enabled after install

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#174]
When we click on Deluge menu item, it asks for installation.  After installation, it should be automatically installed, however, it is shows as disabled.  User is having to manually enable it.

**Comment by bharathCh** [comment]
@SunilMohanAdapa It seems deluge is not enabled by default after install. The status shows {'is_running': False, 'enabled': True}. After installation, deluge-web service is not enabled.

It is enabled through the following commands

sudo systemctl enable deluge-web
sudo systemctl start deluge-web 

I ran the commands manually on the shell and was able to see the deluge-web service running in plinth.

I think a generic solution is to pass a callback that executes in package.Transaction class (this class handles the package installation) for post install. This helps in not touching the transaction class again but is extensible as we add other services.

Please suggest.

**Comment by SunilMohanAdapa** [comment]
On 09/02/2015 09:29 PM, Bharath Chava wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa> It seems deluge is
> not enabled by default after install. The status shows {'is_running':
> False, 'enabled': True}. After installation, deluge-web service is not
> enabled.
> 
> It is enabled through the following commands
> 
> sudo systemctl enable deluge-web
> sudo systemctl start deluge-web
> 
> I ran the commands manually on the shell and was able to see the
> deluge-web service running in plinth.
> 
> I think a generic solution is to pass a callback that executes in
> package.Transaction class (this class handles the package installation)
> for post install. This helps in not touching the transaction class again
> but is extensible as we add other services.
> 
> Please suggest.

post install trigger already exists.  See Transmission module as
reference for how it enables the module after install.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
#213 fixes this bug.
