### ISSUE TITLE
Move diagnostics from freedombox-setup into appropriate Plinth modules

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#178]
Now that we have a framework for diagnostics in each module (https://github.com/freedombox/Plinth/pull/170), some of the checks in http://anonscm.debian.org/cgit/freedombox/freedombox-setup.git/tree/testsuite can be moved into Plinth modules, as appropriate.

**Comment by SunilMohanAdapa** [comment]
This is now completed with merge of diagnostics related patches.
