### ISSUE TITLE
PageKite: abort_not_configured line not removed

### ISSUE THREAD

**Issue by peacekeeper** [freedombox/Plinth#179]
If I enter **markus.freedombox.me** as "Server", and also **markus.freedombox.me** as "Kite name", then the **abort_not_configured** line in **/etc/pagekite.d/10_accounts.rc** doesn't get removed.

With this line in the configuration, PageKite won't start.

**Comment by SunilMohanAdapa** [comment]
This is fixed with merge of #244.
