### ISSUE TITLE
PageKite: need port in "frontend" setting

### ISSUE THREAD

**Issue by peacekeeper** [freedombox/Plinth#180]
If I enter **markus.freedombox.me** as "Server", then in **/etc/pagekite.d/20_frontends.rc**, Plinth writes the following:
> frontend=markus.freedombox.me

But it should actually write:
> frontend=markus.freedombox.me:80

If the port is missing, PageKite doesn't work at all.
Of course I can put the full server AND port into the Plinth "Server" field.
But this is not obvious, so I think Plinth should add the port **:80** if it's missing.

**Comment by NickDaly** [comment]
Should we add a separate port field that defaults to 80?

**Comment by peacekeeper** [comment]
Ya I think that's also a good solution.

**Comment by SunilMohanAdapa** [comment]
This is now fixed with #244.
