### ISSUE TITLE
Error while refreshing package list during install

### ISSUE THREAD

**Issue by chaitanyamuppala** [freedombox/Plinth#183]
Error says:

"Error installing packages: W: Failed to fetch http://http.debian.net/debian/dists/sid/main/binary-armel/PackagesIndex Hash Sum mismatch E: Some index files failed to download. They have been ignored, or old ones used instead. "
![selection_053](https://cloud.githubusercontent.com/assets/8538527/9287564/44e35f7e-4339-11e5-97a2-8fae79efaa94.png)

**Comment by SunilMohanAdapa** [comment]
This seems to another consequence of a similar bug in PackageKit.  https://bugs.freedesktop.org/show_bug.cgi?id=91609

To generalize the issue seems to be that if any warning comes up during refresh-cache operation, then it is treated as an Error.

**Comment by SunilMohanAdapa** [comment]
To work around the problem, you can run 'apt-get update' on the console, identify which package list is causing the problem and remove it from /var/lib/apt/ directory.  Or simply remove all the package lists from /var/lib/apt/ directory.

**Comment by SunilMohanAdapa** [comment]
@chaitanyamuppala Does the work around fix the problem for you?

**Comment by jvalleroy** [comment]
Fixed in #493.
