### ISSUE TITLE
Improvements to first boot

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#188]
We should improve the first boot experience. I suggest a new design on the following lines.  Perhaps we should also have another page entirely for taking and setting the wifi password.
![1](https://cloud.githubusercontent.com/assets/1535496/9288862/902e4a94-4379-11e5-80eb-a68c10dcd367.png)
![2](https://cloud.githubusercontent.com/assets/1535496/9288863/94a47364-4379-11e5-874f-9100cd642369.png)
![3](https://cloud.githubusercontent.com/assets/1535496/9288864/974344e2-4379-11e5-8a8a-7733782a527b.png)

**Comment by SunilMohanAdapa** [comment]
Changing the hostname during firstboot is not important.

**Comment by SunilMohanAdapa** [comment]
I believe it is import to also have an App selection screen that installs all the selected applications.

**Comment by SunilMohanAdapa** [comment]
I am working on this and completed the first two steps.

**Comment by fonfon** [comment]
I tried it out but did not yet have a look at the code.
Setting the box up and basic functionality (wrong password handling etc.) works; Just two tiny things/thoughts:

1) For me it was strange to see the 'Congratulations' title at the start of first-boot, I'd expect this when everything is set up correctly
2) At the state10 page: 
Right now they Go to Networks' / 'Go to Apps' buttons are aligned in a way that lets me think they'd belong to the 'External' and 'Internal' network connections:
![image](https://cloud.githubusercontent.com/assets/1867309/10637061/9e9a2f8a-7803-11e5-8fca-420abd6e97a8.png)
Perhaps we could move the buttons into the text as normal links or align them differently (e.g. put them above the diagram).

**Comment by fonfon** [comment]
closed with #352
