### ISSUE TITLE
Show current status of a network connection

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#189]
Show information such as IPv4/IPv6 addresses, DNS, default gateway, type of connection etc.

**Comment by steglicd** [comment]
The topic is related to https://github.com/freedombox/Plinth/issues/155
I can have a look at this while working on issue 155

**Comment by SunilMohanAdapa** [comment]
On 08/18/2015 02:52 PM, Daniel Steglich wrote:
> The topic is related to #155
> <https://github.com/freedombox/Plinth/issues/155>
> I can have a look at this while working on issue 155

Please go ahead.

**Comment by steglicd** [comment]
@SunilMohanAdapa 
I would like to add a new tab to Network Menu. I would name it "Status" and would place the following information on this page:

* Interface Name
* MAC Address
* Default gateway [yes|no] (yes: if NOT a shared connection) - Maybe we name it "Upstream Interface"?
* IP address (v4/v6)
* Netmask

if not default Gateway (shared connection):
* DHCP Range

if it is a default Gatewa Interface:
* Default Gateway (or if PPP Interface: "peer address")
* DNS Server

if it is a Wifi interface:
* SSID
* Encryption Method (display WARNING if unencrypted)
* Link Speed / Link Quality

I also would like to place a Warning message if more than one interface is configured and is not "shared". Because in this case we have more than one default gateway and this will randomly may work or not.

**Comment by jvalleroy** [comment]
@steglicd Just an idea: Currently when you click the connection name under Network Connections, it takes you to the Edit page. Maybe clicking the connection name could go to the Status page instead (which would have a link to Edit that connection). I think viewing the status would be more common than editing.

**Comment by steglicd** [comment]
@jvalleroy 

sometimes when one is thinking to long about something, the most obvious solution will not come in mind :)

sounds good. I will edit my proposal.

**Comment by SunilMohanAdapa** [comment]
On 09/10/2015 12:09 AM, Daniel Steglich wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa>
> I would like to add a new tab to Network Menu. I would name it "Status"
> and would place the following information on this page:
> 
>   * Interface Name
>   * MAC Address
>   * Default gateway yes|no - Maybe we name it "Upstream Interface"?
>   * IP address (v4/v6)
>   * Netmask
> 
> if not default Gateway (shared connection):
> 
>   * DHCP Range
> 
> if it is a default Gatewa Interface:
> 
>   * Default Gateway (or if PPP Interface: "peer address")
>   * DNS Server
> 
> if it is a Wifi interface:
> 
>   * SSID
>   * Encryption Method (display WARNING if unencrypted)
>   * Link Speed / Link Quality
> 
> I also would like to place a Warning message if more than one interface
> is configured and is not "shared". Because in this case we have more
> than one default gateway and this will randomly may work or not.

The proposal is nice (along with the update).

To answer the questions, here is what I think.  This page is useful for
support activities, advanced users and expert debugging but is not
really understood by a typical user.  From this point of view, perhaps
we can keep labels such as 'Default gateway' as it is and not introduce
new terms like 'Upstream interface' that might require learning even for
advanced users.  We can follow Network Manager's terminology and GNOME's
user experience where applicable.

-- 
Sunil

**Comment by steglicd** [comment]
I make some progress here, still working on it. Sorry for the delay.
If you click on a connection on the overview page, you will be directed to a status page like this:
![show](https://cloud.githubusercontent.com/assets/7570118/9863435/2a2440bc-5b40-11e5-860e-f073bd1db99a.png)
Edit button will lead you to the edit form:
![edit](https://cloud.githubusercontent.com/assets/7570118/9863436/2a3b37ae-5b40-11e5-95dd-fda7c6db47ad.png)

Still have some work to do, page style is not complete yet and even information are missing. 

@SunilMohanAdapa I added a helper function to get ip from device without crashing when there is no ip assigned or the ip configured via DHCP.
The configure form hase some ToDo tag here:
```python
# XXX: Plinth crashes here. Possibly because a double free bug
# address = settings_ipv4.get_address(0)
# form_data['ipv4_address'] = address.get_address()
```
maybe the helper function will be useful here, like this:
```python
name = connection.get_id()
form_data['ipv4_address'] = network.get_ip_from_device(name)
```
`network.get_ip_from_device` will return the first ip from the device or "0.0.0.0" if there is none assigned.

**Comment by SunilMohanAdapa** [comment]
@steglicd , I believe we have most of the information shown as part of your pull request #230.  I am closing this now.  If there is more information that can be shown we can create another issue and track it there.  If there is more work pending here, please feel free to reopen the bug.
