### ISSUE TITLE
Bootstrap javascript does not work

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#198]
As discussed #173 and [#786429: libjs-bootstrap requires newer (non-packaged) version of jquery](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786429), Boostrap Javascript is not working for Plinth.  The following are known to be affected:
- Logout button is not visible.
- Network connection activate/deactivate does not work.

**Comment by SunilMohanAdapa** [comment]
Newer version of Jquery as required by Boostrap is now available in Debian.  Upgrading libjs-jquery fixed the problem for me.

**Comment by stalexan** [comment]
It might be nice to have a boolean config setting (internal and not surfaced to the user) in Plinth that is by default off but can be turned on to disable Javascript, for when/if this happens again. It could be checked anywhere we do other checks to generate HTML that doesn't use Javascript; e.g. for https://github.com/freedombox/Plinth/issues/173.
