### ISSUE TITLE
Plinth Redirects Forever Behind PageKite

### ISSUE THREAD

**Issue by NickDaly** [freedombox/Plinth#200]
After activating PageKite on Plinth 0.5 and trying to navigate to Plinth via PageKite, the Plinth service repeatedly redirects to itself and doesn't successfully load.

You can see a demonstration of this redirect loop by connecting to https://betweennowhere.pagekite.me/plinth or by taking a look at the header log (via LiveHttpHeaders):

https://gist.github.com/NickDaly/ad68db0aee70c9b2afe1

**Comment by SunilMohanAdapa** [comment]
Could you please try disabling 'http' service (and keep 'https') in Pagekite configuration of Plinth?

**Comment by NickDaly** [comment]
Sunil, I'm not sure whether it should even support Pagekite at all: infinite redirection is bad, but Plinth's Apache configuration (plinth.conf) specifically disallows any non-local-network connections (this is missing in plinth-ssl.conf).

Should we allow users to get to Plinth over pagekite?  If so, that's a different fix (and philosophy) than just preventing redirects.

**Comment by NickDaly** [comment]
Closing, that appears to be an issue on Plinth 0.4 and is resolved: plinth is now accessible via PageKite in Plinth 0.5.

**Comment by SunilMohanAdapa** [comment]
On 08/31/2015 01:31 AM, Nick Daly wrote:
> Sunil, I'm not sure whether it should even support Pagekite at all:
> infinite redirection is bad, but Plinth's Apache configuration
> (plinth.conf) specifically disallows any non-local-network connections
> (this is missing in plinth-ssl.conf).
> 
> Should we allow users to get to Plinth over pagekite? If so, that's a
> different fix (and philosophy) than just preventing redirects.

We need a portal that sends the users to all the available services on
FreedomBox.  This portal should be available to all the users on the
Internet as I would like to expose my blog, wiki, social network etc. to
the outside world.  Plinth is in the best place to generate this portal
as it has information about the currently enabled services and their
URLs (or information on how to use that services).  Plinth is getting
ready to have this 'dashboard' or 'front page'.

We do need to protect our administrative functions, I wonder what we can
do in light of this.

-- 
Sunil

**Comment by jvalleroy** [comment]
Just some ideas:
- We could add some protection against brute force attacks to the Django login.
- Plinth could generate the list of public services, but publish it as a (static?) site that's served separately from Plinth.
