### ISSUE TITLE
Allow Users to Shutdown or Restart FBX from Plinth

### ISSUE THREAD

**Issue by NickDaly** [freedombox/Plinth#202]
To properly turn off a FBX, users must currently SSH into the box and run shutdown commands (`sudo shutdown -h 0`).  Users should never need to SSH into the box to do anything, especially not routine maintenance tasks.

We should add Shutdown and Restart actions to Plinth so users can shutdown or restart the box without needing to log in.

**Comment by SunilMohanAdapa** [comment]
This is fixed by @joelvalleroy with #306 .
