### ISSUE TITLE
Update Package Lists on First Boot so Users can Easily Install Packages

### ISSUE THREAD

**Issue by NickDaly** [freedombox/Plinth#203]
Packages can't successfully be installed until the package list is updated.  Currently, users must do this in Plinth manually, by running "Unattended Upgrades."  This makes installing and activating your first service a two-step process, where you can't activate a service until the upgrade process is complete.

This may also be resolved by fixing #77.

**Comment by NickDaly** [comment]
I may have been wrong, still receiving the package install error after running UA.  Closing bug pending further investigation.

**Comment by SunilMohanAdapa** [comment]
To provide further information:

- Package list is refreshed every time before a new package is installed.

- We have a known issue with package refresh mechanism of PackageKit's aptcc backend: see #183.
