### ISSUE TITLE
Firewall Status Page Should Use non-Red/Green Color Scheme

### ISSUE THREAD

**Issue by NickDaly** [freedombox/Plinth#204]
Page: https://freedombox/plinth/sys/firewall/

To support Red/Green color-blind users, we should use a different color scheme: a small number of users (1 - 3%, depending on source) have the most common type of color blindness and can't differentiate red and green.  It's difficult to [differentiate the statuses if you can't see the colors](https://imgur.com/a/VX8nc).

We should resolve this by switching color pallets (blue / yellow, blue / white+black, etc.) or adding additional non-color indicators, like **bold** or _italic_ formatting to different statuses.

**Comment by nikhilrayaprolu** [comment]
Hello if so we would be changing the colours of the badges in firewall page,what would be correct combination to go with?
red is standard for blocked
green for enabled
yellow for disabled are actually standard notations followed
 .can any one suggest colours that are appropriate if we change these?

**Comment by NickDaly** [comment]
There are a number of ways to correct this:

1. Never use color as the only indicator, use other styling as well.
2. Going by the Wikipedia page on [colorblindness](https://en.wikipedia.org/wiki/Color_blindness), I can see that red, yellow, and green all [collapse into yellow](https://en.wikipedia.org/wiki/File:Braeburn_GrannySmith_dichromat_sim.jpg), so only one of those colors should be used.

Keeping these in mind, I suggest the following two guidelines:

1. Use Yellow, Blue, and Gray.  Those colors are relatively distinguishable and used widely: yellow for blocked, blue for enabled, and gray for disabled.  Disabled-gray is a standard, as is replacing blue for green, when green's unavailable.

2. Use normal, _italicized_, and **bolded** (and **_bold-italics_**).  These are not as standard, but as long as they're used consistently and clearly, tying in with the colors, their purpose will be obvious.

**Comment by SunilMohanAdapa** [comment]
[Most](http://webaim.org/articles/visual/colorblind) [resources](http://wearecolorblind.com/examples) [on](https://designshack.net/articles/accessibility/tips-for-designing-for-colorblind-users/) the matter don't actually suggest changing the colors to help people with color blindness.  They suggest that using these colors should not normally be a problem but when color is used to provide important information, then cues other than just color should be provided.  We are clearly providing additional cue with the text.  If a color blind person sees our firewall page, they will still know which is items are enabled, disabled, blocked etc. due the text.  This is sufficient for conforming to WCAG 2.0.  Using colors other than red/green mean that function of the color, such as attracting attention to problematic items, is diminished.  This is why most accessibility compliant websites that want to attract attention to problems such as form errors don't remove red as the color but instead using other cues as well.

[WCAG 2.0](https://www.w3.org/TR/WCAG20/) suggests a minimum [contrast](http://webaim.org/resources/contrastchecker/) for the foreground color to background color.  Twitter's bootstrap [meets](https://www.sitepoint.com/making-bootstrap-accessible/) the WCAG 2.0 criteria for contrast for regular text and text on menu items.  However, it does not seem to meet the criteria for test that is labels like the ones we used.  One area of work for us could be to change that.

**Comment by SunilMohanAdapa** [comment]
@NickDaly , any thoughts? Can we close this issue?

**Comment by NickDaly** [comment]
Hi Sunil, thanks for pinging me on this, I'd missed pull #519.  I'm installing Plinth on my XU4 now and will try pull 519 out on the system later today.  After an initial review of the patch, it seems like enabled services are _italicized_, but other types of services and ports are not styled differently than neutral text.

I'll let you know after I try it out, I don't recall this thread well enough to remember if that's enough distinct styles.  I thought we needed three indicators, not two.

**Comment by SunilMohanAdapa** [comment]
On 09/05/2016 11:49 PM, Nick Daly wrote:
> After an initial review of the patch, it seems like enabled services
> are /italicized/, but other types of services and ports are not
> styled differently than neutral text.

Well, after all that reading, I believe no styling is actually required
for any of the elements because text label is available.  Other cues are
only required only if color is being used to convey the necessary
information.

> 
> I'll let you know after I try it out, I don't recall this thread
> well enough to remember if that's enough distinct styles. I thought
> we needed three indicators, not two.

Sure, please let us know what you think.

-- 
Sunil

**Comment by NickDaly** [comment]
Pull #519 works nicely!  It differentiates between the three statuses pretty well.  Bolding blocked entries would be perfect, but it's definitely good enough right now.

Apologies for the delay on this issue.

**Comment by SunilMohanAdapa** [comment]
Well, we need to reach an agreement on the differentiation required. Since we have the text and since we not using colour as the only cue, our current implementation is fine. I am closing this issue.  But please feel free to reopen to add more to the discussion.
