### ISSUE TITLE
After changing domain name, old name is shown

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#208]
The effect is applied as expected in /etc/hosts file.  However, socket.getfqdn() continues to return a cached older value in Plinth as well as other applications even after an application restart.  Find a better way to (store/)retrieve the domain name.

**Comment by jvalleroy** [comment]
This is fixed in the daily image. We can still look for an alternative to using /etc/hosts though (#434 to track that).
