### ISSUE TITLE
Update Plinth docs

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#211]
doc/faq.mdwn and doc/scripts.mdwn seem particularly out of date.

**Comment by bharathCh** [comment]
Any pointers on what needs to be updated?

**Comment by jvalleroy** [comment]
Here's a quick list I put together:
* colophon.mdwn - Change "Freedom Box front end" to "Plinth"
* design.mdwn - I don't think freedombox.lan works anymore, but freedombox.local should work via mDNS.
* faq.mdwn - I think we can probably delete this file.
* scripts.mdwn - Rename to "actions", and basically replace "scripts" with "actions" everywhere.
  * "Do only one thing" - Most of the actions support multiple commands.
  * "Require no interaction beyond..."
    * Another supported form of interaction: Plinth can send data over stdin to the action.
  * Change "Freedom Plug" to "FreedomBox"
* themes.mdwn
  * "Themes are stored in /themes." - Currently in /static/themes.
  * "The default or active theme is linked from..."
    * /static/default moved to /static/theme
    * I can't find templates/default, maybe it's not used anymore?
  * "Templates are stored in /templates." - Currently in /plinth/templates.

**Comment by jvalleroy** [comment]
Actually, we have a new developer manual now! :) (Thanks Sunil!)
https://wiki.debian.org/FreedomBox/Manual/Developer

I think we can just check that the information in the doc files is covered in that wiki page. Then the old docs here can be deleted, and maybe "make doc" should fetch the developer manual from the wiki.

**Comment by SunilMohanAdapa** [comment]
I am working on this issue.

**Comment by SunilMohanAdapa** [comment]
#232 fixes this issue.

**Comment by SunilMohanAdapa** [comment]
#232 is merged.  I believe there are no more TODO items from this bug. Please reopen if you believe there are more fixes to be made as part of the bug.
