### ISSUE TITLE
Merge 'app' and 'system' modules into Plinth core

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#220]
For the tiny little functionality they provide, they have to be added as dependency for every module that we write.  Can't image a reason why we would want to disable them.  It is not worth having them as modules. Merge them into core and remove dependency on them from every module.

**Comment by 500swapnil** [comment]
@jvalleroy I would like to work on this one. How do I proceed?

**Comment by jvalleroy** [comment]
@500swapnil Here's a list of tasks to get started:
* Move templates from the "apps" and "system" modules into plinth/templates.
* Move routes from apps and system modules into plinth/urls.py.
* Move views from apps and system modules into plinth/views.py.
* Rename things as needed so they don't conflict with existing items.
* Basic testing to check that nothing is broken.

**Comment by 500swapnil** [comment]
@jvalleroy I opened a PR #705 . Please have a look!

**Comment by sahithi-ihtihas** [comment]
@jvalleroy Done the changes and created a pull request

**Comment by jvalleroy** [comment]
Fixed in #705 and #792.
