### ISSUE TITLE
Consider setting the default firewall zone as "internal" or "external"

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#229]
Currently, when a network interface is automatically configured by Network Manager, the interface belongs to `public` firewall zone.  However, we only configure our firewall for `internal` and `external` zone. As a result, new only added interfaces do not provide any services including basic web interface access.  Consider changing the default zone attached to any interface to be `internal` or `external` (perhaps `external` is better for security reasons).  There is also another proposal #228 to automatically configure a network interface with help a udev trigger.  This will make this problem less severe or unnecessary.

**Comment by SunilMohanAdapa** [comment]
Firewall now has all unknown interfaces treated as 'external' (safer) interfaces.  This is done by setting default zone as 'external' in firewalld.  This should be available in 0.7+.  This bug can be closed after testing that everything works as expected.

**Comment by jvalleroy** [comment]
As far as I know, it is working as expected. Please reopen if needed.
