### ISSUE TITLE
Diagnostics errors due to modules not setup yet

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#248]
Running diagnostics before module setup, causes some errors:
1. Before Tor is installed, running all diagnostics results in a FileNotFoundError for /var/lib/tor/state.
2. After Tor is installed, running all diagnostics shows a number of failures for other modules where the required packages are not installed yet.

I think we can skip diagnostics for modules that have not been setup, and show "skipped" as the result.

**Comment by SunilMohanAdapa** [comment]
When the setup framework is available, we will be able to track which modules have been setup and which ones need installation/upgrading.  To fix this properly we should wait until the setup process arrives.
