### ISSUE TITLE
Remove the hack for getting IP address of a connection

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#251]
During editing a connection to show the currently set IP address of a connection, we are using an ugly hack due to a bug https://bugzilla.gnome.org/show_bug.cgi?id=756380.  The bug is fixed upstream and for release of network-manager >= 1.0.7 we should remove the hack.

**Comment by nikhilrayaprolu** [comment]
https://github.com/freedombox/Plinth/blob/master/plinth/network.py#L135

where from the 'address' variable came here. I could see 'addresses' being initialised and assigned above this line,but could not find where 'address' is initialised

**Comment by nikhilrayaprolu** [comment]
Does this mean we have to update the version of nm package to some version >1.0.7

**Comment by jvalleroy** [comment]
@nikhilrayaprolu Debian testing and unstable have network-manager 1.2.2 (https://packages.qa.debian.org/n/network-manager.html).

But Plinth still has an "ugly hack" workaround, that was needed for the older network-manager:
https://github.com/freedombox/Plinth/blob/master/plinth/network.py#L203

So we want to replace that now, with something less hack-y.

**Comment by jvalleroy** [comment]
Fixed in #526 and #542.
