### ISSUE TITLE
Refactor XMPP module

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#254]
Plinth can potentially support multiple XMPP servers and multiple XMPP web clients. To encourage this, I suggest the following changes:
1. Split xmpp module into 2 modules: Chat Server (Ejabberd) and Chat Client (JWChat).
2. Name / URL of each new module should match the package's name.

**Comment by SunilMohanAdapa** [comment]
In this particular case, I agree that splitting modules is fine.  When we have bigger functionality such as email, we cannot expect the user to enable mail server, anti-spam, anti-virus, IMAP server etc. separately and may have to add that into a single module. Web client for that though may be a separated like we are considering with `jwchat`.

**Comment by 500swapnil** [comment]
I would like to work on this one. How do I proceed?

**Comment by SunilMohanAdapa** [comment]
@500swapnil , the following could be done:
* Remove xmpp module.
* Add new module called `jsxc` (with code from xmpp module). This module should only deal with JSXC and nothing with ejabberd.
* Add new module called `ejabberd` (with code from xmpp module). This modules should only deal with ejabberd setup and nothing with JSXC.

**Comment by 500swapnil** [comment]
I have opened a PR #697 . Please have a look!

**Comment by jvalleroy** [comment]
Fixed in #697.
