### ISSUE TITLE
Config Tests use System Config instead of Test Config

### ISSUE THREAD

**Issue by NickDaly** [freedombox/Plinth#260]
When running `nosetests` to test the system, the `plinth/tests/test_cfg.py` tests use the system-wide config file (`/etc/plinth/config`) instead of the test config file (in `plinth/tests/data`).  This leads to inaccurate testing.

This issue is easy to reproduce when running Plinth 0.6 tests when Plinth 0.5 is installed on the system, and will prevent the package from building (therefore, it's impossible to build the Plinth 0.6 package when Plinth < 0.6 is installed on the system).

**Comment by SunilMohanAdapa** [comment]
I have revamped the cfg tests and they should work predictably and not causes issues during build #328 .  Please re-open if you think the problem is not fixed.
