### ISSUE TITLE
Setting domain name does not reflect

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#262]
Perhaps due to recent changes in the way we are dealing with /etc/hosts, setting a domain name does not reflect.  XMPP server reflects the new domain name but /etc/hosts does not show the new domainname.  This leads to showing empty value in domainname field and also in description of XMPP while showing the example addresses.

**Comment by jvalleroy** [comment]
It looks like there are 2 cases where setting the domain name doesn't reflect (in Plinth or in `hostname --fqdn`):
- hostname is set to 'localhost'
- hostname is set to 'freedombox'

Those 2 names are in the top line of /etc/hosts:
```
jvalleroy@freedombox:~$ cat /etc/hosts
127.0.0.1	localhost freedombox
127.0.1.1       freedombox.compcube.info freedombox
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
```
After I removed 'freedombox' from the 1st line and rebooted, the domain name was displayed correctly.

**Comment by jvalleroy** [comment]
It looks like vmdebootstrap adds the hostname to the 127.0.0.1 line. I think we will need to skip or undo this step. I found this reference: https://unix.stackexchange.com/questions/11844/etc-hosts-for-debian

**Comment by jvalleroy** [comment]
The domainname field displays correctly now, but XMPP page does not. I opened #470 to track the remaining issue.
