### ISSUE TITLE
Remove first line Plinth README

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#263]
It reads "Plinth User Manual".  It was placed there when we were generating manual from all these files.  However, that is not true anymore. We don't need this line.

Also add URLs to actual user manual on the wiki from Plinth README.

**Comment by Web-Dev-Rich** [comment]
As a beginner I would like to have a go a this. Should be done today.

**Comment by Web-Dev-Rich** [comment]
PR submitted :)
