### ISSUE TITLE
Mumble not starting

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#264]
It appears that in a recent release of `mumble-server`, they have removed the init script.  It makes the Mumble server not start anymore.  I am perplexed as to why someone would to this http://metadata.ftp-master.debian.org/changelogs//main/m/mumble/mumble_1.2.10-1_changelog

We need to provide an init script or systemd unit for mumble-server or convince the maintainer to add it back.

**Comment by bhuvankrishna** [comment]
The bug has been identified and I think it is getting fixed.
http://bugs.debian.org/802390

**Comment by SunilMohanAdapa** [comment]
Note that if a fixed package is uploaded, we don't have do anything from FreedomBox side as we don't package Mumble in our images but just install it at the time of usage.

**Comment by SunilMohanAdapa** [comment]
The Debian package is fixed and the fixed package is available in both testing and unstable.
