### ISSUE TITLE
Improve 'organizing' apps and services

### ISSUE THREAD

**Issue by fonfon** [freedombox/Plinth#267]
With the increased amount of services and applications that are fortunately available for FreedomBox, our current approach of handling apps -- to just display a list of all available apps -- will become less and less convenient.

The dashboard (see outdated proposal #20 ) should help to only display the installed apps, but we (hopefully) will also need something to easier group and search the available apps/services. I'm thinking about something like a "Software Center" or "App Store" (although I wouldn't call it 'Store'). Or just a possibility to group the existing apps into different categories.

We could add this search functionality to the main `Apps` landing page (`/plinth/apps/`).

Right now this is not really necessary, but we should keep it in mind or prepare first steps towards this direction.

**Comment by phylophyl** [comment]
apps categorization or filter for the app list on the plinth home page:

First draft
NETWORK, DATA SYNC/SHARING, IM. VOICE, CONTENT PUBLICATIONS, EMAIL, GAME
data category needs a split to be more accurate (data sync, data sharing, links reader)
shorter term for content publication

| Apps     | Network | Data | IM | Voice | Publication | E-Mail   | Game |
| :------- | ----: |  ----: | ----: | ----: | ----: | ----: | ---: | ---: |
| Tor | X |     |  |  |  |  |  |  |
| Deluge    |    |  X   |  |  |  |  |  |  |
| Transmission     |     |  X  |  |  |  |  |  |  |
| Minetest     |     |    |  |  |  |  |   X   |
| Shaarli     |     |   X    |  |  |  |  |  |  |
| Radicale     |     |   X    |  |  |  |  |  |  |
| XMPP     |     |    |   X   |  |  |  |  |  |
| Dynamic DNS     |     |    |  |  |  |  |  |  |
| Roundcube     |     |    |  |  |  |   X   |     | 
| ownCloud     |     |    X    |  |  |  |  |  |  |
| Quassel     |     |    |   X |  |  |  |  |  |
| Tiny Tiny RSS     |     |    |  |  | X |     |  |  |
| PageKite     |     |    |  |  |X  |  |  |  
| repro     |     |    |  | X |  |  |  |  |
| OpenVPN     |   X  |    |  |  |  |  |  |  |
| Mumble     |     |    |  |X  |  |  |  |  |
| Privoxy     |  X   |    |  |  |  |  |  |  |
| ikiwiki     |     |    |  |  | X |  |  |

**Comment by phylophyl** [comment]
GREEN LIGHTS
Adding a green light for active apps in the right plinth list would allow to avoid clicking on each app to know if they are activated or not

**Comment by phylophyl** [comment]
APPS PAGE
definition + link to official app website
adding solid INSTALL and USE how-tos independant pages

**Comment by jvalleroy** [comment]
We might consider organizing apps by "task", rather than by category.

Tasks might be phrased like:
"I want to..."
- Create a blog (ikiwiki, wordpress)
- Start a chat (ejabberd, jsxc, quassel)
- Make a voice call (mumble, repro, ejabberd)
etc. So an app can provide for multiple tasks.

**Comment by mray** [comment]
I'd not use categories if they are not specific enough or if they have have only few members.

I think we have not yet reached a number of apps that make categorization sensible. We either have to use too vague categories or have too few apps per category. Depending on how we integrate categories into the UI it creates unnecessary noise.

I think our audience still *heavily* has to rely on knowing what they are looking for and reading/learning how to achieve what they want. Browsing through categories and choosing like a breeze is part of an ideal solution, unfortunately I think it only adds complexity right now.

**Comment by SunilMohanAdapa** [comment]
I also agree with @mray last comment on categorization adding complexity. Many desktop/mobile user interfaces have moved away from multi-level categorization and settled on search and other improvements.

We are moving towards @mray 's comprehensive card based design. That design does not have groups but specifies a 'short description' in the card separating it from the name. Please comment/improve that design. I believe we should close this issue, please feel free to reopen it for further discussion.
