### ISSUE TITLE
config: Allow hyphens in hostname/domainname

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#275]

**Comment by SunilMohanAdapa** [comment]
Looks good, I have merged this.  Welcome to the FreedomBox project :)

I have made the following changes.  Please check if they are okay.

- Make sure that minimum length is 1.
- Update description.
- Write tests cases.

Currently we are not check the domain name properly.  Would you like take up the task and fix the domainname checking to properly reflect the rules?

**Comment by joelvalleroy** [comment]
Thank you - yes I shall get started on that!
