### ISSUE TITLE
SSH public key login

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#280]
Related to https://github.com/freedombox/freedombox-todos/issues/11, allow the user to upload their public RSA key and add it to the SSH authorized keys, so they can use SSH without a password.

**Comment by preexo** [comment]
+1 for this. Is just the plinth UI missing to add the a pub key to the authorized keys file or is more required to achieve this? 

I have created the ~/.ssh/authorized_keys file containing my public key by hand. But it's not working, seems like it's not being used like on other servers where I did that. So was wondering if that needs more adjustments, the sshd config seems fine for it...

**Comment by steglicd** [comment]
@preexo which users home did you used? So what is the full path of "~/"?

**Comment by preexo** [comment]
using a ssh-rsa key works fine, ssh-dss keys are not being supported by default anymore, sorry for the confusion.

**Comment by SunilMohanAdapa** [comment]
With the merge of #302 , this should be fixed.  There now UI to allow adding SSH keys from Plinth.

**Comment by SunilMohanAdapa** [comment]
The implementation is basic.  But adding multiple keys is possible.  Home directory is created with proper permissions if required.  @preexo do check and comment on it, if possible.
