### ISSUE TITLE
Improve apps/service registration

### ISSUE THREAD

**Issue by fonfon** [freedombox/Plinth#296]
I think we need to add more information when registering a Service, and make the `services.py` more powerful. This proposal partly overlaps with #103.

Main reason for me is that I'd like to know whether a specific service is installed, which is essential for #20, #266, #267. Checking for installed packages on the fly is too slow (0.7s for only ['tor', 'obfsproxy', 'torsocks', 'apt-transport-tor'] on my VM).

I'm thinking of providing the required packages when registering/creating a service:

    service = service_module.Service('tor', required_packages=['tor', ..], ..)

and we'd have to distinguish services that can be uninstalled and 'system-level' services that are essential like plinth/ssh/http/...

I'd add a `service.is_installed` method/attribute that the `Service` class takes care of.
Views can require a service to be installed, instead of specific packages now. The services module can offer a thin installation wrapper to the `packages.py` installation routine (`my_service.install()`).
This could emit pre-install/post-install/pre-uninstall/post-uninstall events that the plinth modules then listen to, opposed to the current decorator `@package.required(before_install=my_method)`. Like this, one module could listen to the installation/uninstallation of another module.

Do you consider `services.py` to be the right place for this functionality?
Another possibility is to introduce some kind of 'application registry'. This would interfere less with the already existing 'system-level' services.

**Comment by SunilMohanAdapa** [comment]
With the setup improvements, there is a clear way to get the state of a module.  `module.setup_helper.get_state()` will return `needs-setup`, `needs-update` or `up-to-date`.  This is done using a special database table to store information about the module setup state.  This is a kind of mini application registry.

Sorry, for a long drawn implementation of my setup proposal.  I believe this requirement is now satisfied although the implement is a bit different.  Please check it out and reopen this if necessary.  More importantly, it opens up possibilities for further work we were planning.
