### ISSUE TITLE
Issue when changing Network Interface from DHCP to manual

### ISSUE THREAD

**Issue by steglicd** [freedombox/Plinth#307]
When changing a connection  "IPv4 Addressing Method" from Manual to DHCP, I get a error Message:

"500

This is an internal error and not something you caused or can fix. Please report the error on the bug tracker so we can fix it."

**Comment by steglicd** [comment]
concrete error message is:
nm-connection-error-quark: ipv4.gateway: gateway cannot be set if there are no addresses configured (7)

line 311 of network.py will remove the manually configured addresses, but the Gateway (set on line 309) will remain.
I did not found the way to remove the gateway property, but I assume this will be the solution.
We also could set up a new SettingIP4Config settings object in case of switching from manual to DHCP (to remove other manual configured fragments - like DNS Server)

**Comment by steglicd** [comment]
Also when switching from DHCP to manual mode, the DHCP obtained IP remains in the system in addition to the manual given IP.

**Comment by SunilMohanAdapa** [comment]
This is fixed by #312
