### ISSUE TITLE
Add dynamic DNS Domain to trusted_domains of owncloud

### ISSUE THREAD

**Issue by steglicd** [freedombox/Plinth#309]
If the FB is reachable via DynamicDNS, owncloud is still not accessible because the trusted_domain is not configured.

**Comment by SunilMohanAdapa** [comment]
On 11/28/2015 06:10 PM, Daniel Steglich wrote:
> If the FB is reachable via DynamicDNS, owncloud is still not accessible
> because the trusted_domain is noct configured.

We could solve it one of the two ways:

1) Disable ownCloud domain specific checks.  I am not sure how useful it
is in a managed environment like this.

2) Use the new names module which has a signal that is fired when a new
domain is added.  Dynamic DNS should fire a signal on new domain
configured.  ownCloud will pick up the signal and add the domain to the
configuration file.

-- 
Sunil

**Comment by fonfon** [comment]
Because of Owncloud being removed from Debian I close this issue.
