### ISSUE TITLE
Dynamic DNS: passing password to action script via stdin is not working

### ISSUE THREAD

**Issue by steglicd** [freedombox/Plinth#310]
The action script of dynamicdns is not working, because the "read -t 0" (statement when passing a string to be used as password) is causing a syntax error.

**Comment by mray** [comment]
Does this mean i'll have to wait for 0.7 release to use dyndns?

**Comment by steglicd** [comment]
@mray 
yes it will not work before 7.0 
But in the meantime you may workaround by using this two commands on freedombox cmdline:

` wget -O /usr/share/plinth/actions/dynamicdns https://raw.githubusercontent.com/steglicd/Plinth/dynamicdns-password-fix/actions/dynamicdns`

`sudo chmod +x /usr/share/plinth/actions/dynamicdns`

**Comment by mray** [comment]
Ok having done that seems to work. values now persist in the form (not the password obviously).
Thanks a lot!

**Comment by steglicd** [comment]
@mray I'm glad you tested again!!!!!
I was wondering about your statement:
"(not the password obviously)"

And you are right. Everything was working fine, except storing the password! So the  actual DNS update may still not working on your box. I updated this pull request. If you could repeat the two lines from above and check if the "status" tab at the dynamic DNS app shows a success message?

**Comment by mray** [comment]
lol. awesome. thanks again.

**Comment by mray** [comment]
Something undesirable is happening in the "Dynamic DNS" -> "configure" tab:
After checking "accept all SSL certificates" the "use HTTP basic authentication" option gets selected.

Maybe I need to reboot after applying the patch or something?

**Comment by steglicd** [comment]
Oh, thanks for the hint. This is a display issue. I will create a new issue and fix this.

**Comment by steglicd** [comment]
@mray 
I opened issue #320 and added a second commit to my pull request which will fix the issue.
Thanks for reporting.
