### ISSUE TITLE
Improve manual IP configuration

### ISSUE THREAD

**Issue by steglicd** [freedombox/Plinth#314]
It should be possible to not only configure IP address manually, but also the Netmask, the Gateway and the DNS Server address.

Also it should be possible to use DHCP and also configure the DNS server on your own.

**Comment by steglicd** [comment]
![ip-dhcp](https://cloud.githubusercontent.com/assets/7570118/11453864/ebaacfec-961b-11e5-85e7-38fb0a4c19c2.png)
![ip-manual](https://cloud.githubusercontent.com/assets/7570118/11453865/ed9254b0-961b-11e5-9ad4-4f41a237130a.png)

**Comment by SunilMohanAdapa** [comment]
The modified interface looks good.

- Should the DNS servers be editable in automatic configuration?  What will happen to the DNS servers provided by the DHCP server?
- We should probably also handle IPv6 while we are at this.  Generally speaking, I believe FreedomBox has overall good support for IPv6 in various configuration areas, except for one or two places such as this one.
- We should probably group the settings into an accordion: http://getbootstrap.com/javascript/#collapse-example-accordion . One group for general settings, one for IPv4 and one for IPv6.

**Comment by steglicd** [comment]
@SunilMohanAdapa 
Yes, the user should be able to get IP Address from DHCP but use his own DNS Servers.
Usecase:
If I am connected to a untrusted network, and I assume that the network provider will log all my DNS requests. Or even worse, he will answer some of my DNS requests himself to present me some "Site is blocked" content instead of the host I try to reach. In that cases it is useful to use your own DNS Servers. 

I.e. in Germany, the "Deutsche Telekom" will answer all DNS requests (even if they don't exist). If a domain does not exist, they give you a IP address which show some advertisement and stuff. For this reason I do not use provider DNS Server.

IPv6 should also be available, yes (but maybe on a different issue?). Same on form grouping?

**Comment by SunilMohanAdapa** [comment]
On 11/30/2015 07:28 PM, Daniel Steglich wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa>
> Yes, the user should be able to get IP Address from DHCP but use his own
> DNS Servers.
> Usecase:
> If I am connected to a untrusted network, and I assume that the network
> provider will log all my DNS requests. Or even worse, he will answer
> some of my DNS requests himself to present me some "Site is blocked"
> content instead of the host I try to reach. In that cases it is useful
> to use your own DNS Servers.
> 
> I.e. in Germany, the "Deutsche Telekom" will answer all DNS requests
> (even if they don't exist). If a domain does not exist, they give you a
> IP address which show some advertisement and stuff. For this reason I do
> not use provider DNS Server.

Sound good.

> 
> IPv6 should also be available, yes (but maybe on a different issue?).
> Same on form grouping?

Okay, your call.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
This has been completed.  We now have the ability to configure gateway, and DNS servers.  Please re-open if you think more can be done.
