### ISSUE TITLE
favicon is distorted

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#317]
The favicon should not get distorted as a result of not fitting perfectly into a 16x16 raster.

![distorted-logo](https://cloud.githubusercontent.com/assets/164785/11457774/e24a2510-96b1-11e5-85a3-8d7d8e445c83.png)

**Comment by SunilMohanAdapa** [comment]
On 11/29/2015 08:29 PM, mray wrote:
> The favicon should not get distorted as a result of not fitting
> perfectly into a 16x16 raster.
> 
> distorted-logo
> <https://cloud.githubusercontent.com/assets/164785/11457774/e24a2510-96b1-11e5-85a3-8d7d8e445c83.png>

You are right, I noticed this a few days back.

The original designer of the logo is longer working with the project.
Also I don't think a specialized version of the logo was made for 16x16,
just a down scaled one.

Please feel free to submit a patch or just a rectified icon.

-- 
Sunil

**Comment by mray** [comment]
I am the original designer of the logo and design guide.
I'm currently looking into how to and where to provide patches...

**Comment by SunilMohanAdapa** [comment]
On 11/29/2015 11:46 PM, mray wrote:
> I am the original designer of the logo and design guide.

Lol :) Sorry to have said that you are longer with the project.  Welcome
back!

> I'm currently looking into how to and where to provide patches...
> 

You can submit patches by

- Posting them on the mailing list

- Or by raising pull requests on GitHub here.

**Comment by jvalleroy** [comment]
Fixed in #583.
