### ISSUE TITLE
Dynamic DNS: inverted Options are shown on config page

### ISSUE THREAD

**Issue by steglicd** [freedombox/Plinth#320]
Configure:
[x] accept all SSL certificates
[ ] use HTTP basic authentication

Save and reload page:
[ ] accept all SSL certificates
[x] use HTTP basic authentication

Internally the dynamic DNS module will accept all SSL certificates and will not use HTTP basic authentication. But the display is wrong.

**Comment by SunilMohanAdapa** [comment]
Now fixed with the merge of #311.
