### ISSUE TITLE
Changing hostname messes up ejabberd config file

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#33]
During a hostname change process, Plinth's XMPP actions change the hostname in the ejabberd configuration file.  This is done using a simple regular expression replacing from old hostname to new hostname.  If the old hostname is something like "e" or "the" then a lot of text in the configuration file gets replaced with new hostname.  This most likely causes the configuration to become invalid and ejabberd does not start after that.  This also leads to hostname change process to fail if I remember correctly.

**Comment by jvalleroy** [comment]
I believe this has been fixed. Please re-open if that's not the case.
