### ISSUE TITLE
Email Weblate

### ISSUE THREAD

**Issue by phylophyl** [freedombox/Plinth#331]
Alerts and technical messages are sent from Weblate to my email weblate@hyperlecture.net
We could have instead a weblate@freedomboxfoundation.org email with redirections and irc logs if possible.

**Comment by phylophyl** [comment]
philippe@hyperlecture.net, sunil@medhas.org are receiving weblate@hyperlecture.net
anyone interested in dealing with weblate issues ?

**Comment by matujo** [comment]
Are we using weblate for translation? Who is running the server?

**Comment by phylophyl** [comment]
We do since today actually after discussions on the list
https://lists.alioth.debian.org/pipermail/freedombox-discuss/2015-December/thread.html

Michal Čihař is answering to emails regarding technical issues on weblate which is sponsored by the host provider http://www.webhostingsecretrevealed.net/

Weblate is a free software (GNU General Public License), we can run it on our own server if we like, it is part of an emergency plan we want to have in case of bad hosting quality.

**Comment by phylophyl** [comment]
this issue should become "FreedomBox.org email" issue

**Comment by phylophyl** [comment]
Issue is now "FreedomBox.org email"
