### ISSUE TITLE
UnicodeDecodeError at /help/manual/

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#333]
I get this error when visiting the manual page:
```'ascii' codec can't decode byte 0xa0 in position 98080: ordinal not in range(128)```

It seems to be referring to line 640 of freedombox-manual.html, which has this text:
```</td><td class="auto-generated">�</td><td class="auto-generated">�</td><td class="auto-generated">�</td></tr>```

**Comment by SunilMohanAdapa** [comment]
I have fixed this issue by introducing empty cells in tables where this is causing problems.  Please tag 0.7.1 for release.
