### ISSUE TITLE
Move freedombox-setup/firstrun.d into Plinth

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#34]
> "That way, all the first run config is in one package."

If any user decision is needed to do this configuration it can be provided in first boot configuration in Plinth. If this configuration depends on questions take during first boot (such as hostname) then also things can be properly done.

Another advantage is that instead of installing all the dependent packages in FreedomBox during build time, a user and select which services she expects to use in Plinth and then packages will be installed on demand and configuration will be done.  Since Plinth itself is modularized into "Apps" this also means that this configuration will become modularized into the apps.

**Comment by jvalleroy** [comment]
First run has been eliminated, so this can be closed.
