### ISSUE TITLE
Translation strings review

### ISSUE THREAD

**Issue by phylophyl** [freedombox/Plinth#343]
TABLE OF ISSUES REVIEWED

- [ ] FirstBoot page
  - [ ] LDAP user to be deleted 
  - [x] Box it up button
- [ ] Apps
  - [ ] Need of a clear app home page link
  - [ ] Need of content explaining apps before clicking on apps pages.
  - [ ] App title and definition on each app pages

Who is in charge of editing strings on global po file ?

**Comment by phylophyl** [comment]
URL https://freedombox.local/plinth/firstboot/state1/
SCREENSHOT http://i.imgur.com/VkPCr2J.png
STRING: 'Box it up!'
ISSUE: places on a save buttob, is there a mix between two strings?
PROPOSAL: 'Save"

**Comment by jvalleroy** [comment]
:+1: There's no need to mention LDAP during firstboot.

Perhaps "Box it up!" can be changed to "Start using FreedomBox"?

**Comment by phylophyl** [comment]
> Perhaps "Box it up!" can be changed to "Start using FreedomBox"?
-  My bad, i read "Box IS up!". I'll do the proper change in the french local file.

**Comment by phylophyl** [comment]
URL:https://freedombox.local/plinth/apps/
ISSUE: missing clear Apps home page link
PROPOSAL: On every app install page, there is a need of a "Back to Apps home page" to avoid searching how surfing back. Or a "Apps Home" link on the left frame along with apps install links.

**Comment by phylophyl** [comment]
URL:https://freedombox.local/plinth/apps/
ISSUE: missing introduction on each app on the home page + short explanation of what happen when you click on the app links on the left frame (will it install by clicking? or not)
PROPOSAL: copy existing definition strings ($name in bold - $definition)
PROPOSAL: new string 'Please click on the Apps link on the left to discover more details about it and access to install feature."

**Comment by phylophyl** [comment]
URL https://freedombox.local/plinth/apps/**deluge-or-name-of-app**/
ISSUE Poor presentation
PROPOSAL: replace INSTALLATION bold title by the name of the app
PROPOSAL: add definition of the app under the title

**Comment by ikmaak** [comment]
Hi, I am confused by this Issue, as I am announcing my work for some time on replacing most of the strings with a freedoms-oriented approach to the interface instead of a technology based approach. I think we should get 0.7.2 out as soon as possible, to avoid adding more things like Quassel to the release, instead of just translation improvements.

My work would replace 80-95% of the strings, and that is why talked about this in the Hackcall and decided to do a translation-review-only release as soon as possible after 0.7.1, so the new strings could be introduced with 0.8. As 0.8 is planned for 23 of Jan, base strings would have to be ready at least a week beforehand, to give time to translators to do their work.

Because of this we decided to not promote weblate to the "masses" yet, and wait for that till 0.8. After that we can attract more languages.

**Comment by phylophyl** [comment]
Don't be ikmaak. This issue is made to make quick moves (non techy oriented mainly), keep in mind that these are "proposals", quick feelings while on firstboot, not heavy work.

As you seem to be very oriented on this, you are assignee now :)

**Comment by ikmaak** [comment]
As every change has to be re-reviewed by all translators, small changes can lead to a lot of work. Also this proposal does not address important issues like the use of "You" in the current strings, which would lead to a short-lived change in a lot of strings, including grammar changes which is one of the most time consuming forms of review.

Thank you for assigning me :)

**Comment by phylophyl** [comment]
You are because i understand fully nothing of what you are saying and it takes too much energy trying :) I put also your admin of Weblate.

So let's see your moves now. You want to change "80-95%" of the strings with a project you can not show yet. For this reason, you want to block another small move made to put an end to the 0.7 version. On weblate, your plan is to block translations made by new translators. You want to warn a new translator working now on portuguese weblate file that his work will be 95% deleted. Honestly ikmaak, this is not serious. 

I am working to have fun, not to have someone consuming my energy mate. As long as you are doing so, i prefer pushing other projects.

**Comment by ikmaak** [comment]
I would like some clarification on the first sentence of your last message, as I am unclear of your meaning there.

I am not trying to block translations, I would like to explain the translator that some changes could be made soon, and his efforts 'could' be short lived. If he wants to contribute now, he can still do that, just be informed about it. I explicitly do NOT want to block people doing what they like.

The move away from the 0.7x branch for me is more of an issue of getting as much of the work as possible that is not translation onto the 0.8 for bigger exposure then. If we do the release of 0.7.2 sooner, it would stop prolonging the current feature freeze.

Have you ever tried to design something while the customer sits beside you saying "lets try this, no, undo it, try it in green now. No red!". That increases dev time a lot. I would like to prevent this issue by working on the base alone, and requested info during the hack call to help gather viewpoints.

When my "freedom/user oriented storyline" has all the basic elements, I will be happy to share that base for discussion. I do not mind if the idea is not used, but expect that at least parts of it will. I hope to be ready to present the idea soon.

The basic idea is not to focus on the programs the box offers, but the possibilities it offers users, and the freedoms it protects/enhances. Please inform me of the questions/opinions you have about this.

I am sorry if I’m spoiling your fun, and would like to stop doing that. Please accept my sincere apologies, and advise me on how to support your efforts better, as I am very grateful for your hard work.

P.S. The "You" issue is an issue of clarity and consistency in strings, it seems to be good form to avoid sentences including "you", to prevent issues with formality etc. in translations.

**Comment by phylophyl** [comment]
Dispute over.
I'll close "Translation strings review #343" issue to create a more explicit and rational one like "minimal global strings proposals for non techy" and make the 0.7.2 happen increasing inclusive manner. I'll open a discussion/dispute page on wiki to avoid noise.
