### ISSUE TITLE
shaarli: Update firewall service status after install

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#344]
After Shaarli is installed, the Firewall page still shows it as "Disabled".

**Comment by phylophyl** [comment]
As a beguinner, how can i help?

**Comment by jvalleroy** [comment]
@phylophyl We need to have an "on_install" function that notifies that the service is enabled. Then the on_install function is passed to the @package.required decorator.

Example: https://github.com/freedombox/Plinth/blob/master/plinth/modules/quassel/views.py#L32

**Comment by phylophyl** [comment]
If i add 

def on_install():
    """Notify that the service is now enabled."""
    shaarli.service.notify_enabled(None, True)

between line 29 and 32 on this file
https://github.com/freedombox/Plinth/blob/master/plinth/modules/shaarli/views.py

is that ok ?

**Comment by jvalleroy** [comment]
@phylophyl That should be ok, but also need to let the package installer know which function to call when install is finished.

Could you open a pull request so that I can review and test your changes?

**Comment by jvalleroy** [comment]
This is fixed with #348.
