### ISSUE TITLE
Global strings review for 0.7.2

### ISSUE THREAD

**Issue by phylophyl** [freedombox/Plinth#347]
Minimal global strings proposals for non techy. Should not affect V0.7 frozen structure.
Valid strings edition will be integrated in tagging and packaging on Dec 19 thanks to James.

If ticked, proposal will be integreted:
- [x] LDAP mention to delete
- [x] Add precision on the effect of a click
- [x] Power term translation
- [x] Domain Name translation

**Comment by phylophyl** [comment]
URL: https://freedombox.local/plinth/firstboot/state1/
STRING: (..) An LDAP user with administrative privileges (sudo) is also created.
ISSUE: LDAP is a bit too technical.
PROPOSAL: 'Choose a username and password to access this web interface. The password can be changed later. This user will be granted administrative privileges. Other users can be added later.'

**Comment by phylophyl** [comment]
URL: https://freedombox.local/plinth/apps/
STRING: You can install and run various services and applications on your FreedomBox.
ISSUE: Landing for the first time, you don't know if clicking on app links will install the app.
PROPOSAL: You can install and run various services and applications on your FreedomBox. Click on any app page link on your left to read a description of application and choose to install it or mot.

**Comment by phylophyl** [comment]
URL: https://freedombox.local/plinth/sys/ + https://freedombox.local/plinth/sys/power/
ISSUE: Power term is not translated in the left frame. It is on the power page though.
PROPOSAL: use "Power" string for left frame term as well.

**Comment by phylophyl** [comment]
URL: https://freedombox.local/plinth/sys/names/
ISSUE: "Domain Name" term is not translated.
PROPOSAL: use "Domain Name" string already translated for this page as well.

**Comment by SunilMohanAdapa** [comment]
All the suggestions look good, for the suggestion:

>  "You can install and run various services and applications on your FreedomBox. Click on any app page link on your left to read a description of the application and choose to install it or not."

I suggest that we remove the "or not" at the end.

**Comment by phylophyl** [comment]
Fine for me

**Comment by jvalleroy** [comment]
I think these items are all resolved. Please reopen if needed.
