### ISSUE TITLE
Local strings v 0.7.2

### ISSUE THREAD

**Issue by phylophyl** [freedombox/Plinth#351]
**Schedule for packaging : Dec 23rd instead of Dec 26th (Sunil / imaak)**

Current localization status before packaging: 
 * [x] Danish: 100.0% (weblate)
 * [x] Dutch: 100.0% (weblate)
 * [x] French: 100.0% (weblate)
 * [x] German: 100% (weblate)
 * [x] Norwegian Bokmål: 100.0% (transifex) 96.0% (weblate)
 * [ ] Telugu: 42.0% (weblate)
 * [ ] Portuguese: 5,4% (weblate)
 * [ ] Spanish:0% (weblate)
 * [ ] Italian:0% (weblate)

Check mark above means that the translation team agrees that the language is ready for 0.7.2 release.  The main objective of this release is to allow the translators to see the interface strings in FreedomBox 0.7 images and make corrections. The release will be done early if translators of the completed languages (top five here) all mark as done.

Resources:
https://hosted.weblate.org/projects/freedombox/plinth/
https://www.transifex.com/freedombox/

**Comment by ikmaak** [comment]
I'm ok with current NL translations. Please mark as Done.

**Comment by phylophyl** [comment]
Norwegian Bokmål: 
unlikely to find time before the cutoff date, still texts are updated and proof read in transifex.

**Comment by Diet-mar** [comment]
German is done as well.

**Comment by phylophyl** [comment]
French done also.

**Comment by mikini** [comment]
There are no untranslated strings in Danish on Weblate either. So in relation to the above definition it could be considered 'done'.

**Comment by SunilMohanAdapa** [comment]
Based on @mikini 's update, I have marked Danish as completed.

We can now proceed with an early release of v0.7.2.  If anyone wants to check the UI further on the latest images and make further updates, please request for a delay.  Otherwise, @jvalleroy , please tag the trunk for 0.7.2.  When the plinth's Debian package is also updated, we an request an upload, perhaps tomorrow.

**Comment by phylophyl** [comment]
How is handled technically Norwegian Bokmål: 100.0% (transifex) 96.0% (weblate)?

**Comment by SunilMohanAdapa** [comment]
We need to commit this manually, before tagging.  Forgot about it.

**Comment by SunilMohanAdapa** [comment]
I have committed NB from Transifex.

**Comment by SunilMohanAdapa** [comment]
0.7.2 has been released after the five translation teams have agreed to it.  Closing this issue.
