### ISSUE TITLE
FAQ: Localization freeze Dec 2015

### ISSUE THREAD

**Issue by phylophyl** [freedombox/Plinth#353]
Waiting for a proposal from imaak focusing on user workflow (users oriented, not softwares) and impacting strings, localization efforts and advertising are frozen.

**Comment by phylophyl** [comment]
How long exactly is that freeze? 
If i trust my memory, it has been said at least 2 weeks, meaning till January 4th 2016. 
Is that correct?

**Comment by SunilMohanAdapa** [comment]
That freeze is now lifted.  Many string changes have been proposed by Calyp and we have entered another freeze for releasing 0.8.
