### ISSUE TITLE
Manually Starting Unattended Upgrades from Plinth Requires Manual Recovery

### ISSUE THREAD

**Issue by phylophyl** [freedombox/Plinth#366]
I am running FBX on Debian Sid and Cubietruck. Here are messages i got when installing apps, for instance Ikiwiki.

Ikiwiki install vi Tor=
Error installing packages: gpg-failure W: The repository 'tor+http://debian.grn.cat/debian sid Release' does not have a Release file.

without Tor activated for packages downloads =
Error installing packages: E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. None

**Comment by SunilMohanAdapa** [comment]
On Sunday 10 January 2016 07:01 AM, Philippe Baret wrote:
> I am running FBX on Debian Sid and Cubietruck Here are messages i got
> when installing apps, for instance Ikiwiki
> 
> Ikiwiki install vi Tor=
> Error installing packages: gpg-failure W: The repository
> 'tor+http://debiangrncat/debian sid Release' does not have a Release file
> 
> without Tor activated for packages downloads =
> Error installing packages: E: dpkg was interrupted, you must manually
> run 'dpkg --configure -a' to correct the problem None

This happens when a package installation process gets interrupted such
as because of a power failure.  The manual work around to the problem is
to run `dpkg -configure -a` on the command line.

This is a larger problem with automatic package management in Debian.
Perhaps we could detect this specific case and run the command from
within Plinth.

-- 
Sunil

**Comment by phylophyl** [comment]
i run `dpkg -configure -a` on the command line.

https://freedombox.local/plinth/apps/
is working fine

https://freedombox.local/plinth/apps/xmpp/
or any other apps are giving:
```
500
This is an internal error and not something you caused or can fix. Please report the error on the bug tracker so we can fix it.
```

running apt-get update on command line (serial on fbx account + su) gives
```
Ign:3 http://ftp.fr.debian.org sid/main armhf Packages
Err:3 http://ftp.fr.debian.org sid/main armhf Packages
  404  Not Found [IP: xxx.xx.xx.xx xx]
W: The repository 'http://ftp.fr.debian.org sid Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Failed to fetch http://ftp.fr.debian.org/dists/sid/main/binary-armhf/Packages  404  Not Found [IP: xxx.xx.xx.xx xx]
W: Failed to fetch http://ftp.fr.debian.org/dists/sid/contrib/binary-armhf/Packages  404  Not Found [IP: xxx.xx.xx.xx xx]
W: Failed to fetch http://ftp.fr.debian.org/dists/sid/non-free/binary-armhf/Packages  404  Not Found [IP: xxx.xx.xx.xx xx]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

running apt-get upgrade gives:
root@freedombox:/home/fbx# apt-get upgrade
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: The package plinth needs to be reinstalled, but I can't find an archive for it.
```

root@freedombox:/home/fbx# dpkg --configure -a
```
dpkg: error processing package plinth (--configure):
 package is in a very bad inconsistent state; you should
 reinstall it before attempting configuration
Errors were encountered while processing:
 plinth
```

**Comment by phylophyl** [comment]
root@freedombox:/home/fbx# apt-get purge plinth
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: The package plinth needs to be reinstalled, but I can't find an archive for it.
```

root@freedombox:/home/fbx# apt-get install plinth
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: The package plinth needs to be reinstalled, but I can't find an archive for it.
root@freedombox:/home/fbx# apt-get install freedombox-setup
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: The package plinth needs to be reinstalled, but I can't find an archive for it.
```

**Comment by phylophyl** [comment]
> This happens when a package installation process gets interrupted such
> as because of a power failure. 

It happened without a power failure actually, rather as a result of Ikiwiki install via Tor

**Comment by NickDaly** [comment]
I think I also ran across this bug, but not certain about the reproduction conditions:

1. Boot a 0.7 image, go to Plinth.
2. Attempt to install ikiwiki.
3. Watch ikiwiki install fail.
4. Activate unattended-upgrades.
5. Manually kick off an unattended-upgrade.
6. Wait about an hour.
7. Apt-get will have been interrupted and plinth will need to be reinstalled.  After reinstalling, plinth pages will 503 error.

**Comment by NickDaly** [comment]
Closely related to #304.

**Comment by NickDaly** [comment]
Confirming manually running "apt-get update && apt-get upgrade" via SSH upgrades successfully.  Seems like Sunil correctly identified the issue, that the manually started u-u process is killing Plinth during the upgrade.

The correct long-term fix is to dissociate-fork or nohup the started upgrade process, and a viable short-term fix is to prevent the user from kicking off the process manually, from within Plinth.

**Comment by SunilMohanAdapa** [comment]
Looks we now have confirmation for both scenarios: manual trigger of upgrades from Plinth fails and upgrade from command line works.

**Comment by SunilMohanAdapa** [comment]
This is something we would like to fix for the next release.
