### ISSUE TITLE
PackageKit is not a direct dependency for Plinth

### ISSUE THREAD

**Issue by marxistvegan** [freedombox/Plinth#369]
This is a new install on a beaglebone black. 

For reference I installed the beaglebone 8.2 debian image which is running jessie. I then upgraded to stretch and then to sid. After upgrading to sid and rebooting to make sure network and kernel were working I then installed freedombox-setup.

The freedombox-setup on apt-get install brought up the macchanger which I missed the note to select 'no' and by mistake selected 'yes' however it seemed the install failed as after it ran I not able to run the setup as it was not there. So I tried to reinstall it instead and in that case I was never presented with a macchanger option. The reason i mention this is because after running the setup and reboot my resolveconf was not set correctly. I made the changes to the /etc/resolvconf/resolve.conf/base to be the same nameserver as my laptop as they share the same router. That fixed the issue and on reboot I was able to visit the freedombox web ui to start and complete the install. I was able to change the configurations for the host and domain.

After installing and configuring via the web ui I went to add an app, and was presented with a 500 error. This occurs in all instances.

**Comment by marxistvegan** [comment]
this is the tail from /var/log/syslog
`Jan 12 13:15:38 beaglebone nslcd[748]: [334873] <passwd="*"> request denied by validnames option
Jan 12 13:15:54 beaglebone ntpd[694]: error resolving pool 2.debian.pool.ntp.org: Name or service not known (-2)
Jan 12 13:15:55 beaglebone ntpd[694]: error resolving pool 1.debian.pool.ntp.org: Name or service not known (-2)
Jan 12 13:15:56 beaglebone ntpd[694]: error resolving pool 3.debian.pool.ntp.org: Name or service not known (-2)
Jan 12 13:15:56 beaglebone ntpd[694]: error resolving pool 0.debian.pool.ntp.org: Name or service not known (-2)
Jan 12 13:16:27 beaglebone nslcd[748]: [b0dc51] <passwd="*"> request denied by validnames option
Jan 12 13:16:47 beaglebone plinth[643]: [2016-01-12 13:16:47,007] django.request ERROR    Internal Server Error: /plinth/apps/tor/
Jan 12 13:16:47 beaglebone plinth[643]: Traceback (most recent call last):
Jan 12 13:16:47 beaglebone plinth[643]: File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 149, in get_response
Jan 12 13:16:47 beaglebone plinth[643]: response = self.process_exception_by_middleware(e, request)
Jan 12 13:16:47 beaglebone plinth[643]: File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 147, in get_response
Jan 12 13:16:47 beaglebone plinth[643]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jan 12 13:16:47 beaglebone plinth[643]: File "/usr/lib/python3/dist-packages/plinth/package.py", line 232, in wrapper
Jan 12 13:16:47 beaglebone plinth[643]: if not _should_show_install_view(request, package_names):
Jan 12 13:16:47 beaglebone plinth[643]: File "/usr/lib/python3/dist-packages/plinth/package.py", line 251, in _should_show_install_view
Jan 12 13:16:47 beaglebone plinth[643]: is_installed = check_installed(package_names)
Jan 12 13:16:47 beaglebone plinth[643]: File "/usr/lib/python3/dist-packages/plinth/package.py", line 285, in check_installed
Jan 12 13:16:47 beaglebone plinth[643]: _callback, None)
Jan 12 13:16:47 beaglebone plinth[643]: GLib.GError: pk_control_error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.PackageKit was not provided by any .service files (0)
Jan 12 13:17:01 beaglebone ntpd[694]: error resolving pool 2.debian.pool.ntp.org: Name or service not known (-2)
Jan 12 13:17:01 beaglebone ntpd[694]: error resolving pool 1.debian.pool.ntp.org: Name or service not known (-2)
Jan 12 13:17:01 beaglebone ntpd[694]: error resolving pool 0.debian.pool.ntp.org: Name or service not known (-2)
Jan 12 13:17:02 beaglebone CRON[1623]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jan 12 13:17:02 beaglebone ntpd[694]: error resolving pool 3.debian.pool.ntp.org: Name or service not known (-2)
^[[1;2A
`

**Comment by SunilMohanAdapa** [comment]
PackageKit is not installed.  It does not appear to be direct dependency of either freedombo-setup or Plinth.  It must be getting pulled in by something as recommends.

**Comment by SunilMohanAdapa** [comment]
I confirmed that Plinth depends on gir1.2-packagekitglib-1.0, which depends on libpackagekit-glib2-18 which recommends packagekit.  We need to add explicit dependency on packagekit for Plinth.

**Comment by SunilMohanAdapa** [comment]
To fix this issue:
- Add to dependencies list in INSTALL in Plinth main repository.
- Add to Debian package dependencies list in debian/control inside plinth-debin repository.

**Comment by joelvalleroy** [comment]
ignore my above 2 commits, sorry!

proper commit + pull: https://github.com/freedombox/Plinth/pull/394

**Comment by jvalleroy** [comment]
This is fixed now in both INSTALL and the Debian package.
