### ISSUE TITLE
Owncloud database not created

### ISSUE THREAD

**Issue by marxistvegan** [freedombox/Plinth#370]
Hey folks,

So this is in the path from doing the install via debian sid and apt-get install freedombox-setup. I was able to install owncloud via the apps but the corresponding database and password were not created. I can visit the /owncloud but it is asking for database credentials.

**Comment by SunilMohanAdapa** [comment]
On Wednesday 13 January 2016 05:39 AM, Stephen wrote:
> Hey folks,
> 
> So this is in the path from doing the install via debian sid and apt-get
> install freedombox-setup I was able to install owncloud via the apps but
> the corresponding database and password were not created I can visit the
> /owncloud but it is asking for database credentials

Thanks for reporting.

1) Would it be possible to post the syslog messages for the install?

2) Did you see any error while installing and setting up ownCloud app?

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
On Wednesday 13 January 2016 09:42 AM, Sunil Mohan Adapa wrote:
> On Wednesday 13 January 2016 05:39 AM, Stephen wrote:
>> Hey folks,
>>
>> So this is in the path from doing the install via debian sid and apt-get
>> install freedombox-setup I was able to install owncloud via the apps but
>> the corresponding database and password were not created I can visit the
>> /owncloud but it is asking for database credentials
> 
> Thanks for reporting.
> 
> 1) Would it be possible to post the syslog messages for the install?
> 
> 2) Did you see any error while installing and setting up ownCloud app?
> 

This could have happened if the post setup script for the owncloud
failed.  There are only very few setups involved in the setup, so
checking until which setup has been performed will help locate the problem.

1) Does a PostgreSQL user known as owncloud exist?
2) Does a PostgreSQL database know as owncloud exist?
3) Does /etc/owncloud/autoconfig.php exist?  What are its contents?
4) Does /etc/owncloud/config.php exist? What are its contents?

-- 
Sunil

**Comment by marxistvegan** [comment]
In bad form, i did not copy the logs before doing a reinstall...but seems this is likely able to be duplicated when I have the chance I will do a similar install maybe this weekend on a different device

**Comment by SunilMohanAdapa** [comment]
Are we able to reproduce the problem and collect more information?  Otherwise, perhaps we should close the issue.

**Comment by fonfon** [comment]
Unfortunately the owncloud package is currently being removed from Debian. I'd say we should focus on searching/implementing alternatives and added the 'wontfix' label.
