### ISSUE TITLE
Error while setting up openvpn

### ISSUE THREAD

**Issue by stacycockrum** [freedombox/Plinth#378]
Received the following error while performing the setup for openvpn. I have a raspberry pi 2.  Received the error after setup ran for more than an hour. 

500
This is an internal error and not something you caused or can fix. Please report the error on the bug tracker so we can fix it.

**Comment by SunilMohanAdapa** [comment]
On Sunday 17 January 2016 01:00 AM, stacycockrum wrote:
> Received the following error while performing the setup for openvpn I
> have a raspberry pi 2 Received the error after setup ran for more than
> an hour
> 
> 500
> This is an internal error and not something you caused or can fix Please
> report the error on the bug tracker so we can fix it

Could you please post the relavent errors messages from
/var/log/plinth/status.log.  It will contain informaton about what
exactly failed.

-- 
Sunil

**Comment by stacycockrum** [comment]
I apologize for not including this yesterday.  Just didn't know what would be helpful.  This actually includes all of the activity from 1/16.  I just wasn't sure what to remove.  Thank you.
[20160116status.txt](https://github.com/freedombox/Plinth/files/93610/20160116status.txt)
