### ISSUE TITLE
networks: Allow editing IP/netmask when 'shared' mode connections

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#408]
Currently when 'shared' mode is selected in creating/editing a network interface, IP address and netmask fields are blanked out and disabled.  However, there is an interesting feature if we allow setting IP/netmask.  If IP/netmask are set, the IP will be set on the interface and remaining IPs in the network defined by IP/netmask pair are allocated to the the clients.  By default, 10.42.0.*/24 is selected as range.  By being able to configure, it is possible to change the allocation range and also increase the number of possible IPs in the range to larger number than 253.

To fix the issue:
- Don't disable IP/netmask in shared mode
- Perhaps expand the description of IP address/netmask fields to explain what they mean in 'shared' mode.

Ping @steglicd .

**Comment by steglicd** [comment]
was not the intention of this feature, but sounds god. Still need to check if some other things needs to be done to to accomplish this (i.e. if the DHCP Server range automatically adopts to the interface IP).

@SunilMohanAdapa did you tested this?

**Comment by SunilMohanAdapa** [comment]
A friend of mine used this in the field.  He got to know about this trick from network-manager folks on IRC. He had to use 'nmtui' to get the job done since Plinth was not allowing.  As he has experienced, after assigning the IP, the DHCP server range automatically adopts to this range.

**Comment by bhuvankrishna** [comment]
I updated Q&A with the solution. this is the [link](https://wiki.debian.org/FreedomBox/QuestionsAndAnswers#Is_there_a_way_to_change_the_default_IP_range_and_class_in_FreedomBox.3F) for the same.

**Comment by jvalleroy** [comment]
Fixed in #477.
