### ISSUE TITLE
Reuse code for enabling/disabling services

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#415]
@fonfon floated the idea of reusing the code for enabling/disabling a service from action.  In each module there is a lot of boiler plate code enabling and disabling services. The discussion went like this:
- We agreed that we should reuse the code.  This can be done by writing an function to enable/disable a service and using it in all modules.
- However, this will not play nice when Plinth starts running as non-root user.
- Then we can create a common action script for enabling and disabling all services.
- We loose a bit on security here because currently the set of services manageable for Plinth is restricted to our apps.  But with this approach there is no restriction.

Here is a possible solution: we will define a variable in each `<module>/__init__.py` as `services_managed: ['service1', 'service2']` etc.  Then we will write a common action script that takes three arguments `<module_name> <service_name> <enable/disable>`.  Then the action script will:
- Obtain the module path from /etc/plinth/modules-enabled/<module_name>
- Import the module and obtain list of services.
- Check that services asked for is part of that list.
- Go ahead and perform operations on that service.

@fonfon What do you think? Are you interested in taking it up?

**Comment by fonfon** [comment]
I'll try to solve this issue, I already had a look into it.

**Comment by fonfon** [comment]
I created a dummy pull request (far from merge-able) to show how I want to change things.
Basically it introduces `actions.service`, and adapts `plinth.Service` as well as `views.ConfigurationView`:
https://github.com/fonfon/Plinth/pull/2

The pull request description contains more detailed information. I'll continue working on it and come up with a proper pull request here, I just want you to be able to have a look already (and let you know that I'm working on it).

**Comment by SunilMohanAdapa** [comment]
This is now closed with the merge of pull request #446.
