### ISSUE TITLE
Have non-admin user's in Plinth

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#426]
We should have users in Plinth who are non-admin users.  Currently each user in Plinth is an administrator.  If the FreedomBox owner wishes to provide friends and family with accounts these need to be non-admin users.  Imagine a user logging into Plinth to download OpenVPN profile but not being able to alter anything else.

Various functions in FreedomBox need to check for admin privileges.

**Comment by jvalleroy** [comment]
Fixed in  #733.
