### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by MithridatesEupator** [freedombox/Plinth#432]
Used to be able to log in but now have no functionality. Always the same standard internal error message:

500
This is an internal error and not something you caused or can fix. Please report the error on the bug tracker so we can fix it.

**Comment by jvalleroy** [comment]
Could you please check /var/log/plinth/status.log for any errors, and post them here?

**Comment by MithridatesEupator** [comment]
Yes. Can you provide me with instructions on how to do check that file? I'm sorry—I'm a newbie trying to learn. I'm using a Pi2.

**Comment by jvalleroy** [comment]
@MithridatesEupator If you are not able to log in to the system at all, it may be easier to take out the microSD card and check its contents from another computer.

**Comment by MithridatesEupator** [comment]
I will do this.

**Comment by SunilMohanAdapa** [comment]
@MithridatesEupator , ping.

**Comment by Irianx** [comment]
Hi. I think I have the same problem. Clicking on "Monkeysphere" from "Plinth" is showing the same error message. Here the plint/status.log content for the action:

[2016-07-17 17:01:56,880] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/monkeysphere', 'host-show-keys']
[2016-07-17 17:01:59,132] django.request ERROR    Internal Server Error: /plinth/sys/monkeysphere/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/plinth/modules/monkeysphere/views.py", line 40, in index
    status = get_status()
  File "/usr/lib/python3/dist-packages/plinth/modules/monkeysphere/views.py", line 98, in get_status
    return {'keys': get_keys()}
  File "/usr/lib/python3/dist-packages/plinth/modules/monkeysphere/views.py", line 112, in get_keys
    if '*' in key['available_domains']:
KeyError: 'available_domains'

**Comment by jvalleroy** [comment]
@Irianx Could you please run the following:
```
$ sudo /usr/share/plinth/actions/monkeysphere host-show-keys
```
And send the output?

**Comment by Irianx** [comment]
I replaced my hostname by "myhostname.de", if you need my hostname, i will send you a private message (is hope this is possible? I am new here):

{"keys": {"3:9b:d9:01:d8:37:2f:05:36:c8:ff:42:61:79:a1:30": {"key_file": "/etc/ssl/private/ssl-cert-snakeoil.key", "ssh_fingerprint": "3:9b:d9:01:d8:37:2f:05:36:c8:ff:42:61:79:a1:30", "service": "https", "available_domains": ["*"]}, "53:9b:d9:01:d8:37:2f:05:36:c8:ff:42:61:79:a1:30": {"pub": "2048R/F0C3D75D", "ssh_fingerprint": "53:9b:d9:01:d8:37:2f:05:36:c8:ff:42:61:79:a1:30", "openpgp_fingerprint": "7152502893AF5B1F0E0D5F12894F5370F0C3D75D", "service": "https", "ssh_key_type": "RSA", "imported_domains": ["myhostname.de"], "ssh_key_size": "2048", "uids": ["https://myhostname.de"], "date": "2016-07-17"}, "d6:a5:56:65:3e:b4:70:3f:ba:89:b5:e4:3e:f0:8d:2d": {"key_file": "/etc/letsencrypt/live/myhostname.de/privkey.pem", "ssh_fingerprint": "d6:a5:56:65:3e:b4:70:3f:ba:89:b5:e4:3e:f0:8d:2d", "service": "https", "available_domains": ["myhostname.de"]}, "90:b1:3e:c8:19:cb:75:2f:41:e8:b5:8e:a8:de:7c:b3": {"pub": "2048R/F4AE2F68", "key_file": "/etc/ssh/ssh_host_rsa_key", "ssh_fingerprint": "90:b1:3e:c8:19:cb:75:2f:41:e8:b5:8e:a8:de:7c:b3", "openpgp_fingerprint": "5B5BC45270619A915DBEEA60BAB142F2F4AE2F68", "service": "ssh", "ssh_key_type": "RSA", "imported_domains": ["myhostname.de"], "ssh_key_size": "2048", "uids": ["ssh://myhostname.de"], "date": "2016-07-17", "available_domains": ["*"]}}}

**Comment by SunilMohanAdapa** [comment]
The monkeysphere issues is fixed elsewhere. Closing the original issue due to lack of more information. Please reopen the issue if more information is available.
