### ISSUE TITLE
Add DNS module

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#434]
This module would be used to configure bind.

**Comment by tonghuix** [comment]
It is so useful in China!

**Comment by mridulnagpal** [comment]
@jvalleroy 
I would like to work on this issue. How do I proceed?

**Comment by jvalleroy** [comment]
@mridulnagpal Do you have experience with DNS servers? I guess bind is the most popular, but there are several others that could be considered.

We will need a plinth module that installs the DNS server package. But we also need to consider:
1. A default configuration that will work for most FreedomBox users.
2. Which configuration controls should be available through Plinth UI.

Sorry this is very general, but I haven't done much with DNS servers, so I don't really know any details.

**Comment by mridulnagpal** [comment]
@jvalleroy I am working on adding BIND will post a PR soon.

**Comment by jvalleroy** [comment]
Bind module was added in #693. It supports the following configuration:
- Enable/disable forwarding
- Enable/disable DNSSEC
- Set DNS forwarders

Feel free to open new issues to request any additional features, or for any problems that we find.
