### ISSUE TITLE
UI polishing: Improve status displays when enabling/disabling Tor

### ISSUE THREAD

**Issue by fonfon** [freedombox/Plinth#437]
When enabling/disabling Tor, the status information could be improved, for example by displaying an animated GIF to make it more obvious that there's something still happening:
![image](https://cloud.githubusercontent.com/assets/1867309/14425670/4690ad78-ffe9-11e5-83ad-8ccc0e44dfb3.png)

(perhaps there are more places than tor that use this kind of a status display)

**Comment by jvalleroy** [comment]
Fixed in #524.
