### ISSUE TITLE
R Pi2

### ISSUE THREAD

**Issue by clhamlin10** [freedombox/Plinth#448]
OpenVPN: Got error 500 - "nothing you can do about it".

**Comment by jvalleroy** [comment]
Could you please check for errors in /var/log/plinth/status.log? There should be a python exception at the end of the log file, after you get error 500.

**Comment by SunilMohanAdapa** [comment]
This seems to be duplicate of #459 .  I have provided workaround to the problem.  The core issue will be fixed with #456 .
