### ISSUE TITLE
Improve 500 error page

### ISSUE THREAD

**Issue by fonfon** [freedombox/Plinth#451]
Until #276 is implemented (or also additionally), we could make the 500 error page more helpful.

There could be an additional page that shows the last X lines of `/var/log/plinth/status.log`. The error page could show a link to it (Error-pages themselves should be as simple as possible, and make it extremely unlikely that another error occurs on them). 

Users reporting an issue can directly include the information from there. This should reduce the issues with missing information (like #448) where we have to ask users to provide the information from the log file manually.

Are there any objections to showing the last bit of this log-file in Plinth?

**Comment by fonfon** [comment]
Hints for beginners picking up this issue:

- I'd add the page containing the last X lines of the log-file to the module `plinth/modules/system`. You'll have to create a new URL (urls.py), a template and a new view for the page.
- In the view, make sure to read the currently configured `status_log_file`:
```
    from plinth import cfg
    cfg.status_log_file
```
- Then you add a link to this new page to the template `plinth/templates/500.html`.

**Comment by harry-7** [comment]
I want to work on this Issue ? Can I work on it ?

**Comment by SunilMohanAdapa** [comment]
On 07/15/2016 04:33 PM, Hemanth Kumar Veeranki wrote:
> I want to work on this Issue ? Can I work on it ?

Please go ahead and work on it.

-- 
Sunil

**Comment by harry-7** [comment]
I am including last 100 lines of the log for now. What should be regex that I need to add to urls.py for this view?

**Comment by SunilMohanAdapa** [comment]
You can have the URL as /help/status-logs (better suggestions welcome).  This URL will be linked to from the 500.html template.  The URL regex for the page will page ^/help/status-logs$.  Or are you taking of something else?

**Comment by harry-7** [comment]
My doubt was that since this page should serve as landing page for 500 error. This should be redirected to the particular url for which the user will be redirected when he encounters a 500 error. Is there any such url ?

**Comment by SunilMohanAdapa** [comment]
I don't think a redirect should happen.  The current 500 error page will remain.  It will contact a link to a new page that the user will have to click.  That new page will contain the logs messages for user to take and report.

**Comment by SunilMohanAdapa** [comment]
At least, this is how I understand @fonfon intension. I think it is a better approach compared to redirection.

**Comment by harry-7** [comment]
Yes this is better. And so these views should be created in help module right ? and add the link in 500.html template ? That is what should be done right ?

**Comment by SunilMohanAdapa** [comment]
Yes.

**Comment by fonfon** [comment]
Yes, the link to the log-page is better than a redirection, you are on the right track :)

**Comment by jvalleroy** [comment]
FIxed in #520.
