### ISSUE TITLE
Drop PackageKit dependency

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#456]
We are currently facing a lot of problems with PackageKit:

- Each PackageKit operation would leak a file descriptor (no longer a major issue after new setup mechanism).
- We see problems with refreshing cache (perhaps more than apt would ever have).
- We see problems with network being offline after installing on Debian due to network manager not being used even for a single network connection. (can be corrected by adding an option not to use network manager).
- Problem running properly in chroot during setup (already fixed by using apt-get directly).

On the overall, I say PackageKit is not working out as expected although it played a decent role before the setup module. It is not providing us a lot other than privilege separation with polkit (not implemented yet), fine progress indication (can do without or get from apt with effort) and distribution abstraction (already heavily Debian specific).

I propose removing PackageKit and implementing package installation using apt. This must be implemented as a Plinth action which allows only specific actions on specific packages. We can revisit PackageKit later in future as need arises.

**Comment by jvalleroy** [comment]
Fixed in #493.
