### ISSUE TITLE
Improve PageKite

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#46]
Basic module that can setup pagekite now exists. Limitations are that only HTTP and SSH services are supported. It only supports pagekite.net account. Explore using other FreedomBoxes as frontend servers. Consider migrating the pagekite action script to use augeas (or so) instead of directly modifying the configuration files.

**Comment by fonfon** [comment]
I'm currently working on pagekite and have two questions:

a) If I put the pagekite lens (pagekite.aug) into `data/usr/share/augeas/lenses`, will it be copied to `data/usr/share/augeas/lenses/pagekite.aug` during the installation/setup?
b) I'll provide three default checkboxes to activate HTTP/HTTPS/SSH, and create a form to add custom services. Does anybody want more predefined service than these?

**Comment by SunilMohanAdapa** [comment]
On Wednesday 07 January 2015 07:57 PM, fonfon wrote:
> I'm currently working on pagekite and have two questions:
> 
> a) If I put the pagekite lens (pagekite.aug) into
> `data/usr/share/augeas/lenses`, will it be copied to
> `data/usr/share/augeas/lenses/pagekite.aug` during the
> installation/setup?

You will need to add that file to the data_files list in setup.py.

> 
> b) I'll provide three default checkboxes to activate HTTP/HTTPS/SSH,
> and create a form to add custom services. Does anybody want more
> predefined service than these?

We need to check what other services Pagekite can support (not sure if
there are many).   If any of them are important we can include those.

-- 
Sunil
