### ISSUE TITLE
Error "packages not found None" while installing owncloud

### ISSUE THREAD

**Issue by stueja** [freedombox/Plinth#462]
I just wanted to install owncloud via the web interface.
While doing so, I was trying to get plinth's version number. "man plinth" was not working, and plinth --help spawned a (new?) plinth process which I exited with ctrl-c.
The owncloud setup ran forever, obviously without doing anything.
I used the web interface to reboot and went back to owncloud installation.
Row "owncloud" only shows "owncloud" in the package column, and nothing in the summary column. postgresql and php5-pgsql have their names in the packet column and descriptions in the summary column.
When I now click on "Install", freedombox will start to install and, after a couple seconds (~30) come back with `Error instaling packages: packages not found None`
How can I install owncloud?

**Comment by SunilMohanAdapa** [comment]
Unfortunately, ownCloud has been removed from Debian and FreedomBox project can't manage it.  So, we have decided to look for alternatives in FreedomBox instead.  After merge of PR #458, Plinth will now not show ownCloud menu item for new users and show warning to earlier users that they will have to manage ownCloud manually or migrate.

**Comment by SunilMohanAdapa** [comment]
I have closed this as the above PR will take care of addressing the error.  We are yet to make release with that fix and there is not much we can do. Please feel free to reopen the issue if you wish to discuss anything further.

**Comment by stueja** [comment]
Oh, that's a pity. However, searching the web, I found that owncloud was removed due to security issues. So it seems indeed better to leave it out of freedombox. Leave that issue here closed.
I am sure you know that, but maybe there is an alternative here: https://prism-break.org/en/all/#file-storage-sync
