### ISSUE TITLE
Support Tahoe-LAFS

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#47]
> Support Tahoe-LAFS

**Comment by jvalleroy** [comment]
I think this is blocked by: https://www.tahoe-lafs.org/trac/tahoe-lafs/ticket/1436
We need relative paths in the web UI so we can serve it at /tahoe (with LDAP access control).

**Comment by jvalleroy** [comment]
Tahoe-LAFS module added in #791.
