### ISSUE TITLE
plinth --setup could take a list of modules to setup

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#473]
```plinth --setup [module1...]``` would setup both the essential modules, and the non-essential modules listed.

**Comment by jvalleroy** [comment]
Some examples where this might be useful:
- FreedomBox blends like Danube edition could specify additional modules to be setup by default.
- We could provide tasksel tasks that setup some module combinations to achieve certain tasks.

**Comment by SunilMohanAdapa** [comment]
Yes, we could do this.  When a list of modules is given, setup only those modules and when the list is not given, setup all essential modules.

**Comment by harry-7** [comment]
@jvalleroy  I would like to work on this. Can I change --setup argument to setup subparser [here](https://github.com/freedombox/Plinth/blob/master/plinth/__main__.py#L55) and add a subargument ?

**Comment by SunilMohanAdapa** [comment]
On 07/30/2016 03:09 PM, Hemanth Kumar Veeranki wrote:
> an I change --setup argument to setup subparser here
> <https://github.com/freedombox/Plinth/blob/master/plinth/__main__.py#L55> and
> add a subargument ?

That sounds good.  Please make sure to keep backward compatibility.
Running --setup without arguments to lead to all essential applications
getting installed just like before

-- 
Sunil

**Comment by harry-7** [comment]
@SunilMohanAdapa  To do that I must add a additional arugument called modules usage will be like
plinth --setup will load all modules where as
plinth --setup --modules [module1 module2...] will install module1 module2 etc.
Is that fine ?

**Comment by SunilMohanAdapa** [comment]
On 07/30/2016 03:31 PM, Hemanth Kumar Veeranki wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa> To do that I must
> add a additional arugument called modules usage will be like
> plinth --setup will load all modules where as
> plinth --setup --modules [module1 module2...] will install module1
> module2 etc.
> Is that fine ?

Writing parameter nargs='*' for the --setup argument should allow zero
or more arguments to accompany --setup.

-- 
Sunil

**Comment by harry-7** [comment]
@SunilMohanAdapa  Yes Found out that added it and created a pull request.

**Comment by SunilMohanAdapa** [comment]
Fixed in #535.
