### ISSUE TITLE
Install recommended packages together with ikiwiki

### ISSUE THREAD

**Issue by Diet-mar** [freedombox/Plinth#485]
I suggest to install together with ikiwiki the following recommends:
- libimage-magick-perl: needed for the img plugin, very common for wikis
- xapian-omega, libsearch-xapian-perl, libdigest-sha-perl and libhtml-scrubber-perl: needed for the search plugin

**Comment by nikhilrayaprolu** [comment]
I would like to take up this issue.is it sufficient to add these packages to list of managed_packages list in ikiwiki's init.py

**Comment by jvalleroy** [comment]
@nikhilrayaprolu Yes, that would be sufficient.

We can also remove the extra packages that are listed there now (besides ikiwiki). Because they are Recommends for the ikiwiki package, they are now installed by default.

**Comment by nikhilrayaprolu** [comment]
'gcc', 'libc6-dev', 'libtimedate-perl','libcgi-formbuilder-perl', 'libcgi-session-perl','libxml-writer-perl'
these are actually the present dependencies listed over in ikiwiki init.py.with the present dependencies plus xapian-omega, libsearch-xapian-perl, and libhtml-scrubber-perl are listed in dependencies of ikiwiki in debian packages list at https://packages.debian.org/stretch/ikiwiki  .But some of them are marked as suggested and some as dependencies.So does apt download all related packages irrespective of what their level of dependency(suggested recommended etc) might be?
If it is so then it is enough to list the dependecies as managed_packages = ['ikiwiki','libdigest-sha-perl']

**Comment by nikhilrayaprolu** [comment]
finally got this list from "apt-cache showpkg ikiwiki"
Dependencies: 
3.20160509 - libhtml-parser-perl (0 (null)) libhtml-scrubber-perl (0 (null)) libhtml-template-perl (0 (null)) libjson-perl (0 (null)) libtext-markdown-discount-perl (0 (null)) liburi-perl (2 1.36) libyaml-libyaml-perl (0 (null)) perl (0 (null)) ikiwiki-plugin-table (0 (null)) gcc (16 (null)) c-compiler (0 (null)) git (18 1:1.7) git-core (18 1:1.5.0) subversion (16 (null)) tla (16 (null)) bzr (18 0.91) mercurial (16 (null)) monotone (18 0.38) darcs (0 (null)) libauthen-passphrase-perl (0 (null)) libc6-dev (16 (null)) libc-dev (0 (null)) libcgi-formbuilder-perl (2 3.05) libcgi-pm-perl (0 (null)) libcgi-session-perl (2 4.14-1) libcrypt-ssleay-perl (0 (null)) libgravatar-url-perl (0 (null)) liblwpx-paranoidagent-perl (0 (null)) libmail-sendmail-perl (0 (null)) libnet-openid-consumer-perl (0 (null)) librpc-xml-perl (0 (null)) libterm-readline-gnu-perl (0 (null)) libtimedate-perl (0 (null)) libxml-simple-perl (0 (null)) dvipng (0 (null)) file (0 (null)) gettext (0 (null)) ghostscript (0 (null)) graphviz (0 (null)) libfile-mimeinfo-perl (0 (null)) libhighlight-perl (0 (null)) libhtml-tree-perl (0 (null)) libimage-magick-perl (16 (null)) perlmagick (0 (null)) liblocale-gettext-perl (2 1.05-1) libmagickcore-extra (0 (null)) libmailtools-perl (0 (null)) libnet-amazon-s3-perl (0 (null)) libnet-inet6glue-perl (0 (null)) libsearch-xapian-perl (0 (null)) libsort-naturally-perl (0 (null)) libsparkline-php (0 (null)) libtext-csv-perl (0 (null)) libtext-multimarkdown-perl (0 (null)) libtext-textile-perl (0 (null)) libtext-typography-perl (0 (null)) libtext-wikicreole-perl (0 (null)) libtext-wikiformat-perl (0 (null)) libxml-feed-perl (0 (null)) libxml-writer-perl (0 (null)) po4a (2 0.35-1) polygen (0 (null)) python (0 (null)) python-docutils (0 (null)) texlive (0 (null)) tidy (0 (null)) viewvc (16 (null)) gitweb (16 (null)) viewcvs (0 (null)) xapian-omega (2 1.0.5) ikiwiki-plugin-table (0 (null)) 
so  it is enough to list the dependency as managed_packages = ['ikiwiki','libdigest-sha-perl']

**Comment by jvalleroy** [comment]
@nikhilrayaprolu Currently we use apt-get to install packages, with default settings. So it will installed Depends and Recommends, but not Suggests. So for now, we can specify ikiwiki + suggested packages that we want.

**Comment by jvalleroy** [comment]
Fixed in #523.
