### ISSUE TITLE
Plinth should not allow creation of a "plinth" user

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#491]
this also needs to be indicated along with other username restrictions.
this also needs to apply to renaming existing users.

Reported by: @mray

**Comment by mray** [comment]
nitpick: the title misses "user" probably making a search for user related bugs harder.

**Comment by SunilMohanAdapa** [comment]
I've updated the subject line.  I must have missed it during copy/paste.  Thanks for correction.

**Comment by SunilMohanAdapa** [comment]
This should now be fixed with #516 which does not allow usernames that exist in the system and reserved usernames.
