### ISSUE TITLE
Certificate unusable

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#494]
It dawned on me that some certificate issues might be the reason Thunderbird works fine, but DavDroid on my phone does not work.
So I researched how to get that cert into my phone. I exported the self-signed certificate vie firefox from the website into a "localhost" file and copied it onto the SD-card of my phone. That didn't help, and as far as I can tell it didn't even work since it does not get listed in the user imported certificate list. (it is totally empty).

So i thought maybe i'm not doing this right to do this manually and I downloaded CAdroid to do the task form me, but it tells me
> CN=localhost - The certificate chain doesn't contain a valid certificate for the hostname in the URL. Use the correct host name or change the corresponding certificate's subject.

Sound to me as if FreedomBox creates kind of "useless" certificates.

*Sidenote if certificate importing is a necessary step to get it running on mobile phones we MUST address this on FreedomBoxes side: we can't expect people to 1. find out about it 2. take care of it!*

**Comment by mray** [comment]
After feedback from @SunilMohanAdapa I know that there practically is NO certificate in place to access freedombox from ouside. Maybe it is a lack of understanding, but to me this seems like setting things up for failure. How can we see ourselves as a secure "cloud" replacement and make https mandatory, but the key services will fail due to missing certs?

I think there needs *at least* to be a mention of this, if not there needs to be an automatic and loud warning after setting up dyndns without certificate. Both, the DynDNS app and the FreedomBox config tab should feature a certificate status next to the domain field either indicating a good certificate, an invitation to create one or an informative warning.

Incidentally obtaining a lets's encrypt certificate isn't [that easy either](https://github.com/freedombox/Plinth/issues/495). :(

**Comment by SunilMohanAdapa** [comment]
On 06/10/2016 01:11 PM, mray wrote:
> After feedback from @SunilMohanAdapa
> <https://github.com/SunilMohanAdapa> I know that there practically is NO
> certificate in place to access freedombox from ouside. Maybe it is a
> lack of understanding, but to me this seems like setting things up for
> failure. How can we see ourselves as a secure "cloud" replacement and
> make https mandatory, but the key services will fail due to missing certs?
> 
> I think there needs /at least/ to be a mention of this, if not there
> needs to be an automatic and loud warning after setting up dyndns
> without certificate. Both, the DynDNS app and the FreedomBox config tab
> should feature a certificate status next to the domain field either
> indicating a good certificate, an invitation to create one or an
> informative warning.

We should certainly improve the UI to indicate to the user that
certificate needs to be obtained.

To indicate right next to the domain in DynDNS app and in FreedomBox
config seems like neat idea.  We can also explore other UI improvements
to fix the situation.

-- 
Sunil

**Comment by mray** [comment]
I now seem to have successfully obtained a certificate through the let's Encrypt app, but still have no luck detecting any CalDAV or CardDAV services through DavDroid.

**Comment by SunilMohanAdapa** [comment]
Since the original problem with lets encrypt is solved, I believe we can close this issue.  Please feel free to reopen if more discussion is necessary.

If the issue with CalDAV/CardDAV still exists, please create a separate issue with it.
