### ISSUE TITLE
Narrow container layout

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#498]
Having a 100% wide layout breaks at large screens as you can see in ym screenshot
Boostrap offers to use `class="container"` instead of `class="container-fluid"` in [its documentation](https://getbootstrap.com/css/#overview-container). That onyl addresses the body, the header would need to shrink accordingly.

**this is no fun to read:**
![toolong](https://cloud.githubusercontent.com/assets/164785/15991182/661720e4-30ab-11e6-90d8-62b8abcb3129.png)

**Comment by SunilMohanAdapa** [comment]
@mray , would you please check the output of the proposed patch #586 is as you imagined?

**Comment by mray** [comment]
Yes, that would fix the width issue.
