### ISSUE TITLE
Tor: Add option to circumvent censorship

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#512]
Currently we are helping others circumvent censorship by enabling Tor bridge relays. However, if FreedomBox's Internet connection itself is being censored, we can't use other bridge relays to circumvent censorship.

Add an option to circumvent censorship:
- Provide a multi-line input box to collect bridge relay information just like in Tor browser bundle.
- Description to this field should point to bridges.torproject.org for people get information about bridges.  Users will copy the information there and paste into the input box.
- The allowed format of this box should be the same as provided by bridges.torproject.org.
- Then for each line the input add a "Bridge [transport] IP:ORPort [fingerprint]" line in the configuration and restart Tor.

**Comment by jvalleroy** [comment]
Fixed in #512.
