### ISSUE TITLE
Grouping Applications

### ISSUE THREAD

**Issue by Diet-mar** [freedombox/Plinth#537]
I would like to suggest to group similar and alternate applications in Plinth. The idea is to make on one side the alternatives (e.g. Pagekite, DynDNS)  clear to the user and on the other side to provide a structure because the number of applications is increasing.

**Settings**
- Certificates (Let's Encrypt)
- Configure
- Date & Time
- Diagnostics
  - Name Services
  - Firewall
- Monkeysphere
- Networks
- Power
- Public Visibility 
  - PageKite
  - Dynamic DNS Client
- Service Discovery
- (move under Networks?)
- Software Upgrades
- Users and Groups

**Apps**
- Anonymity Network (Tor)
- Bit Torrent
  - BitTorrent (Transmission)
  - BitTorrent Web Client (Deluge)
- Block Sandbox (Minetest)
- Cloud
  - Bookmarks (Shaarli) – temporarily unavailable
  - Calendar and Addressbook (Radicale)
  - (placeholder for Owncloud equivalent)
- Communication 
  - (alternatively, call this „Chat“ and leave Roundcube separate)
  - Chat Server (XMPP)
  - IRC Client (Quassel)
  - Email Client (Roundcube)
- News Feed Reader (Tiny Tiny RSS)
- Virtual Private Network (OpenVPN)
- Voice over IP
  - Voice Chat (Mumble)
  - SIP Server (repro)
- Web Proxy (Privoxy)
- Wiki and Blog (ikiwiki)

the simplest way to implement this could be to show/hide the sub-topics together with the description with click or mouse-over.

**Comment by jvalleroy** [comment]
@Diet-mar Could you please check #511 and comment on it (whether it looks like a step in the right direction, or what it might be missing)?

**Comment by Diet-mar** [comment]
@jvalleroy I did not see that work before, it's the same idea. Let's continue discussion there and close this.

**Comment by SunilMohanAdapa** [comment]
We are moving towards @mray 's comprehensive card based design. That design does not have groups but specifies a 'short description' in the card separating it from the name.  Please comment/improve that design.  I believe we should close this issue, please feel free to reopen it for further discussion.
