### ISSUE TITLE
Plinth front page for visitors 

### ISSUE THREAD

**Issue by Diet-mar** [freedombox/Plinth#540]
During the last call we discussed a Plinth front page for visitors. I started a brainstorming about this idea:

- Show a general introduction to the FreedomBox concept. This should be identical to the intro in the wiki or freedombox.org
- list and link to the public services installed on that box, such as owncloud, wikis and blogs, e-mail client, Plinth ...

This page could be fixed, but I like better the idea to have the possibility to modify it. So maybe pre-installing ikiwiki with the front page pre-generated (ups, logical flaw, at the time of generation no services is installed) but editable.

**Comment by SunilMohanAdapa** [comment]
This is very important and urgent thing to do.

**Comment by Diet-mar** [comment]
My idea of the front page is that it informs visitors about where they are (and thus does advertising) and also provides a quick entrance to its users.
So the content could be like:

"
Welcome to FreedomBox

FreedomBox is a 100% free software self-hosting web server to deploy social applications on small machines. It provides online communication tools respecting your privacy and data ownership. You can use FreedomBox at home to replace services provided by third-parties mining your life and using your content. Thanks to a very friendly interface, you will be able to deploy on demand applications focusing on confidentiality such as file sharing, shared calendaring, instant messaging, secure voice conference calling, blog and wiki. FreedomBox is a free software stack, a subset of the Debian universal operating system, that can be installed in many flavors of inexpensive and power-efficient Open Source hardware, called single board computers (SBC). Once installed on the hardware of your choice, the simplicity of setting up and operating a FreedomBox is similar to that of a smart phone. 

More info about FreedomBox is available at freedombox.org, the freedomboxfoundation.org and for support and collaboration at wiki.debian.org/FreedomBox.

On this device, the following services are available:
- wiki1
- wikiN
- blog1
- blogN
- Email Client (requires log-in)
- Your own cloud (requires log-in)
- Configuration (requires log-in) <- this links to Plinth
:
"

The introductory text is copied from the wiki, here it might be too long, so there is room for improvement. 
In the top-right there could also be the logo and a picture of our favorite box.
Style should be the same as on freedombox.org.

**Comment by jvalleroy** [comment]
A front page was added in #575, so I think this can be closed. Please re-open if needed.

**Comment by SunilMohanAdapa** [comment]
@Diet-mar , would you please look the screenshots in #575 and comment on it?

@jvalleroy , @Diet-mar We need to improve the frontpage to make it more appealing and function.  Internally, code structure could be better too, I believe.  Will post ideas as they come by.
