### ISSUE TITLE
Support LibreJS

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#543]
Currently, when LibreJS is enabled, it blocks javascript loaded from a plinth instance.

Since all of the JS used by Plinth is free software, we should be able to add licensing information so that the scripts won't be blocked. There is a guide on how to add license info in a way that LibreJS can recognize:
https://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by 500swapnil** [comment]
I would like to help with this one.

**Comment by SunilMohanAdapa** [comment]
@500swapnil , essentially we would like the librejs tool to automatically recognize that Plinth is using Free Software Javascript. In order for this to happen, we need to explicitly provide information to librejs.  There are many ways of doing this from a separate license file to inline markers for librejs to read.  Please investigate and compare the various ways available for us to work with librejs.  Then we shall agree on a method and you can proceed with its implementation (should be straight forward).

**Comment by 500swapnil** [comment]
Hey. Sorry for the delay. I think we could use JavaScript web labels method to work with librejs. It's the easiest and most efficient way to add license information. We will need to create an html file with a JavaScript web labels table.

**Comment by jvalleroy** [comment]
@500swapnil That sounds fine to me. I think the JS web labels page can go in our static folder, and the base template can be modified to link to it.

**Comment by 500swapnil** [comment]
Okay that'd be great!

**Comment by 500swapnil** [comment]
@jvalleroy Can you tell which all versions of JavaScript we have used so I can make the page?

**Comment by 500swapnil** [comment]
I have opened a PR #688. Please have a look!

**Comment by jvalleroy** [comment]
Partially supported with #688. I'll open a new issue with remaining problems to be solved.
