### ISSUE TITLE
Django 1.10 menu issue

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#544]
After upgrading python3-django to 1.10-2 (from unstable), the menus are no longer displayed in Plinth.

**Comment by harry-7** [comment]
@jvalleroy this is because the submenu variable [here](https://github.com/freedombox/Plinth/blob/master/plinth/templates/base.html#L160) is becoming None in the template. Any ideas why ?

**Comment by jvalleroy** [comment]
Fixed in #546 and #547.
