### ISSUE TITLE
Add service delivery (connector) UI support

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#55]
> Users should be able to configure the system they want to serve a service over (PageKite, Tor, Public IP, etc.).

**Comment by jvalleroy** [comment]
Should this be part of the Name Services module?

We could add drop-down menus to the enabled/disabled buttons in the table, so it's easy to select which services are enabled for each domain.

**Comment by SunilMohanAdapa** [comment]
Since we want to keep FreedomBox UI clean, minimal and automated, I suggest that we don't implement this feature unless we see a major driving use case for it.  To that effect, we can close this issue.

Currently, we have every service divided automatically (no user intervention) as public (external and internal) and private (internal).  Using this we are exposing services on all domains or on none of them.  This is a simple enough concept for users to understand.  When the need arises, we can let users select if they want to change some external services to internal and vice versa.  Allowing services on particular domains is more in-depth customization.

**Comment by jvalleroy** [comment]
Ok, let's close this for now.
