### ISSUE TITLE
xmpp: Use letsencrypt certificate, when available

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#565]
Use letsencrypt certificate for both c2s and s2s connections.

**Comment by JoKeyser** [comment]
I'm getting seriously interested in tackling this, if it's not currently being solved. I think PR #579 was a good start; I would start from there.
Importantly, there needs to be a renew-hook in place to keep up with renewed certificates. My plan would be to port [certbot's renew example script](https://github.com/certbot/certbot/blob/master/docs/using.rst#renewing-certificates) to Python, as Plinth action for the ejabberd module. This then gets called periodically as a renew-hook. I still have to look up how renewals are currently triggered - is this a cron job?
Also, it's important not to do this for every available certificate, just for the one currently in use, probably sufficiently defined by the current domain name.

**Comment by JoKeyser** [comment]
This should be solved by #919 , at least it provides the option to enable it manually (once).

**Comment by mray** [comment]
Is this connected to my jabber contacts complaining about SASL mechanism not being there and authentification failure?

**Comment by JoKeyser** [comment]
@mray it *may* be *indirectly* connected, in that it will reduce complaints of clients and servers about self-signed certificates. But PR #919 cannot have caused the problem you report in #1058, if that's what you're asking. (The PR isn't yet in the next Debian package, and admins have to activate the option.)

**Comment by JoKeyser** [comment]
This will likely be overhauled once it's clarified in #1125 how to implement this better.
