### ISSUE TITLE
letsencrypt: Misleading diagnostic message when no name services configured

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#567]
When no name services are configured (including domain, pagekite, tor HS), when running the diagnostics in the letsencrypt module, it shows the diagnostics results page with: "This module does not support diagnostics".

Perhaps we should not display the Run Diagnostics button on this page, when no name services are configured.

**Comment by Pk13055** [comment]
Hi, I'm a newbie to contributing to OS, and was wondering if you could tell me where I could find the button config; in the letsencrypt module or the diagnostics module?

**Comment by mridulnagpal** [comment]
https://github.com/freedombox/Plinth/pull/635
I have put up a PR regarding the issue

**Comment by jvalleroy** [comment]
Fixed in #641.
