### ISSUE TITLE
Restrict characters allowed in ikiwiki site name

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#574]
When creating a wiki with symbols in the name, it may silently fail to create the wiki, or fail to compile it.

Add form validation to the name field to restrict the allowed set of characters. At least alphanumeric characters and spaces seem to be ok.

**Comment by parthsuresh** [comment]
Hi, I'm a beginner to open source projects but have some experience with Python and Django and I'd really like to contribute more to this project. Can I start off by working on this issue?

**Comment by jvalleroy** [comment]
Hi @parthsuresh! Yes, you can work on this issue. Let me know if you have any questions or need some tips to get started.

**Comment by parthsuresh** [comment]
Thanks for responding @jvalleroy! I'd like to know if there is any IRC channel for this project where I could ask some questions. I'm a bit of a noob, so some of my questions may end up cluttering this ticket..

**Comment by jvalleroy** [comment]
@parthsuresh Yes, we are in #freedombox on OFTC.

**Comment by SunilMohanAdapa** [comment]
I am taking this task to demonstrate contirbutions to Free Software.

**Comment by jvalleroy** [comment]
Fixed in #611.
