### ISSUE TITLE
repro: Handle opening firewall port for RTP communication

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#590]
Currently, after configuring repro and connecting to via an Android/desktop application, VOIP calls fail due to RTP ports not being open. This is typically the range 16384 - 32767 of UDP ports but may vary from vendor to vendor.  Find the port range required for repro and open the ports in firewall as long as repro is open.

**Comment by jvalleroy** [comment]
Fixed in #613.
