### ISSUE TITLE
networks: Mesh configuration needs to disable IPv6

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#591]
Currently, after creating a Mesh network configuration as described in the manual https://wiki.debian.org/FreedomBox/Manual/Networks#Configuring_a_mesh_network . The first connection fails to establish.  This is because IPv6 configuration is failing and leading to connection being treated as failed.  After setting `ipv6.method` to `ignore` using nmtui or nmcli the connection succeeds.  Provide a way to set this from Plinth UI.

**Comment by jvalleroy** [comment]
Fixed in #610.
