### ISSUE TITLE
minetest improvements

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#606]
- [x] Add some basic configuration options such as max_users, enable_pvp, creative_mode, enable_damage.
- [X] Add minetest-mod-\* packages as dependencies for the module.

**Comment by jvalleroy** [comment]
To add some detail to this:
* Augeas' Php lens can be used to modify the configuration in /etc/minetest/minetest.conf.
* These are the packaged mods I found that can be installed with just the server (don't require the client):
  * minetest-mod-advspawning
  * minetest-mod-animalmaterials
  * minetest-mod-animals
  * minetest-mod-mesecons
  * minetest-mod-mobf-core
  * minetest-mod-mobf-trap
  * minetest-mod-moreblocks
  * minetest-mod-nether
  * minetest-mod-torches

**Comment by mridulnagpal** [comment]
@jvalleroy I want to work on this issue can you tell me how to proceed

**Comment by jvalleroy** [comment]
@mridulnagpal One task is to add a configuration form to the minetest page, where the user can set values for the options I mentioned. Then to actually change the configuration, you can use the Php lens from Augeas. As an example I was able to use this lens to configure repro:
https://github.com/freedombox/Plinth/pull/589/files#diff-3f2f4981582b4deb4dc5bb447ea6f6a8R181

The 2nd task is to just add the mod packages I listed to minetest's managed_packages list. We should test to make sure this doesn't pull in the minetest client though (should only depend on the server).

**Comment by mridulnagpal** [comment]
@jvalleroy How do we proceed on the next task?

**Comment by jvalleroy** [comment]
@mridulnagpal We will need to create an actions/minetest script. It can be similar to the other python scripts in that folder. It can have a parser named "configure" with arguments like "--max_players", "--enable_pvp", "--creative_mode", "--enable_damage". It should load Augeas, configured to use the Php lens with /etc/minetest/minetest.conf.

So the first step will be to get this action script working, so we can run commands like ```sudo ./actions/minetest --max_players 30 --creative_mode true``` and it will make the requested changes to the configuration, and restart the minetest server.

**Comment by jvalleroy** [comment]
Fixed in #686.
