### ISSUE TITLE
xmpp: Update Javascript XMPP Client to >= 3.0.0

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#608]
The current version of JSXC in FreedomBox/Plinth is 1.0.0 due to this version being available in Debian.  However, 3.0.0 is available with lot of improvements.  Update version in Debian and Plinth to >= 3.0.0.

**Comment by SunilMohanAdapa** [comment]
JSXC addition to Plinth is under review #607 .

**Comment by SunilMohanAdapa** [comment]
JSXC 3.0 is now available in Debian, we need to adopt our scripts to it: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812933

**Comment by jvalleroy** [comment]
Fixed in #665.
