### ISSUE TITLE
Create generic service frameworks

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#62]
> For example, provide a "vpn" command to client services that specifically need it so that we can swap out VPN backends at whim.  This would also be handy for defining functional dependencies between modules, for when one module needs to enable a feature in another module to function correctly.

**Comment by fonfon** [comment]
I do not understand what you exactly mean.
With 'command', do you refer to the action scripts? If yes, why are the action scripts not sufficient for swapping out backends? (except that they're right now named after the package name like 'openvpn')

**Comment by SunilMohanAdapa** [comment]
This TODO item was carried forward from earlier freedombox-todo lists at various places.

You are right that the action scripts are sufficient although there are subtle differences when comparing multiple services.

Also since started allowing multiple applications for same purpose like smart phones do, I believe this is a non-goal for us right now.

**Comment by SunilMohanAdapa** [comment]
We can close this item upon agreement.
