### ISSUE TITLE
Update screenshots on Wiki and README.md

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#621]
We have four screenshots on the page https://wiki.debian.org/FreedomBox/Plinth which somewhat outdated due to much cleaner design we follow.  Also ownCloud is no longer an application in FreedomBox.  Update these images with fresh screenshots and also edit the Plinth/README.md if necessary.

**Comment by sakshinagpal07** [comment]
I am new to github can anyone assist me for this bug??

**Comment by fonfon** [comment]
The first part is about improving the debian wiki page of FreedomBox at https://wiki.debian.org/FreedomBox/Plinth - it has nothing to do with github directly.
You'd have to register there to be able to edit the debian wiki. Plinth is the web administration frontend of FreedomBox. If you have it somewhere running make up-to-date screenshots and replace the outdated screenshots of the wiki page.

The second part is about this file: https://github.com/freedombox/Plinth/blob/master/README.md
This is the documentation showing up when you open https://github.com/freedombox/Plinth/
The screenshots are outdated too. Are you familiar with using git and github? If not then this is a good starting point: https://wiki.debian.org/FreedomBox/Contribute/Code

**Comment by mridulnagpal** [comment]
i want to be assigned to this issue

**Comment by jvalleroy** [comment]
Fixed in #630.
