### ISSUE TITLE
jsxc URL allows install/update of xmpp module without requiring login

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#623]
Just confirming this issue that was reported by DJ on the mailing list. I believe it only affects jsxc, because it is served at a url under the xmpp module.

**Comment by mridulnagpal** [comment]
@jvalleroy could you tell me more about the problem

**Comment by mridulnagpal** [comment]
@jvalleroy #653 Please check this PR once.

**Comment by jvalleroy** [comment]
@mridulnagpal Here's a test case to demonstrate the issue:
1. Start with a fresh vagrant image (vagrant up && vagrant provision).
2. Go to https://localhost:4430 and complete the first boot process.
3. Log out from Plinth.
4. Go to https://localhost:4430/plinth/apps/xmpp/jsxc/. Although you are not logged in, you can still install the xmpp module.
![plinth-jsxc-install](https://cloud.githubusercontent.com/assets/178876/20463950/1ee68234-af0c-11e6-9d91-ef9ce96be171.png)

**Comment by jvalleroy** [comment]
Fixed in #694.
