### ISSUE TITLE
Unable to setup vagrant and virtualbox installed both virtualbox and vagrant when i do vagrant up it asks for a vagrantfile. what do i do?

### ISSUE THREAD

**Issue by mridulnagpal** [freedombox/Plinth#626]

**Comment by jvalleroy** [comment]
The Vagrantfile is provided in this repo (https://github.com/freedombox/Plinth/blob/master/Vagrantfile). Are you running "vagrant up" inside the plinth project folder?

**Comment by mridulnagpal** [comment]
Yes i am 
and it shows these 2 errors
 *The following settings shouldn't exist: post_up_message
* The box 'freedombox/plinth-dev' could not be found.

**Comment by jvalleroy** [comment]
@mridulnagpal Which version of vagrant are you using?

If needed, you can edit the Vagrantfile and comment out or remove lines 28-33. Maybe that will work.

**Comment by mridulnagpal** [comment]
I removed the lines 28-33 
now when i vagrant up it shows one error 
 The box 'freedombox/plinth-dev' could not be found.

**Comment by mridulnagpal** [comment]
version for vagrant is 1.4.3
