### ISSUE TITLE
Issue regarding virtualbox setting up of Plinth

### ISSUE THREAD

**Issue by mridulnagpal** [freedombox/Plinth#629]
I downloaded virtualbox and vagrant and did vagrant up and am getting this error
![screenshot from 2016-10-20 22 29 11](https://cloud.githubusercontent.com/assets/22350740/19569854/dfaa79a4-9714-11e6-9f69-85545c509bc6.png)

**Comment by jvalleroy** [comment]
@mridulnagpal I think you just need the vagrant-virtualbox plugin. Try running this command:
```
vagrant plugin install virtualbox
```
