### ISSUE TITLE
Make Radicale easier usable

### ISSUE THREAD

**Issue by fonfon** [freedombox/Plinth#644]
Right now it's a bit tedious to actually use the Radicale service. Which URLs do I have to use, how can I create a calendar or address book, which calendars/address books do exist on the server?

It would be helpful to display such information on the radicale plinth page, or even allow deleting/creating calendars and address books there.

**Comment by JoKeyser** [comment]
Hi @fonfon , I'm trying to clean up the issues around radicale, and thus close this one (feel free to reopen if you disagree). Here my 2 reasons:

1. As you say in #773, your first point about explaining the usage is already advanced there.
2. Your second point about a web-interface will be addressed by radicale 2 itself, see http://radicale.org/configuration/#web. The Debian maintainers are already on the case, see https://packages.debian.org/experimental/radicale. So there seems no necessary effort from us in Plinth, except adding a link in the future :).
