### ISSUE TITLE
ttrss: Show status block

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#650]
I saw an issue where my feeds stopped updating for a while. It turned out that the tt-rss feed update service had stopped running for some reason.

The status block is currently disabled for ttrss's ServiceView: https://github.com/freedombox/Plinth/blob/master/plinth/modules/ttrss/urls.py#L33

I suggest that we enable the status block, to make it clear if the update service is running.

**Comment by Pk13055** [comment]
I would like to work on this issue.

**Comment by Pk13055** [comment]
show_status_block has been changed from 'False' to 'True'.

**Comment by Pk13055** [comment]
show_status_block has been changed from 'False' to 'True'.

**Comment by jvalleroy** [comment]
Fixed in #651.
