### ISSUE TITLE
frontpage: Configure links are broken

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#669]
Looks like the links are missing the /plinth prefix.

**Comment by jvalleroy** [comment]
Strangely, the links are correct for me now (after running "vagrant provision" again).

**Comment by mridulnagpal** [comment]
@jvalleroy Seems to work fine by me as well.

**Comment by jvalleroy** [comment]
Yep, seems to just be an artifact of running development plinth on top of 0.11 vagrant install. I'll close this for now.

**Comment by jvalleroy** [comment]
Actually I'm seeing this issue again, but very strange, some of the links are correct (with /plinth prefix) and some of them are missing it.

We use django.urls.reverse to get these URLs. I'm thinking we might need to use reverse_lazy instead. I'll do some testing and see if that affects it.

**Comment by jvalleroy** [comment]
Fixed in #674.
