### ISSUE TITLE
Consider using tor-instance-create

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#676]
Currently when the Tor module is setup, we make changes to /etc/tor/torrc. But since that file is owned by the tor debian package, this can cause issues during upgrade (conffile prompt).

The tor package includes a script called tor-instance-create, which sets up a new user and home directory with its own configuration file. So for example we can have a service named tor@plinth, and keep our configuration in /etc/tor/instances/plinth/torrc.

**Comment by mridulnagpal** [comment]
@jvalleroy So do we just change the TOR_CONFIG variable??

**Comment by jvalleroy** [comment]
@mridulnagpal That's part of it. Also during tor setup (https://github.com/freedombox/Plinth/blob/master/actions/tor#L69), we would need to stop and disable the default tor service, and run tor-instance-create. And update the name of the service wherever it's used.

This page has details about using the tor-instance-create script: http://manpages.org/tor-instance-create/8

**Comment by jvalleroy** [comment]
Fixed in #678.
