### ISSUE TITLE
List modules from command line

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#681]
We should be able to get the list of installed modules from the plinth command line. I'd suggest the following:
- plinth --list-modules --> Lists all modules.
- plinth --list-modules essential --> Lists essential modules only.
- plinth --list-modules optional --> Lists optional modules only.

This is to support https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847680.

**Comment by mridulnagpal** [comment]
@jvalleroy I'd like to give it a shot

**Comment by jvalleroy** [comment]
@mridulnagpal Ok! I think the only changes will be in ```plinth/__main__.py```.
- Add an argument to the parser: https://github.com/freedombox/Plinth/blob/master/plinth/__main__.py#L44
- Add a new function that prints the list for all, essential, or optional modules, and then exits.
- In main(), check the argument value, and if it's set, call the function.
- The modules can be accessed through module_loader.loaded_modules.

**Comment by jvalleroy** [comment]
Fixed in #682.
