### ISSUE TITLE
Add script to create new module

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#684]
When creating a new Plinth module, I usually copy a lot of code from other modules, and then modify it as needed. It would be nice to have a script that you can run like ```./create-module <name>``` that will create all the boilerplate that is common for modules.

**Comment by nikhilrayaprolu** [comment]
@jvalleroy is there any boiler plate for apps till now?
I think writing a script is easier if we do have a boiler plate.
just generating  a copy of the boilerplate and placing the name of module whereever required may do the trick.

**Comment by jvalleroy** [comment]
@nikhilrayaprolu Not exactly boiler plate, but we have instructions on the wiki that should cover the basic requirements of a module:
https://wiki.debian.org/FreedomBox/Manual/Developer

You could also pick a simple module like quassel or mumble. Those are just basic service modules, without much customization, so they should be close to a boiler plate.

**Comment by nikhilrayaprolu** [comment]
@jvalleroy I am making a boilerplate initially , then generate them with  commands.

**Comment by nikhilrayaprolu** [comment]
@jvalleroy can you look at  boilerplate at https://github.com/nikhilrayaprolu/plinthmodule-boilerplate and make changes which are required.

**Comment by nikhilrayaprolu** [comment]
@jvalleroy As the boilerplate is almost complete now I would like to discuss the design for solving this issue.
Initially I will be using this boilerplate templates as a blue print.In a python script , I will be asking the user for the module_name,module_title,module_description.
secondly the tags that need to be replaced in the blueprints will be named as `{{module_name}},{{module_title}},{{module_description}}`
now here there are two approaches to follow:-

1. above blueprint files will be copied to required new module folder, and then are parsed to replace the tags with original module name(using a python script).
2. or the blueprints are parsed in the python ,respective tags which are to be replaced are replaced and then  the final output will be copied to the required folder.

which approach would be a better one?or any other approach you would like to suggest?

**Comment by jvalleroy** [comment]
@nikhilrayaprolu Ah did you see the comments I made at https://github.com/nikhilrayaprolu/plinthmodule-boilerplate/issues/1?

I think the 2nd approach will be a bit simpler. But either one is probably ok.

**Comment by jvalleroy** [comment]
This is done in a separate repository:
https://github.com/freedombox/plinth-app-bootstrapper
