### ISSUE TITLE
User permissions based on apps

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#690]
I think it would be nice to be able to assign/withdraw access rights to all apps on a per-user basis.
Currently there are only groups like "admin" and "wiki".

**Comment by fonfon** [comment]
For clarification, you mean to be able to define for each app whether each existing user is allowed to login?
Or just define one group whose members are allowed to login to each app?

**Comment by SunilMohanAdapa** [comment]
@fonfon , I believe @mray is talking about the result to the end user and not specifically talking about how it should be done.

Having one group per app (or per group of related apps such as 'email', 'xmpp') then assigning users to the group will let one have all the flexibility one needs.  We should not have the concept of user being assigned to application:
- It keeps the permissions system simple.
- Existing LDAP schema can store information about user belonging to a group but not whether a user is allowed to access an application.
- It is also very easy to write Apache configuration files allowing users to a particular app by requiring them to belong to a group.
- In the UI we can show it as if the user has permission for app when a user belongs to a group.

**Comment by mray** [comment]
Right, I just want to create users independently on what they can access. This certainly raises what the default setting for enabeling new apps is. Enable by default? disable by default? Maybe ask after adding new apps?

I just want to be able to transparently limit the rights of users. Preferably with a conservative default where no access is granted unless decided otherwise.
