### ISSUE TITLE
XMPP Client + Server one app?

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#692]
It looks like the JSXC (client) app gets automatically installed by installing the ejabberd XMPP server app.
It is strange to not know any details like the names of the software *and* that two apps get installed, even when I only need one component.

Plinth should list two different apps and use their names instead of a generic description.

**Comment by nikhilrayaprolu** [comment]
@mray It looks like this same issue matches with #254

**Comment by fonfon** [comment]
Let's continue on #254
