### ISSUE TITLE
Make Plinth the front page for FreedomBox

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#71]
Currently, if someone visits their FreedomBox as http://freedombox/ they are shown jwchat interface.  This has the following problems:
- JWChat is only a small part of FreedomBox
- Other services available such as /owncloud and not easy to discover
- Even Plinth which should help a user discover various services is hidden under /plinth

I propose that Plinth be the first entry point into all the FreedomBox services.  This can be implemented as the dashboard work being done by @fonfon in #20 (with improvements).  This approach has several advantages:
- FreedomBox gets a better looking front page
- Each service that is implemented in Plinth can choose to expose various interfaces properly
- Enabling and disabling services in Plinth will reflect changes properly in the front page.
- Plinth will be able to show the status and health of the FreedomBox and request user intervention.

**Comment by SunilMohanAdapa** [comment]
Simpler look has been implemented and freedombox-setup now redirects to Plinth.  Only issue remaining is to implement the dashboard in #20.  Since the work on that is being tracked there, I am closing this issue.

**Comment by SunilMohanAdapa** [comment]
#20 is a pull request that has been closed off.  Reopening this issue.

**Comment by jvalleroy** [comment]
A front page was added in #575, so I think this can be closed. Please re-open if needed.
