### ISSUE TITLE
Eliminate extra reboot after running freedombox-setup

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#711]
- [x] slapd: Some ideas for eliminating this extra setup step are in https://github.com/freedombox/Plinth/pull/709.
- [x] firewalld: Firewalld configuration can be done during setup. If the setup is happening inside a chroot environment, then firewalld-offline-cmd could be used instead of firewalld-cmd. Also most of the port opening done in this script are no long required due to the way modules are handled these days.
- [x] ssh-keys: When building images, make sure that pre-generated keys are removed. When installing FreedomBox on Debian, running setup/firstboot should not do anything. We can write a pre-execution hook for SSH server (using systemd) and create keys if they are not available.
- [x] apache2: When building images, make sure that pre-generated snake oil certificate is removed. When installing FreedomBox on Debian, running setup/firstboot should not do anything. We can write a pre-execution hook for Apache2 server (using systemd) and create snake oil certificate if it is not available.
- (Add ideas for eliminating other steps from first-run.)

**Comment by SunilMohanAdapa** [comment]
I have added ideas for some more scripts.  We can think of one for networking by trying to modify auto-configuring behaviour according to FreedomBox needs.

**Comment by JosephKiranBabu** [comment]
Can this be closed now?

**Comment by SunilMohanAdapa** [comment]
I think this is been completed.
