### ISSUE TITLE
jsxc: Broken links to JS/CSS files

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#712]
https://github.com/freedombox/Plinth/blob/master/static/jslicense.html
The xmpp module was removed, and so jsxc-plinth.js is now in the jsxc module. Need to update the links on this page.

**Comment by jvalleroy** [comment]
Also some links in the JSXC web client page template:
https://github.com/freedombox/Plinth/blob/master/plinth/modules/jsxc/templates/jsxc_launch.html#L59
Need to be switched from xmpp module to jsxc module.

**Comment by MarkoMackic** [comment]
Can I do it ?

**Comment by SunilMohanAdapa** [comment]
First part of the bug was fixed by @MarkoMackic in #717 . Second part is pending in #718 .

**Comment by SunilMohanAdapa** [comment]
#718 has been merged and that should fix this issue completely. Thanks to @MarkoMackic .
