### ISSUE TITLE
infinoted: Should have a line break in shortcut label on front page

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#720]
To match the other shortcuts and keep the height constant for even rows.

**Comment by MarkoMackic** [comment]
I'm planning to solve this today, can you be a bit more precise. How can I reproduce bug and what is a shorcut label

**Comment by jvalleroy** [comment]
@MarkoMackic If you check other apps on the frontpage, such as mumble, there's a newline character in its title. This is ignored on the normal app page, but is used on the frontpage.

To reproduce the bug, try enabling several apps that have front page shortcuts. (You may also need to maximize your browser window and zoom out the page.)

**Comment by jvalleroy** [comment]
The shortcut label is the text shown under the logo on the front page. It is taken from the module's ```title``` variable.
For infinoted: https://github.com/freedombox/Plinth/blob/master/plinth/modules/infinoted/__init__.py#L44
For mumble: https://github.com/freedombox/Plinth/blob/master/plinth/modules/mumble/__init__.py#L37

**Comment by MarkoMackic** [comment]
Cool, I'll fix it today

**Comment by MarkoMackic** [comment]
Haven't I fixed this in #725 ?

**Comment by jvalleroy** [comment]
Yep I missed this one, closing.
