### ISSUE TITLE
Problem setting dev environment

### ISSUE THREAD

**Issue by MarkoMackic** [freedombox/Plinth#723]
I read `HACKING` and wanted to install dev environment
My system is : `Ubuntu 16.04.1 LTS`
I installed vagrant and virtualbox
`vagrant is already the newest version (1.8.1+dfsg-1).`
`virtualbox is already the newest version (5.0.24-dfsg-0ubuntu1.16.04.1).`

and if I go `vagrant up` my machine boots to ssh (looking at gui) but at vagrant
it doesn't go further until `Cable connected` is marked manually in machine settings. 

When it starts copying files I can access the panel, but when everything is 
over, I can't access the panel ( 503 error)

**Comment by jvalleroy** [comment]
I think this is due to the xmpp module that was removed. But the vagrant provisioning doesn't handle these updates. Please try the following:
```
$ vagrant ssh
$ sudo rm /etc/plinth/modules-enabled/xmpp
$ sudo systemctl restart plinth
```
The issue will be fixed when we build and upload a new vagrant image with plinth v0.13.

**Comment by MarkoMackic** [comment]
Yeah, that solved it
