### ISSUE TITLE
vagrant: Force re-install of existing folders

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#724]
When "vagrant provision" is run, it uses "setup.py install" to install the latest development branch of Plinth in the vagrant box. However, "setup.py install" doesn't install over existing folders such as /usr/share/plinth, which contains actions and static files. This can lead to missing files when trying to test Plinth.

Investigate if we can force setup.py to overwrite the existing files.

**Comment by MarkoMackic** [comment]
How to test does it work, can I edit `setup.py` and run `vagrant provision` ?

**Comment by jvalleroy** [comment]
@MarkoMackic Yes, vagrant provision will run the provision script from Vagrantfile, which includes "setup.py install":
https://github.com/freedombox/Plinth/blob/master/Vagrantfile#L22

**Comment by jvalleroy** [comment]
Fixed in #725.
