### ISSUE TITLE
wiki recommendation link broken

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#727]
On the [wiki](https://wiki.debian.org/FreedomBox/QuestionsAndAnswers#Which_single_board_computer_.28SBC.29_do_you_recommend.3F) the last link to [APU / ALIX](http://www.pcengines.ch/order.php) is broken. not sure where it should link to instead.

**Comment by SunilMohanAdapa** [comment]
I updated it to the correct page now http://www.pcengines.ch/order.htm . Thank your for reporting.
