### ISSUE TITLE
Plinth login error

### ISSUE THREAD

**Issue by pranithkumar** [freedombox/Plinth#730]
500
This is an internal error and not something you caused or can fix. Please report the error on the bug tracker so we can fix it. Also, please attach the status log to the bug report.

**Comment by jvalleroy** [comment]
@pranithkumar The "status log" should link to a page with the actual log. Could you share that log (after removing any personal info)?

**Comment by pranithkumar** [comment]
It is a remote server and I am not able to access it through ssh even with the correct password.(Error:Permission denied)

**Comment by jvalleroy** [comment]
@pranithkumar On which page in Plinth did you get the 500 error? Is it reproducible?

**Comment by pranithkumar** [comment]
The problem is solved.There was no space left on the disk and therefore was not able to login to plinth.I logged into the server and expanded the disk space and the problem was solved.
