### ISSUE TITLE
Plinth service does not start on vagrant box

### ISSUE THREAD

**Issue by lispyclouds** [freedombox/Plinth#732]
Currently the vagrant box that is uploaded on Hashicorp Atlas cannot start the plinth service as the **/etc/plinth/modules-enabled/xmpp** file exists and if the latest code is run from the box the service start fails.

Solution is to remove the file and rebuild the vagrant box.

**Comment by jvalleroy** [comment]
We need to merge this pull request on freedom-maker:
https://github.com/freedombox/freedom-maker/pull/84
And then build and upload a new vagrant box.

**Comment by JoKeyser** [comment]
Seems solved now, so this issue can be closed?

**Comment by jvalleroy** [comment]
I think it is fixed, but please reopen if needed.
