### ISSUE TITLE
ejabberd just breaks

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#744]
I can't get my ejabberd instance running anymore.

1. I shut down FreedomBox to remove the SDcard from my raspi
2. I made a backup in form of a disk image copy
3. I reinserted the SDcard and rebooted
4. FreedomBox seems to run fine but jabber clients refuse to log in
5. Looking at plinth I see ejabberd isn't installed anymore.
6. As sometimes things *appear* to not be present I just try "installing" it again.
7. Error: 
```   Error installing application: Error during installation E: The repository 'tor+http://httpredir.debian.org/debian sid Release' does no longer have a Release file. ```

I have no idea what to do.

**Comment by mray** [comment]
Trying `sudo apt-get update` via ssh stops at 0% like this:
```0% [Connecting to SOCKS5h proxy (socks5h://localhost:9050)]```

**Comment by mray** [comment]
I tried disabeling tor since ```the tor+http``` part seemed strange to me.
The Tor app complained about needing an update, so I updated it and it says the same thing again:
```
 Error installing application: Error during installation E: The repository 'tor+http://httpredir.debian.org/debian sid Release' does no longer have a Release file. 
```

I want to chat again! :'(

**Comment by mray** [comment]
I now notice that the initial ssh command didn't stop but went on:

```
Ign:1 tor+http://httpredir.debian.org/debian sid InRelease 
Err:2 tor+http://httpredir.debian.org/debian sid Release   
  Read error - read (104: Connection reset by peer) Reading the greet back from SOCKS proxy socks5h://localhost:9050 failed [IP: ::1 9050]
Reading package lists... Done                              
E: The repository 'tor+http://httpredir.debian.org/debian sid Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by jvalleroy** [comment]
@mray For now, I think you will need to edit /etc/apt/sources.list, and remove the "tor+" part from each URL listed.

I created an issue #745 for providing a way to set the apt mirror in Plinth.

Regarding the Tor module upgrade, if we finish the tasks in #412, then module upgrades will be automatic, and at least we can notify the user if it fails.

I'm not sure about the other issues currently (ejabberd, and either the mirror or Tor not working).

**Comment by mray** [comment]
* I removed the "tor+" part and updated my sources.
* I then *installed* ejabberd again but it says it was not running  despite being enabled
* running diagnostics shows: 
![image](https://cloud.githubusercontent.com/assets/164785/23582140/18a16b7c-0124-11e7-95a5-921d8b136600.png)
* I restarted; now the app is installed, enabled *AND* running - but I still can't log in to my jabber accounts

My users are all there but is Single Sign On broken maybe?

**Comment by mray** [comment]
I can now use my jabber server as expected again. Not sure why though.
I disabled "Download software packages over Tor" in the tor module, waited and rebooted for a few times. Strange. I'd really like to know what caused that whole issue.
Anyhow, closing the issue again.
