### ISSUE TITLE
Add Debian badge

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#753]
Add badges for plinth package from https://badges.debian.net/ to readme.

**Comment by aksbuzz** [comment]
can i work on this issue?

**Comment by SunilMohanAdapa** [comment]
@aksbuzz , Please go ahead and take up the issue.

**Comment by sahithi-ihtihas** [comment]
Added Debian Testing , Unstable badges and created a pull request.

**Comment by SunilMohanAdapa** [comment]
Thank you both for the contribution.

**Comment by aksbuzz** [comment]
Thank you!. This was my first contribution.
