### ISSUE TITLE
Fix URL in INSTALL

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#764]
Reported by Augustine on the mailing list:
```
Turns out this one was really simple, but the INSTALL file should
be changed to:

Plinth UI should be accessible at http://localhost:8000/plinth

instead of what it says now: http://localhost:8000
```

**Comment by cllamb0** [comment]
Hi there! I just fixed the issue, here is the pull request:
https://github.com/freedombox/Plinth/pull/765
I'm really glad I was able to contribute!

**Comment by SunilMohanAdapa** [comment]
Fix is merged.  Closing.  Thank you for the contribution.
