### ISSUE TITLE
Activate unattended-upgrades

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#77]
As discussed in https://github.com/petterreinholdtsen/freedombox-setup/pull/47, unattended-upgrades in not activated by default. Add an option to enable periodic upgrades.

**Comment by fonfon** [comment]
With merging #95 users now have the possibility to check for upgrades and enable auto-upgrades.

In my opinion, auto-upgrades (and unattended-upgrades) should be installed and enabled by default, so I don't close this issue for now.

**Comment by jvalleroy** [comment]
With the setup mechanism integrated, upgrades are now enabled by default.
