### ISSUE TITLE
Cache checking whether user is an admin

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#781]
Currently, with each page load, we check if the user is an admin.  This leads to an SQL query on each page load.  This can be avoided if the result is cached in the session.

**Comment by SunilMohanAdapa** [comment]
To see the list of SQL queries on the terminal, add the following to the logging configuration in `__main__.py`:
```
        'loggers': {
            'django.db.backends': {
                'level': 'DEBUG'
                }
            }
```
After this, add a parameter to `is_user_admin()` method `cached`.  This value should be set to false by default.  When retrieving this value in context processor, set `cached=True`. During important checks such as in user administration page, cached values will not be used.

The cached value should be stored in session.  For this, instead of taking `request.user` object as parameter for `is_user_admin()` take the `request` itself.

**Comment by Marauderer97** [comment]
@SunilMohanAdapa I would like to work on this

**Comment by SunilMohanAdapa** [comment]
Sure, please go ahead.

**Comment by Marauderer97** [comment]
@SunilMohanAdapa I have made changes to the logging configuration in __main.py__. I have also changed the function definition, to include a variable cached, and change the argument user to request. 
![image](https://cloud.githubusercontent.com/assets/20185076/24508406/e99999fa-1580-11e7-882c-2b8d1e05eeae.png)

But I am not sure as to where I should set cached to True. Can you please elaborate?

**Comment by SunilMohanAdapa** [comment]
@Marauderer97 , something like this:
```
if cached and request.session has variable cache_user_is_admin:
  return cache_user_is_admin from request.session

user_is_admin = request.user.group...exists()
set cache_user_is_admin in request.session to user_is_admin
return user_is_admin
```
See [Django documentation](https://docs.djangoproject.com/en/1.10/topics/http/sessions/) on how sessions work and how to store and retrieve values from a session.

**Comment by Marauderer97** [comment]
@SunilMohanAdapa  Thank you! Changed the function accordingly, yet to test however.
Also, the method `is_user_admin` has been called in files such as
forms.py
views.py
middleware.py

I have set cached= True only in middleware.py. Is this correct?

**Comment by SunilMohanAdapa** [comment]
On 04/01/2017 11:03 PM, Soumya Vadlamannati wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa> Thank you! Changed
> the function accordingly, yet to test however.
> Also, the method |is_user_admin| has been called in files such as
> forms.py
> views.py
> middleware.py
> 
> I have set cached= True only in middleware.py. Is this correct?

You only need to get cached=True value in context_processor.

-- 
Sunil

**Comment by Marauderer97** [comment]
@SunilMohanAdapa Sorry for the long gap, I have been busy with a lot of exams and course work. There is no mention of is_user_admin in context_processors.py, so i added the following:
![image](https://cloud.githubusercontent.com/assets/20185076/24836105/e0da1fe4-1d30-11e7-8396-f0fed4441dde.png)
Is this what was expected? Also, how do I test my code, to see if the caching is working or not?

**Comment by SunilMohanAdapa** [comment]
@Marauderer97 , I believe you are looking at older code.  There is import of `is_user_admin` from `plinth.utils` in `context_processors.py`.  You can keep the name of the context variable as it is currently.

**Comment by Marauderer97** [comment]
@SunilMohanAdapa Thank you! I have made a PR.
