### ISSUE TITLE
disks: Show option to resize the disk even when free space is not available

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#785]
We have an option to resize the root partition when there is space available after it.  It is available in 'System Configuration -> Disks'. It does not show up when there is no free space.  From a UI point-of-view it is better to show it all the time and disable it when it is not applicable.  Users will be able to discover this option and be satisfied that this operation need not be performed.  This will also help them understand that such a feature is available to be used on other installations or for other users.

So, in 'Disks' module, instead of hiding the resize option, show it always.  If there is no free space available, simply show different message as follows and disable the "Expand Root Partition" button.  The message should be "There is no unallocated space after your root partition.  There is no need to expand it."

Implementing this only requires basic Django templating skills.

**Comment by JoKeyser** [comment]
Hi Sunil, I'm that potential beginner to give this a try.
I'm new to Django, but it's simple enough. Omitting the button would be very easy, trying to "disable" it is harder than I hoped. Are there any examples of disabled buttons somewhere? Or would this be the first disabled one?

**Comment by SunilMohanAdapa** [comment]
@JoKeyser , see how to disable a button using Bootstrap which we use: https://getbootstrap.com/css/#buttons-disabled

**Comment by JoKeyser** [comment]
@SunilMohanAdapa thanks for the fast help! (And sorry for the initial mess.)
