### ISSUE TITLE
Failing command to assess whether partitions are expandable

### ISSUE THREAD

**Issue by JoKeyser** [freedombox/Plinth#795]
When investigating why I can't see the disk resize button, and found these errors in /var/log/plinth/status.log:

`plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/disks', 'is-partition-expandable', '/dev/root'], , Invalid device, must be a partition`

My guess is that in my case, the called command should have used `/dev/mmcblk0` instead of `/dev/root`... let me know if I can help with additional information.

**Comment by SunilMohanAdapa** [comment]
On Sunday 09 April 2017 02:14 AM, Johannes Keyser wrote:
> When investigating why I can't see the disk resize button, and found
> these errors in /var/log/plinth/status.log:
> 
> |plinth.actions ERROR Error executing command - ['sudo', '-n',
> '/usr/share/plinth/actions/disks', 'is-partition-expandable',
> '/dev/root'], , Invalid device, must be a partition|
> 
> My guess is that in my case, the called command should have used
> |/dev/mmcblk0| instead of |/dev/root|... let me know if I can help with
> additional information.

disks/__init__.py:get_root_device() is failing.  This in turn is because
disks/__init__.py:get_disks() is returning incorrect information.  This
is just information from the 'df' command.  Could you please post the
output of this command?

-- 
Sunil

**Comment by JoKeyser** [comment]
Here is the dump of `df`. Note that I have already increased the size manually.
I think it's funny that it refers to /dev/root instead of /dev/mmcblk0p2..?

```
$ df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root        7508804 2094328   5057576  30% /
devtmpfs          469544       0    469544   0% /dev
tmpfs             473876       0    473876   0% /dev/shm
tmpfs             473876   24388    449488   6% /run
tmpfs               5120       0      5120   0% /run/lock
tmpfs             473876       0    473876   0% /sys/fs/cgroup
/dev/mmcblk0p1    118886   20426     98460  18% /boot
/dev/sda1       14866912 4174716   9917284  30% /mnt/usb16G
tmpfs              94772       0     94772   0% /run/user/10000
```

Here is also the output of `fdisk`, making clear that there still is space behind the root partition, mmcblk0p2.

```
fdisk /dev/mmcblk0

Welcome to fdisk (util-linux 2.29.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): p
Disk /dev/mmcblk0: 29 GiB, 31104958464 bytes, 60751872 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xa9b135b2

Device         Boot  Start      End  Sectors   Size Id Type
/dev/mmcblk0p1 *         1   238281   238281 116.4M  e W95 FAT16 (LBA)
/dev/mmcblk0p2      238282 15625000 15386719   7.3G 83 Linux
```

**Comment by SunilMohanAdapa** [comment]
On Tuesday 11 April 2017 12:26 AM, Johannes Keyser wrote:
> Here is the dump of |df|. Note that I have already increased the size
> manually.
> I think it's funny that it refers to /dev/root instead of /dev/mmcblk0p2..?
> 
> |$ df Filesystem 1K-blocks Used Available Use% Mounted on
> /dev/root 7508804 2094328 5057576 30% /

Our code would have worked if device for root partition showed up as
/dev/mmcblk0p2.  Is this is stock FreedomBox image or something else
like Raspberry Pi iamge?  Is the partition encrypted or so?

Could you please also post the output of lsblk?

> 
> Here is also the output of |fdisk|, making clear that there still is
> space behind the root partition, mmcblk0p2.

Clearly, there is more space after the root partition.

The code that we have to recognize the parent device of the mounted root
device makes too many assumptions.  If we use lsblk command instead of
df then we will get to know the type of the device.  We will be able to
ignore loopback device, crypto devices etc. and just work on partitions.
 We can also reliably find the parent device of a given partition.

-- 
Sunil

**Comment by JoKeyser** [comment]
Hi. No encryption, but it's indeed the Raspberry Pi image, initially http://ftp.freedombox.org/pub/freedombox/0.9/freedombox-testing-nonfree_0.9_raspberry2-armhf.img.xz

Here my output of lsblk (sda is an additional USB stick):

```
$ lsblk 
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    1  14.5G  0 disk 
`-sda1        8:1    1  14.5G  0 part /mnt/usb16G
mmcblk0     179:0    0    29G  0 disk 
|-mmcblk0p1 179:1    0 116.4M  0 part /boot
`-mmcblk0p2 179:2    0   7.3G  0 part /
```

It seems indeed that lsblk is a much better view on the situation.
And there are nice switches to it to make the output simpler to parse, e.g.
```$ lsblk --output KNAME,SIZE,MOUNTPOINT
KNAME       SIZE MOUNTPOINT
sda        14.5G 
sda1       14.5G /mnt/usb16G
mmcblk0      29G 
mmcblk0p1 116.4M /boot
mmcblk0p2   7.3G /
```

**Comment by JoKeyser** [comment]
Note that maybe even better than `lsblk`'s console output format, there are switches `-J` for json output, and `-b` to get all sizes in Bytes!

**Comment by SunilMohanAdapa** [comment]
On Wednesday 12 April 2017 03:57 AM, Johannes Keyser wrote:
> Hi. No encryption, but it's indeed the Raspberry Pi image, initially
> http://ftp.freedombox.org/pub/freedombox/0.9/freedombox-testing-nonfree_0.9_raspberry2-armhf.img.xz
> 
> Here my output of lsblk (sda is an additional USB stick):
> 
> |$ lsblk NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT sda 8:0 1 14.5G 0 disk
> `-sda1 8:1 1 14.5G 0 part /mnt/usb16G mmcblk0 179:0 0 29G 0 disk
> |-mmcblk0p1 179:1 0 116.4M 0 part /boot `-mmcblk0p2 179:2 0 7.3G 0 part / |
> 
> It seems indeed that lsblk is a much better view on the situation.
> And there are nice switches to it to make the output simpler to parse, e.g.
> 
> |KNAME SIZE MOUNTPOINT sda 14.5G sda1 14.5G /mnt/usb16G mmcblk0 29G
> mmcblk0p1 116.4M /boot mmcblk0p2 7.3G / |
> 

This clears up a lot of things:

- This bugs happens on FreedomBox images and not other weird setups :)

- On you machine /dev/root must be a symlink to /dev/mmcblk0p2.
Although I have not seen this happen before.

- lsblk is a much better way of finding out the information we need.
The formatting options are awesome (JSON and bytes output with -J -b).

I would not expect lsblk to return partition boundary information.  We
already have a way to extract this information using parted (which is
quite good at this kind of stuff).  We just didn't have the proper
device name to work with before.

So, we should go ahead and:

- Use lsblk to get the device name of the root mount '/'.

- Possibly use PKNAME and KNAME to figure out the parent device of a
given partition.

- Back-off and report a proper error if the root partition is anything
other than 'part' as type.

The rest of the code should do okay.

-- 
Sunil

**Comment by JoKeyser** [comment]
Okay in PR #823 , I've tried to be minimally invasive, and had to make a few compromises.
Most importantly, I think `lsblk` and `df` deliver complimentary info, so I combined their output, based on the mount point of their outputs.
I'm curious what you think.

**Comment by JoKeyser** [comment]
Here's also a screenshot to show it's now working at least for my case.
Tests also run fine.
![disksworkingonrpi2](https://cloud.githubusercontent.com/assets/8722846/25456813/4cb69fca-2ad4-11e7-925b-11cf5cc92403.png)
