### ISSUE TITLE
syncthing: Missing line break in frontpage shortcut label

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#800]
I noticed that Syncthing doesn't have a line break in its title:
https://github.com/freedombox/Plinth/blob/master/plinth/modules/syncthing/__init__.py#L40

Compare to other modules such as matrixsynapse:
https://github.com/freedombox/Plinth/blob/master/plinth/modules/matrixsynapse/__init__.py#L44

Although its quite minor, we should add the new line, for consistency.

**Comment by sahithi-ihtihas** [comment]
I just fixed the issue, here is the pull request:  #806

**Comment by SunilMohanAdapa** [comment]
Fixed by @sahithi-ihtihas in #806 .
