### ISSUE TITLE
Why i cant upgrade from 0.13 to 0.14?

### ISSUE THREAD

**Issue by dnkls** [freedombox/Plinth#811]
My Plinth steel 0.13 and dont upgrade not in manual not in auto, any ane get update?

**Comment by SunilMohanAdapa** [comment]
@dnkls , 0.14 has not been released yet.  It has been tagged on Git repository but the Debian package is not uploaded yet.  When Debian package is released, it takes about 10 days to reach Debian 'testing' distribution.  A day after that, you should be see your FreedomBox automatically upgraded.

If you are doing development with FreedomBox, checking out latest code from Git and running vagrant will give you a FreedomBox instance with latest code.  For this see the HACKING instructions in the repository.
