### ISSUE TITLE
dynamicdns: Configured domain should show up in "Names" module

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#814]
Currently, when Dyanamic DNS module is configured for a domain, this domain does not show up in the names module.  When a Tor hidden service is added in the Tor module, or when a domain is configured in the pagekite module, or when a domain is configured in the 'Configure' page, they all show up in the names module.  The names module is the central point from which all other modules collect information about domains.

Implementation should do the following:
- When the Dynamic DNS module is initialized, if it is setup and configured, then add the domain name.
- When module is configured from nothing to full domain configuration, add the domain name.
- When module is deconfigured remove the domain name.
- When module configuration changes for domain name, remove the old domain name and add new domain name.

Adding/removing a domain name in the 'names' module is straightforward using the domain_added and domain_removed signals available from the names module.  See example of how to do this in the `tor/__init__.py`.

**Comment by harry-7** [comment]
I created a pull request with suggested changes. However I was not able to figure out this
How to do the following
> When the Dynamic DNS module is initialized, if it is setup and configured, then add the domain name.

It would be helpful if you can elaborate on this.

**Comment by jvalleroy** [comment]
I think this is partially fixed in #920. However, it doesn't show services as enabled yet.

I would suggest, if dynamicdns is enabled, and the domain name is not empty, then we could assume all services in the "external" zone are available at that name. (Including http / https / ssh which are currently shown.)

**Comment by jvalleroy** [comment]
Fixed in #926.
