### ISSUE TITLE
Synapse can't login to any room 

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#822]
I can't seem to log in to any chatroom. After logging in to synapse on my FreedomBox joining `#matrix:matrix.org` says `#matrix:matrix.org is not accessible at this time`.

Actually I'd like to join an IRC channel (which does not work either, there isn't even a dropdown for IRC) but I guess as long as native matrix rooms don't work this isn't important.

![image](https://cloud.githubusercontent.com/assets/164785/25403807/e8b8323a-29fd-11e7-9c42-db4d2b0fa2ba.png)

**Comment by mray** [comment]
@richvdh over [at synapse](https://github.com/matrix-org/synapse/issues/2169#issuecomment-297949192) says:
>  Have you set up federation correctly (see https://github.com/matrix-org/synapse/blob/master/README.rst#id6) ?
> 
> otherwise look for errors in your homeserver log


...I have no idea about reverse proxy and stuff. is it possible FreedomBox does indeed not enable federation properly?

**Comment by SunilMohanAdapa** [comment]
For federation to work, other instances of matrix should be able to connect the FreedomBox' instance of matrix. For that, the following conditions should be met:

- The server must be reachable by the domain name it is configured with. Example: xyz.freedombox.rocks should be the domain we configured Matrix and xyz.freedombox.rocks should be reachable from Internet.  This can be easily checked.
- Next there must be an SRV record for matrix server on the DNS (or) Matrix server should be running on the default port 8448 (this is what FreedomBox is relying on).  FreedomBox should open up the port 8448.  This can be checked in firewalld and diagnostics page of Matrix Synapse package.  Also can checked from outside as:
```
$ curl -k https://<domain_name>:8448

<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>
```
- Finally, the fingerprint for the SSL certificate should be known to the Matrix Synapse server.  We side step the problem by letting Matrix Synapse server do its own SSL. It uses a self-signed certificate but this is okay as per Matrix server.

**Comment by mray** [comment]
`curl: (7) Failed to connect to *domain* port 8448: Connection refused`

I guess my router has to forward port 8448 to my freedombox!?

**Comment by SunilMohanAdapa** [comment]
@mray , yes you should.  That will likely resolve the problem.

**Comment by richvdh** [comment]
> Next there must be an SRV record for matrix server on the DNS (or) Matrix server should be running on the default port 8448 (this is what FreedomBox is relying on).

to be clear: you *only* need an SRV record *if* synapse is not running (and reachable) on port 8448. It sounds like in this case you do not need an SRV record.

**Comment by mray** [comment]
Thanks everybody. After noticing the matrix service refused to run for some reason I finally got it to run with the port forwarded - and it works!
