### ISSUE TITLE
De-bloat first welcome screen

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#830]
after installing FreedomBox and logging in the first time with my new admin user i'm greeted with this screen:
 
![export](https://cloud.githubusercontent.com/assets/164785/25589580/6df75e68-2ead-11e7-9fdf-e173eb68644c.png)

# A 
The note about restricted console login process only matters to people who login to consoles. Our target audience will not understand this, and probably just be intimidated by the techy jargon and "security restrictions"

Lets remove that notification for harmonys sake in the first seconds dealing with FreedomBox's interface.

# B
That text can be trimmed down to a smaller note without redundancy:
## Setup complete! 
Without any apps installed your FreedomBox is dull.
`Go install apps!`

# C
Not sure how relevant that section is. In most cases I don't see this as relevant and we would draw attention to a non issue. Maybe have a quick test if internet connectivity is there and just skip the whole section if it is.
In case we would actually need to care about a network setup at this stage – we can omit the rather complex illustration and just have a button that invites you to care about the issue, if it is one. This would also simplify the first screen.

**Comment by JoKeyser** [comment]
Hi, I agree with points A,B and made a pull request with your verbatim changes.
About C) I'm leaning towards leaving it in, personally. It's hard to guess how people want to use their freedombox, so they should be aware that any automatic solution should be checked.

I agree that the Wi-Fi password issue should only be raised if the freedombox provides an AP? There might be a way to check this, and only warn about it if true...

**Comment by mray** [comment]
Wow, @JoKeyser thanks a lot for taking up that issue, looks much cleaner already! 

about C):

I'll make an assumtion here but may be wrong: **IF** FreedomBox has Internet connectivity, it can be assumed that most hardware and software related settings are ready to go. Further setting up *may* be necessary, but isn't obvious or essential.

If FreedomBox does **NOT** connect to the Internet I would assume that some setting up definitively has to happen. In that case we may want to have a dedicated notification that maybe invites to begin setting up. (BTW I think there should be a notification about missing connectivity).

In no case is it necessary or really benefitial to show a graph  with cryptic icons and terminology like `WAN (enp0s3)` . This *may* be helpful to an admin and makes sense next to some options to act upon, but displaying it just for "clarity" is too loud in my eyes. Maybe if it was part of a multiple choice of preset settings that can match your local topology it would make sense...?

I see that removing C) may be problematic, I guess I just don't know which cases that would exactly relate to. Can somebody help me understand what our target cases are?

**Comment by SunilMohanAdapa** [comment]
Removing A) is good.

Trimming B) is good.  However, it would be nice if we had more formal message than a casual message.  There is a risk of too many casual messages showing up. At least, I suggest "Install Apps" (note the title casing for consistency with the rest of the interface) instead of "Go install apps".

I would be nice if can do better with C).  Internet connectivity is less of a concern. Currently, it is being shown because, people might have situations like:
- FreedomBox is my gateway to Internet.  This needs two network interface one each in "external" and "internal" zones.
- FreedomBox is another device on my network. This needs one "internal" network interface.
- (and more recently proposed) FreedomBox is on a cloud.  This needs one "external" network interface.

Ideally, we should let the user easily select the configuration (we need to build a good UI for this, perhaps on a separate screen). Like @mray, pointed out, we should reduce the noise (such as interface names) in the screen if possible.

**Comment by mray** [comment]
### B) 
Your remarks on B) make sense . "Install Apps" is better.

### C)
I think Plinth should only cover the most relevant case on the welcome screen: *"just another device on my network"* and omit C) if we think no further setup is needed. *"Cloud"* and *"Gateway"* seem less likely in this moment, require administrator skills and a dedicated page *anyway* – so I'd really not bring this to the entire audiences attention right from the start.

>  Internet connectivity is less of a concern.

Many people local/external connectivity are hard to grasp concepts. We probably don't have to expect "has no internet" to be an issue - but an indication when FreedomBox is *NOT* connected seems sensible feedback during setup.

### generally
There probably are smart ways to segway into an easy setup - instead of just totally trimming the welcome screen down. I'm just not sure what that could or should be... - what am I missing?

* **just another device**
  * setting up reachability (DynDNS or Pagekite or Tor ...)
  * create let's encrypt cert *(why not part of the auto setup btw?)*
  * forwarding ports *(there should be alerts for apps that don't get forwarded what they "need")*
  * installing apps
  * ???...

* **Gateway**
  * ???...
  * pointing other devices to new gateway?
  * installing apps

* **Cloud**
  * ???...
  * installing apps

**Comment by JoKeyser** [comment]
Okay I've adapted the message in B) to be slightly less casual, hope you agree?

About C): As a first step, I suggest to simply erase the network graph, and only point out where the settings are. The warning about default Wi-Fi password should always be present, regardless of first boot, at least in the Network settings. Hence it can go out of the welcome screen (and make space for other things, see below).

Here a screenshot of the current PR:
![firstboot_welcome_strippedabc](https://cloud.githubusercontent.com/assets/8722846/26025370/64801388-37e6-11e7-94a4-09360c6de9dc.png)


About the discussion above, I think it's really important but goes beyond the scope of this issue. Below is my attempt to disentangle the topics.

*The welcome page cannot do much.*
Keep in mind the welcome screen is shown exactly once. Imagine a newcomer only reads the first sentence, and immediately clicks on "Install Apps!" - you can't (sensibly) revisit this page; nor should you not need to. Thus, I think the welcome page should/cannot not do more than point the newcomer to the pages that should be looked at first.

*New issue? Revise content and order of welcome screen.*
I agree the screen should show anything that went unexpected (e.g. no Internet). Then it should point to the most important settings  as brief as possible, maybe with a link to a wizard (see below). Maybe some fundamental defaults should be stated (such as the network), but this easily bloats this one-time screen.
I'm unsure whether Install Apps should be the first option to present. To me, first configuring a Domain makes more sense, given that some services play well with domain changes (e.g. ejabberd, #83).
Maybe also the disk-resize option might be mentioned here, see #784...

*New issue? Add Setup Wizard(s)*
For more complex choices that involve interactions of apps and the box's position in the network, a dedicated setup wizard might be added, which can be invoked at any later time as well.
The structuring in @mray 's last post should go here.
Similarly, the options in @SunilMohanAdapa 's last post could also go here; or on the network page.
Maybe a Setup Wizard could be composed of sub-wizards that make sense independently, e.g. the Network wizard's part can be visited directly from the network page.

*New issue? Warn about default Wi-Fi password*
The warning about default Wi-Fi password should always be present, regardless of first boot, at least in the Network settings. Maybe it should even be displayed everywhere, or maybe only in the configuration context?

**Comment by mray** [comment]
> Okay I've adapted the message in B) to be slightly less casual, hope you agree?

Sounds totally fine.

> The welcome page cannot do much.

I absolutely agree.
I'd even go a step further and stick to a basic UX rule of thumb to have **ONE** hero action/button that we want people draw to: the `Install Apps` button, and only link the text *check the network setup* to the destination of the current *Go to Networks*-button.

> New issue? Revise content and order of welcome screen.

 Opened #849. 

> New issue? Add Setup Wizard(s)

Opened #850.

> New issue? Warn about default Wi-Fi password

This could be mentioned in a Wizard, but ultimately is worth a permanent notifcation alert until changed. In my eyes.

**Comment by JoKeyser** [comment]
@jvalleroy also changed the network button into link and merged it all; so this can be closed.
