### ISSUE TITLE
Link power button to "Restart or shut down the system."

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#834]
* The power button in the header should replace the respective "configurations"  tab.
* The currently linked logout option should be a dropdown option on the user icon.

@Marauderer97 sorry, I could have noticed earlier if I had a running version of the latest changes. 

![safswfwefe](https://cloud.githubusercontent.com/assets/164785/25693457/a9bcd5a6-30a9-11e7-9fd9-22e12cb55fd6.png)

**Comment by JoKeyser** [comment]
Hi @mray , I've created a PR, to do the new drop-down, but at the moment without erasing the module from the system menu. I think it's not a problem to have redundant access? And maybe more things will be added to the page, not just the 2 buttons...
Note also that the drop-down only works with JavaScript enabled.
Let me know if you insist on removing it :), it can be done of course.

**Comment by mray** [comment]
Not being available without Javascript is a problem. The "Power" module hardly configures anything though, and it really is just a simple on/off switch. So I think it should not be listed as a full configuration module in the long run.

**Comment by JoKeyser** [comment]
Missing JavaScript is not a big deal at all, the power button in the top right brings you to the power page with both buttons.
So I agree now, if we ever have more features than that, we can also put it back to the menu.
PR #884 will erase it until then.

**Comment by jvalleroy** [comment]
Fixed in #871 and #834.
