### ISSUE TITLE
FreedomBox Administration via web browser using Cockpit

### ISSUE THREAD

**Issue by JosephKiranBabu** [freedombox/Plinth#838]
Redhat's Cockpit project can save us a lot of duplicated effort if we use it as the administration tool for FreedomBox. Also, Plinth's user interface can be simplified much further as most administration tasks can be delegated to this app.

http://cockpit-project.org/

Cockpit is included in Debian unstable.

**Comment by mray** [comment]
Looks like an interesting project. A quick glance makes me think this is a good tool to reveal administration tasks in detail, and therefore not lend itself to simplify as we need it. Maybe this is a wrong impression - do you have experience in using cockpit?

**Comment by JosephKiranBabu** [comment]
@mray Cockpit was Sunil's idea. I created this issue for him. I haven't tried it out yet.
@SunilMohanAdapa Can you add more details?

**Comment by jvalleroy** [comment]
Here are my thoughts on how this might be used:
1. As an optional "advanced" or "expert" interface, available as another app that can be installed in Plinth. This might allow us to simplify other parts of Plinth, for example, the Networks configuration. Network configuration in Plinth could be made very simple, like "pick one of these 3 common use cases". Then, if some more detailed configuration is needed, the expert interface can be used for that.
2. Cockpit includes a configuration backend. Perhaps Plinth can talk to this directly, and it can replace some of the "actions" scripts included in Plinth.
3. It also appears to be somewhat configurable. We can explore if it's possible to simply the interface sufficiently for our use case.

**Comment by JosephKiranBabu** [comment]
Cockpit operates over websocket. 
Apache's proxying support for websockets has been added recently. https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

Looks like this apache mod doesn't have a Debian package yet.

**Comment by JosephKiranBabu** [comment]
@vignanl Please take a look at the above comment.

Since we cannot proxy Cockpit using Apache, we have to open a port in the firewall to make the web UI available to the user. Please see Matrix Synapse or Tahoe-LAFS for reference on how to do this.

Also, we'll have to enable HTTPS for the service since it would require a login.

**Comment by jvalleroy** [comment]
Cockpit has been added (as optional module) for 0.16 release.
