### ISSUE TITLE
Footer fixed bottom

### ISSUE THREAD

**Issue by kkampardi** [freedombox/Plinth#840]
Footer  would look better pinned to the bottom of the viewport in in desktop browsers. 
![footer-fixed-bottom-1](https://cloud.githubusercontent.com/assets/8265472/25887885/9117bae4-356c-11e7-96e5-8ce5999c234d.png)
![footer-fixed-bottom](https://cloud.githubusercontent.com/assets/8265472/25887890/948f59d4-356c-11e7-8ddb-5c7fc19ea367.png)

**Comment by mray** [comment]
I like the pinned down footer. Especially on pages with few content it can be problematic if it isn't pinned down.

**Comment by kkampardi** [comment]
@mray  I'm glad that you liked it. It was a bit trickier than I thought at first ( happens sometimes with UI implementation  :P) but i think it's OK now. Waiting for review

**Comment by jvalleroy** [comment]
Fixed in #843.
