### ISSUE TITLE
frontpage: Icons/config panel sometimes overlap footer

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#848]
I'm seeing this in some cases. It seems to happen depending on the number of shortcuts shown, the browser window size and font size.
![frontpage_overlap](https://cloud.githubusercontent.com/assets/178876/26029873/5cc7bf7e-380e-11e7-964e-a38f4c06b080.png)

**Comment by mray** [comment]
Is this possibly connected to #840?

**Comment by kkampardi** [comment]
Yes @mray! Could  be related! I' can take care of this asap

**Comment by kkampardi** [comment]
Finally it was related to #840.  I've tried to reproduce this in various ways. Now it seems to work fine. I hope it'll keep it so ( joke  :) )

**Comment by kkampardi** [comment]
After some morning tests it turns that still there are minor issues ( when switching window sizes on large devices). I think that I'd better improve this before the reviewer accepts the PR

**Comment by kkampardi** [comment]
OK. Waiting for review

**Comment by jvalleroy** [comment]
Fixed in #852.
