### ISSUE TITLE
sso: Need to upgrade crypto

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#868]
With mod-auth-pubtkt, we are using DSA and SHA1, because RSA and SHA256 were not usable in current version. Check when mod-auth-pubtkt will be fixed, and upgrade the crypto algorithms that we use.

**Comment by JosephKiranBabu** [comment]
**Update:**
The issue has been fixed in auth-pubtkt's upstream. 
A bug has been raised on Debian to update the deb package.

**Comment by SunilMohanAdapa** [comment]
Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867572

We should wait for a newer version of Debian package to the uploaded then patch our configuration to set RSA and SHA256.

Also it seems that we are using 1024 bits for DSA key pair.  For RSA we should use at least use 2048 if not 4096.

**Comment by SunilMohanAdapa** [comment]
Fixed with #995.  But we need to add a dependency to Plinth's Debian package for libapache2-mod-auth-pubtkt >= 0.11.
