### ISSUE TITLE
When no timezone is set, Plinth shows the first timezone

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#88]
Instead it should show an empty item or a special item showing that no timezone is set.  This problem can be seen on freshly built FreedomBox [images](http://ftp.skolelinux.org/pub/freedombox/latest/).

**Comment by SunilMohanAdapa** [comment]
This bug is not fixed even with the pull request.  The merged patch works when the /etc/timezone file is empty but does not work on a fresh freedombox image indicating that the file has non-empty contents initially.  This must be accounted for.

**Comment by SunilMohanAdapa** [comment]
Turns out initially the value of timezone file is Etc/UTC and we are not handling this well.

**Comment by bharathCh** [comment]
Working on this.

**Comment by jvalleroy** [comment]
This is fixed in v0.6 release.
