### ISSUE TITLE
Add renewal hook scripts for Let's Encrypt certificates

### ISSUE THREAD

**Issue by JoKeyser** [freedombox/Plinth#881]
As far as I understand, our LE certificates are not being automatically renewed ~~yet~~ (edit: properly, with restarting apache2). Let's make a sketch how to implement this best.
To me, solving this is a prerequisite to meaningfully tackle LE integration with other modules, which were already requested for repro (#385), ejabberd (#565, #579), mumble (#701), and IPSec (#614). The reason is that modules that use the LE certs will have to add certain actions upon certificate renewal (at the least, a restart). So it's good to keep that in mind, to avoid annoying surprises.

**Comment by JoKeyser** [comment]
Let's define/debate the goals, independent of implementations.

There are potentially several (sub) certificates available to the Freedombox, e.g. if the admin plays around with domain names. For simplicity, I think renewing only the certificate that matches the currently configured domain is sufficient. That would avoid unnecessary extension of no-longer-used certificates and potential confusion, e.g. about errors if some previous domain expires and the renewal fails just because of that. 

---
For future module integration: What additional options should be offered?

1. The simplest option would be to offer a single on/off switch: Use LE certs only for web-server or LE certs for all modules (that support it, including those installed later). Such a switch would most make sense in the LE module page.
2. A more complex option would be to offer LE integration (of the currently configured domain) on a per-module basis. While more complex, this may be needed to give users a choice e.g. if they prefer Monkeysphere? (In any case, I think LE inclusion should be the default for now, if available?) These options could either be offered on the module page, or the LE page, or both?

**Comment by JoKeyser** [comment]
Here's an implementation sketch (e.g. syntax may be wrong) for the simplest case:
Renewals only for currently configured domain (`CURRENT_DOMAIN`), and for future module integration: one switch to use LE certs for either "no" or "every" module.
Any comments appreciated.

Needed component
* Some scheduler - maybe plain `cron` through command line, maybe `python3-crontab`, maybe [`django-cron`](https://github.com/Tivix/django-cron), ...?

To solve this issue, the scheduler registers the `certbot renew --domain CURRENT_DOMAIN` call, to execute once per day.
The certificate is only actually renewed if expiry is getting closer (that's `certbot`'s default behavior).

---

For future module integration

Added components
* Per module, add an action sub-command `renew-hook` with `--domain` argument, executing the module's needs run upon cert renewal.
* A `sequence-renew-hooks` sub-command for `letsencrypt` that traverses the actions of all installed modules for `renew-hook` subcommands, and executes each one sequentially. It passes the `--domain` argument to each of them, thus also needs one.

If active, the scheduler registers instead `certbot renew --domain CURRENT_DOMAIN --renew-hook "letsencrypt sequence-renew-hooks --domain CURRENT_DOMAIN"`.
The renew-hook are only executed if an actual certificate was obtained (that's `certbot`'s default behavior?).

**Comment by jvalleroy** [comment]
We might want an option to disable the automatic renewal, just so the user has full control over what their box is sending over the internet.

I'm not too sure about the need to disable LE certs. Would this be tied to the "Revoke" button currently on the Lets Encrypt page? Should the box switch back to self-signed certs in this case?

**Comment by JoKeyser** [comment]
Thanks for chipping in, @jvalleroy. Over Matrix, you also said "I guess I don't see a reason to not use LE certs for all modules -- if they are available".

About disabling automatic renewal: No problem to include this, however I think automatic renewal should be the default. If disabled, there might be a warning. Adding an email address (#636) would make manual renewals/re-obtains easier because the admin would get reminders about expiry.

About disabling LE certs: Yes, I think the box should switch to the modules' self-signed certs, especially if the LE cert gets revoked (since it may get revoked because its compromised). Maybe some admins want to force people to manually trust certificates, maybe even only with certain modules. If that's really requested, we could add this feature later, I think? Or should we preemptively include it (and make the UI and code more complicated)?

**Comment by JoKeyser** [comment]
I'll try and implement a solution next weekend, but I'm still undecided how best to execute the recurring tasks. I guess it's a tradeoff between dependencies and integration with the rest of Plinth... specifically:
1. With plain `cron`, no new dependencies, but some custom code to register the jobs and report errors into Plinth (so that the admin can make some sense of it).
2. With `python-cron` there's less custom plumbing, not sure how it would simplify reporting errors.
3. With [django-cron](https://github.com/Tivix/django-cron) we would probably gain the best integration with Plinth, but I'm not sure at what price of additional dependencies (didn't read about it yet).

Do you have an opinion, @SunilMohanAdapa or @jvalleroy or @JosephKiranBabu ? It would be great to get this right from the beginning.

**Comment by jvalleroy** [comment]
@JoKeyser Another option is a systemd-timer. I found one in the certbot package:
https://sources.debian.net/src/python-certbot/0.11.1-1/debian/certbot.timer/
Do you know if that is enabled on FreedomBox?

**Comment by JoKeyser** [comment]
Hi @jvalleroy , systemd-timer sounds nice actually, there is also an [LE example here](https://www.shivering-isles.com/lets-encrypt-renew-all-your-certs-using-systemd/), I'll check it out.
In general I prefer Plinth being unobtrusive, by doing things transparently with tools that a more experienced admin can also change without Plinth. That is, best using plain cron or systemd timer, not a django-integrated thing.

**Comment by JoKeyser** [comment]
Okay, I've done some reading on the actual situation. First off, I was wrong to claim that "currently, the certs are not renewed yet". They do get renewed, by virtue of the systemd certbot.timer that ships with the Debian package (thanks for the hint, @jvalleroy). That timer calls `certbot --quiet renew` twice per day, meaning *all* available certificates will get renewed if they're near expiry (<30 days left). Conveniently, obtaining a certificate also creates a configuration file per domain/cert lineage, in `/etc/letsencrypt/renewal/$DOMAIN.conf`, remembering the settings of the call used to obtain it, so this likely works fine already in all cases.
I've successfully tested it with the Freedombox vagrant image, by appending `--dry-run`, i.e. running `certbot renew --dry-run`.
With that in mind, the only remaining issue is that the current certbot timer does *not* yet include pre-, post-, and renew-hooks. There is an open request to include an easy, Debian-way here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838548, but as it is, we would have to edit the systemd certbot.service file.

But to keep things simpler, I propose to add another, independent timer that includes the necessary pre-, post- and renew-hooks for the domain currently used by Plinth. While it would be somewhat inelegant to add another timer, this approach avoids messing with certbot's timer setup, e.g. of existing manual changes before somebody installed Plinth. Further, it's very transparent to an admin logged in with SSH. To disable it, we simply erase the entire systemd timer and service, e.g. if a better way of implementation becomes possible. For future LE integration into modules, maximally the hook arguments would change in our systemd service file.

Any counter-arguments or improvements to this plan?

**Comment by JoKeyser** [comment]
Okay, I've done some reading on certbot's systemd timer situation, most importantly the end of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838548, wish I had found this earlier.

First off, I was wrong to claim that "currently, the certs are not renewed yet". They *do* get renewed, by virtue of the systemd certbot.timer that ships with the Debian package. That timer calls `certbot --quiet renew` twice per day, meaning *all* available certificates get renewed if they're near expiry (<30 days left). Confusingly, this *does* also run pre-, post- and renew-hooks, see below.
Conveniently, obtaining a certificate also creates a configuration file per domain/cert lineage, in `/etc/letsencrypt/renewal/$DOMAIN.conf`, remembering the settings of the call used to obtain it, so this likely works fine already in all cases. Most importantly, you can also add pre-, post-, and renew-hooks per domain, by adding them in the section `[renewalparams]`.
```
[renewalparams]
...
pre_hook = /path/to/executable
renew_hook = /path/to/executable
post_hook = /path/to/executable
...
```

I've successfully tested that with the Freedombox vagrant image, by calling `certbot --dry-run renew --cert-name $DOMAIN`.

All that's left to do for Plinth is to add appropriate hooks into the config file! This solution is very transparent to anyone using just the command line. In case an admin had them specified before, we can make that choice explicit in Plinth, and even create a backup file to restore later. In case a cert gets obtained for the first time, we edit the hooks right in, as sensible default.
Finally, for future LE integration into modules, only hook arguments would change in that config file.

Any counter-arguments or improvements to this plan?

**Comment by JoKeyser** [comment]
One thing I'm still confused about: Potentially there's also already a cron job in place, to complement the systemd timer, in `/etc/cron.d/certbot`. But is this actually active?

**Comment by jvalleroy** [comment]
@JoKeyser If this is the cron job file:
https://sources.debian.net/src/python-certbot/0.11.1-1/debian/certbot.cron.d/
I think the "\! -d /run/systemd/system" will check that systemd is not available, and only do the renewal in that case.

**Comment by JoKeyser** [comment]
@jvalleroy , outstanding, so it should all work on any system. I've started hacking on this, I think it's ready for implementation :).

**Comment by JoKeyser** [comment]
This issue can be close, PR #891 is assimilated. Thanks @jvalleroy for the help.
