### ISSUE TITLE
networks: After setting manual IPv4 address, box has 2 addresses?

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#882]
After changing the IPv4 addressing setting to manual, and providing a fixed IPv4 address, my box is now showing 2 addresses: the fixed one and the original dynamic IP. When I reboot, the fixed IP remains, and the dynamic IP is changing. Is this expected?

**Comment by SunilMohanAdapa** [comment]
@jvalleroy , This is not expected.  I have tried out in the past many times and setting a static address just leads to just one address.  Could it be a new behavior of Network Manager?  Could you post the connection information using `nmcli connection show <ID/UUID>` (please don't forget to scrub any potentially sensitive data before posting).

**Comment by jvalleroy** [comment]
Hmm, well I haven't been able to reproduce this issue. I'll reopen if I see it again.
