### ISSUE TITLE
All my users have Admin rights

### ISSUE THREAD

**Issue by JayFreez** [freedombox/Plinth#886]
I just installed Freedombox on Debian 9. When I create a new user, and DO NOT check the admin group, they still have full access to do everything. What am I missed here?

**Comment by JoKeyser** [comment]
Hi @JayFreez thanks for filing this issue. Why did you close it again? If it was some misunderstanding, maybe the UI should be improved?

**Comment by JoKeyser** [comment]
Ah I saw jvalleroy's answer on Matrix now, it was solved in Plinth 0.14, while Debian 9 is shipped with 0.13.1.
