### ISSUE TITLE
Ability to enable/disable DHCP for clients through Plinth

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#89]
Imported from https://wiki.debian.org/FreedomBox/BetaReleaseTodos

**Comment by steglicd** [comment]
@SunilMohanAdapa 

maybe I would like to have a look at this topic. Basically I know what to do: 
* add a dnsmasq action script (to apply setting to system / read settings from system) 
* add a plinth page with django forms to control the action script

But is there any plan, how to trigger action scripts when firewall is reconfigured (without calling the script from the firewall action script - to avoid dependencies between firewall and DHCP Server)?

Maybe we need a component above Firewall and DHCP?  Because one may want to disable the firewall and the DHCP Server will not know on which interface he needs to offer a IP afterwards?

**Comment by SunilMohanAdapa** [comment]
On 05/20/2015 11:18 PM, Daniel Steglich wrote:
> @SunilMohanAdapa <https://github.com/SunilMohanAdapa>

This bug was not originally created by me.  It was merely imported by me
from another list.  I am happy to participate in it though.

> 
> maybe I would like to have a look at this topic. Basically I know what
> to do:
> 
>   * add a dnsmasq action script (to apply setting to system / read
>     settings from system)
>   * add a plinth page with django forms to control the action script

Sounds good.

There is one item more to be addressed though.  If we move this dnsmasq
configuration into Plinth, then DHCP will not be available before Plinth
is setup (first run wizard is run).  However, DHCP is one of the basic
services that we need to have even before Plinth is first run.

We could introduce a '--setup' parameter in Plinth. freedombox-setup
will call 'plinth --setup' during the setup process.  When Plinth is
started with this parameter, it would load all modules.  After that,
instead of initializing CherryPy it would call setup() methods in all
the modules that implement it.  Here, the dnsmasq module would perform
the default setup required.  I have also suggested this setup mechanism
in #103.  As a result of this we can move all the dnsmasq configuration
logic into Plinth as you suggested and have dnsmasq setup even before
Plinth first run wizard.

> 
> But is there any plan, how to trigger action scripts when firewall is
> reconfigured (without calling the script from the firewall action script
> - to avoid dependencies between firewall and DHCP Server)?
> 
> Maybe we need a component above Firewall and DHCP? Because one may want
> to disable the firewall and the DHCP Server will not know on which
> interface he needs to offer a IP afterwards?

We now have the networking module which uses NetworkManager to configure
networks.  (This should be used for configuring the initial network
configuration in freedombox-setup shell scripts also, but this is not
happening currently).  This is the component that could be considered as
'above' Firewall and DHCP.

It is the network configuration module that decides which firewall zone
a network interface belongs.  We are currently using 'Internal' and
'External' in firewalld sense.

When the firewall zone of a network interface changes, the network
module could emit a signal (Django signal) and that signal can be caught
by Plinth's DHCP module to change its configuration.  The signal
mechanism is already being used for other activities in Plinth (like
service enabled/disabled announcement).  The subscribers subscribe
voluntarily and this avoids dependencies.

One more thought: I think we should do a quick comparison of
NetworkManager's capability to 'share' the Internet.  It is possible to
configure a network interface in NetworkManager as 'shared'.  NM then
starts a DHCP server and DNS server on this interface and NATs all the
traffic to another interface that has proper Internet connection.  From
what I know, this works well but there is no fine gained configuration
possible (probably okay for FreedomBox's goals).  If this suffices, then
we can do away with the dnsmasq module altogether (and let
NetworkManager deal start/stop dnsmasq).

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
I believe that with the 'shared' configuration available in Network Manager working we no longer need to worry about this.

We are also configuring initial networking properly using network manager.  If more than two network interfaces are detected, then one of them is configured as external network and the remaining are configured as internal networks with 'shared' mode.  This makes network-manager run dnsmasq on them properly.

In freedombox-setup, we no longer run the dnsmasq server.  We switched the dependency to 'dnsmasq-base' which does not run a server but provides what is needed by network manager.

In effect, whether dnsmasq runs or not is decided by whether we configure any interface in 'shared' mode.

Further more, firewalld is currently configured to always allow DNS and DCHP on the 'internal' networks. This seems reasonable but we may later tune it to allow only when the services are in operation.

I believe this bug is not fixed due to above changes and behavior.  Please feel free to re-open the bug if you feel that there is more to be done.
