### ISSUE TITLE
Prevent removal of FreedomBox pakages from Debian testing

### ISSUE THREAD

**Issue by JosephKiranBabu** [freedombox/Plinth#893]
This log is from `apt`. 
We must address the issues before August 2017 to ensure FreedomBox users get updates on time.

```
New packages going to be removed from Debian 'testing' (the maintainer might need help):
 - freedombox-setup - https://tracker.debian.org/pkg/freedombox-setup - removal on 2017-08-09
 - plinth - https://tracker.debian.org/pkg/plinth - removal on 2017-08-09
 - python-django-bootstrap-form - https://tracker.debian.org/pkg/python-django-bootstrap-form - removal on 2017-08-09 (bug: #865938)
 - syncthing - https://tracker.debian.org/pkg/syncthing - removal on 2017-08-10
```

**Comment by JoKeyser** [comment]
I'm not in the loop obviously, what's going on? (How) can I help?

**Comment by JosephKiranBabu** [comment]
Looks like the package python-django-bootstrap-form isn't working with Django 1.11. Plinth will be removed since it depends on this package. Freedombox-setup depends on Plinth. Hence, it's also flagged for removal.

Basically, it boils down to fixing this one issue.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865938

**Comment by JosephKiranBabu** [comment]
Syncthing has manpage errors. I'd be disappointed if Syncthing isn't available on Debian/FreedomBox. Let's hope someone fixes it soon or we can step in if necessary.

https://lintian.debian.org/maintainer/pkg-go-maintainers@lists.alioth.debian.org.html#syncthing

**Comment by JoKeyser** [comment]
Okay, thanks a lot for filling me in. I'm subscribing to these trackers now and have a look.

**Comment by jvalleroy** [comment]
@JosephKiranBabu I think this it the RC bug affecting Syncthing:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=866175

**Comment by JoKeyser** [comment]
About `python-django-bootstrap-form`, I'm trying to reproduce the errors on my vagrant image, but I don't know how to do that. How is this package created? I've cloned https://anonscm.debian.org/cgit/openstack/python-django-bootstrap-form.git and tried to run `dpkg-buildpackage`. This errors, requesting some a tarball at `../python-django-bootstrap-form_3.2.1.orig.tar.{bz2,gz,lzma,xz}`.
When I guessed to download+rename from https://pypi.python.org/pypi/django-bootstrap-form/3.2.1, I get two errors:
```
dpkg-source: error: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -E -b -B .pc/django-1.10-fix-settings-in-runtests.py.patch/ --reject-file=- < python-django-bootstrap-form.orig.PWEsLo/debian/patches/django-1.10-fix-settings-in-runtests.py.patch gave error exit status 1
dpkg-buildpackage: error: dpkg-source -b python-django-bootstrap-form gave error exit status 2

```

Probably I'm doing something terribly wrong: Either `dpkg-buildpackage` is the wrong approach, or there must be another file (or branch) to get this file from, `../python-django-bootstrap-form_3.2.1.orig.tar.{bz2,gz,lzma,xz}`? Any hints welcome.

**Comment by jvalleroy** [comment]
@JoKeyser You can use "apt-get source" to get the orig tarball.

**Comment by JoKeyser** [comment]
I've sent a simple patch for `python-django-bootstrap-form` to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865938. As far as I get it, it's rather trivial.

**Comment by JoKeyser** [comment]
So what if the maintainer responsible for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865938 just doesn't fix it in time? How bad would this be for Plinth to be removed? Do we need a contingency plan yet?
I've started playing with https://packages.debian.org/sid/python3-django-crispy-forms which might replace `python-django-bootstrap-form`. But I'm not sure if we could switch package dependencies like this at this point? (I mean purely technically.)

**Comment by JosephKiranBabu** [comment]
**Update:**
The bug for Syncthing seems to be resolved. It's no longer marked for removal.
https://tracker.debian.org/pkg/syncthing

**Comment by JoKeyser** [comment]
Okay, the autoremoval is pushed back to September 14.
I pinged the people in https://github.com/tzangms/django-bootstrap-form/pull/97#issuecomment-321971122 about their year-long pending PR https://github.com/tzangms/django-bootstrap-form/pull/86, which is very similar to the one causing the autoremoval problem...

**Comment by jvalleroy** [comment]
The issue with django-bootstrap-forms package is now resolved. There's no more warning on https://tracker.debian.org/pkg/freedombox-setup about it being removed from testing. Thanks everyone for tracking this issue.
