### ISSUE TITLE
Errors while trying to install app "Owncloud"

### ISSUE THREAD

**Issue by kalakrumanov** [freedombox/Plinth#897]
In the main panel, when I click on "Install" button, I get the following error on top in red:

`Error installing application: Error during installation E: Package 'php5-pgsql' has no installation candidate E: Unable to locate package owncloud E: Unable to locate package php-dropbox E: Unable to locate package php-google-api-php-client `

I will try to solve them manually, but fyi, the errors occur using the default procedure.

**Comment by jvalleroy** [comment]
@kalakrumanov The owncloud package was removed about 1 year ago, and Plinth shouldn't show the page at all (unless you already had it installed?).

The module will be completely removed in Plinth v0.15.

**Comment by kalakrumanov** [comment]
Thanks you for the answer. Yes, it appears by default. I'm using raspberry pi 1, with image freedombox-testing-nonfree_0.9_raspberry-armel

So, are you going to have Nextcloud instead?

**Comment by JoKeyser** [comment]
@kalakrumanov , I agree it would be nice to include Owncloud or Nextcloud, but apparently it's been a difficult history so far to include them into Debian, see e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835086. Since we're a Pure Blend of Debian, this would have to be resolved first.

**Comment by JoKeyser** [comment]
So I guess this issue can be closed?
