### ISSUE TITLE
HACKING has old information for translators

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#913]
We have moved from Transifex to Weblate: https://hosted.weblate.org/projects/freedombox/plinth/

The HACKING file still refers to Transifex though. It should be updated to point translators to the correct location.

**Comment by JoKeyser** [comment]
Similarly, the information in https://github.com/freedombox/Plinth/blob/master/plinth/locale/README should be updated.

@jvalleroy , @SunilMohanAdapa  could we also drop the emphasis on introducing oneself? It feels like an unnecessary barrier to me.

**Comment by JoKeyser** [comment]
Similarly in the wiki: https://wiki.debian.org/FreedomBox/Translate ... I think it could be reordered. If somebody "just" wants to translate without introduction, that's fine?

**Comment by jvalleroy** [comment]
@JoKeyser Yes, I think that's fine. We can just say that the IRC / mailing list is available if they have any questions.

**Comment by JosephKiranBabu** [comment]
Merged in 7722419e05ec7cc557ad6ed9ec372441af720001
