### ISSUE TITLE
Improve Plinth Apps and Configuration pages for mobile devices

### ISSUE THREAD

**Issue by JosephKiranBabu** [freedombox/Plinth#921]
**Browser:** Firefox for Mobile
**OS:** LineageOS (Android)

Plinth on mobile looks awkward with the App/Configuration listing and the description section appearing in the same vertical column. Also, on clicking one of the apps or configuration items, the page doesn't scroll to the bottom and show the corresponding entry's description.

![plinth_with_app_selected](https://user-images.githubusercontent.com/4830191/28673543-678441a8-7300-11e7-8cbb-ef95f570e25f.png)

I suggest we have a hamburger menu on the left side like on the mobile website of readthedocs.io. Suggestions for alternatives are welcome!

![hamburger_menu_closed](https://user-images.githubusercontent.com/4830191/28673553-72f145d6-7300-11e7-85a5-cc7cac074b35.png)

![hamburger_menu_open](https://user-images.githubusercontent.com/4830191/28673560-79c3c4f6-7300-11e7-947a-63635d7fc75e.png)

This feature will be significant soon, as we will launch Plinth web interface in a web view in the FreedomBox Android app for users with admin privileges. https://github.com/freedombox/android-app/issues/7

**Comment by JosephKiranBabu** [comment]
We already have a hamburger dropdown menu on the right, which means we can't have another hamburger menu on the left. Maybe we can change the existing menu to be the 3 vertical dots button or something more intuitive. 
Design suggestions are welcome.

**Comment by jvalleroy** [comment]
What if we removed the menu from individual app pages? Only show it on /apps.

I think this would move closer to https://github.com/freedombox/Plinth/issues/739.

**Comment by mray** [comment]
@jvalleroy I think that would not solve it for the home screen.
I guess we could update the current dropdown:
![image](https://user-images.githubusercontent.com/164785/28713022-b5d69530-738d-11e7-9305-d4931b95b75c.png)

by
1. removing the "Home" entry
2. putting the three main sections  outside the dropdown in form of icons, next to the logo
3. putting all apps/configuration

simialr to this:
![image](https://user-images.githubusercontent.com/164785/28713229-8c6b1102-738e-11e7-9f83-c1579a5c096a.png)

The remaining links like the logout and reboot can be put at the very bottom, maybe with a separator.
>Note: depending on how soon the new layout will be available this should not use up too many hours of work.

**Comment by JosephKiranBabu** [comment]
@mray Just adding more details.
On clicking the icons for /apps and /sys, we show the default description pages ("Services and Applications" and "System Configuration" respectively) on the screen while populating the drop-down hamburger menu with corresponding list of items. 
I think this issue now has enough details for implementation.

**Comment by mray** [comment]
Actually I think we have to take a step back here. There is a fundamental problem of having the hamburger menu hiding its content already, but hiding it depending on the currently active page won't work.

An easier solution that may depend on Javascript is to have the main buttons (Apps/Configuration) have dropdown buttons similar to the current user menu entry:
![image](https://user-images.githubusercontent.com/164785/28746871-074a0f5e-7493-11e7-9c2c-4fdf0329f616.png)

The respective top level pages for Apps and Configuration might feature a list of links to make them available for peopel without javascript turned on.
Do my concern and my conclusion make sense?

**Comment by SunilMohanAdapa** [comment]
Showing a long list of applications is problematic in side menu as well as in burger menu.

I suggest we simply hide applications list inside an application page as the only change:

The "Applications" page (/plinth/apps) would look like this:
![screen shot 2017-08-02 at 15 00 09](https://user-images.githubusercontent.com/1535496/28867504-f979909e-7793-11e7-899c-a29fd48de69e.png)

An application page (/plinth/apps/tor) would look like this:
![screen shot 2017-08-02 at 15 01 21](https://user-images.githubusercontent.com/1535496/28867503-f96db27e-7793-11e7-88c5-89eae9a8c8dd.png)

To navigate to an application page, the user would have to click on the burger menu, select "Apps", then the applications page would come up. There they would select an application and would end up in the page of that application. To navigate back to application page, they press the back button or go through the burger menu.

**Comment by mray** [comment]
Sorry for the late reply: There would be still enough room to have icons in the top header for logo, apps(icon) and configuration right?

![image](https://user-images.githubusercontent.com/164785/29244304-24037c8e-7fb5-11e7-9172-6e14cf88cc10.png)
