### ISSUE TITLE
Framework: Generic framework for creating a user group per application

### ISSUE THREAD

**Issue by Shilpa-Badekila** [freedombox/Plinth#928]
**Estimate**: 3 points
Framework: Generic framework for creating a user group per application. 

- [ ] Write a method for creating a user group in LDAP.  This should be simple method in a proper module that can be used as API by all other modules to create user groups.
- [ ] Description of the group should be entered into LDAP.
- Assumption: framework for creating LDAP groups exist.
- Risk: (small) framework may not allow description in a straight forward way.

**Comment by harry-7** [comment]
I want to take this up. 

> Assumption: framework for creating LDAP groups exist.

Where can I find the code for this framework to create ldap that you mentioned

**Comment by JosephKiranBabu** [comment]
@harry-7 Some work was started on this here. See if you can continue from there.
https://github.com/bharatak/Plinth/commit/c7f70d3878e04533a2131a708e174ed711140df1#diff-09d5b0203b32f0ea389a741ab5fb55f1R128

**Comment by SunilMohanAdapa** [comment]
@harry-7, Also see the code in `users` modules and action scripts `ldap` and `users`.

**Comment by harry-7** [comment]
Looks like ldapscripts doesnt support taking an argument for description while creating a group. May be we can do it this way
1. We run the `ldapaddgroup` command to create the group.
2. Then we can use augeas to read the file and and set the description in the file.
 what say ?
@SunilMohanAdapa  @JosephKiranBabu

**Comment by JosephKiranBabu** [comment]
@harry-7 
We can achieve this using the two commands `ldapaddgroup` and `ldapmodifygroup`.
I tried this out on the command line. The modification process is as follows:

```
root@freedombox:~# ldapaddgroup somegroupname
Successfully added group somegroupname to LDAP

root@freedombox:~# ldapmodifygroup somegroupname
# About to modify the following entry :
dn: cn=somegroupname,ou=groups,dc=thisbox
objectClass: posixGroup
cn: somegroupname
gidNumber: 10001
description: Group account

# Enter your modifications here, end with CTRL-D.
dn: cn=somegroupname,ou=groups,dc=thisbox
replace: description
description: Some Group Account
Successfully modified group entry cn=somegroupname,ou=groups,dc=thisbox in LDAP
```

Replacing the default value of the description is done by writing these two lines and pressing Ctrl-D.
```
replace: description
description: Some Group Account
```

There are more examples in the man page of `ldapmodifygroup`.

**Comment by harry-7** [comment]
> dn: cn=somegroupname,ou=groups,dc=thisbox
replace: description
description: Some Group Account


@JosephKiranBabu  But how do we get those details inside our script?

**Comment by JosephKiranBabu** [comment]
Well, we have to either get creative with the command line and pipe it somehow, or use a library like python-ldap. Both require significant exploration. I can't give a direct answer unless I write that Python script myself.

**Comment by JosephKiranBabu** [comment]
@harry-7 We can do it using simple file redirection as follows.

```
root@freedombox:/vagrant# ldapmodifygroup somegroupname < configedit.txt 
```
where the file configedit.txt contains those two lines (replace and description).

The same thing can be done in a Python3 REPL as follows:

```
>>> from subprocess import run, PIPE
>>> p = run(['ldapmodifygroup', 'somegroupname'], stdout=PIPE, input=b"replace: description\ndescription: Some Other Group Account")
```

See this [stackoverflow answer](https://stackoverflow.com/a/165662) for explanation.
