### ISSUE TITLE
Framework: Separate out the short description and app name from the current full string 

### ISSUE THREAD

**Issue by Shilpa-Badekila** [freedombox/Plinth#929]
**Estimate** : 2 points
Separate out the short description and app name from the current full string

- [x] In the new card based user interface and for other purposes such as figuring out the name of the manual page, it is good to have the generic name such as 'Bittorrent Web Client' from the name of the application such as 'Transmission'. Separate out the two strings as short_description and name for each application.
- [x] For each application create two variables instead of one.
- [x] Update the menu code to compose the menu item name from the two variables.
- [x] Test for each application that menu entry is correct.

**Comment by harry-7** [comment]
Does every application has only one string?. I can see some applications having title (which contains the name) and description as seperate variables like [here](https://github.com/freedombox/Plinth/blob/master/plinth/modules/avahi/__init__.py) or am I missing something ?

**Comment by JosephKiranBabu** [comment]
Fixed in pull request #979
