### ISSUE TITLE
Framework: Have a framework for providing information about mobile and desktop clients

### ISSUE THREAD

**Issue by Shilpa-Badekila** [freedombox/Plinth#931]
**Estimate** : 3 points
Have a framework for providing information about mobile and desktop clients

- [x] Framework for providing information on application links for Web, F-Droid store, Google Play Store, iOS App Store.
- [x] Handle multiple mobile applications being available for each service.
- [x] Icons for each store.
- [x] Show buttons on each application for all the above. Buttons should link to market page.

**Comment by mray** [comment]
This sis somewhat connected to #832.

**Comment by JosephKiranBabu** [comment]
Fixed in #1014
