### ISSUE TITLE
Framework: Make Let's Encrypt an essential module

### ISSUE THREAD

**Issue by Shilpa-Badekila** [freedombox/Plinth#934]
**Estimate**: 1 point
Make Let's Encrypt an essential module

- [ ] Assumption: There is already a mechanism for making modules essential by setting a flag.
- [ ] Just set the essential flag on Let's Encrypt.

**Comment by JoKeyser** [comment]
Hi @Shilpa-Badekila , thanks for reporting. This issue has already been solved in PR #901, so I'm closing it.
