### ISSUE TITLE
Let's Encrypt: Automatically obtain certificates for new domains

### ISSUE THREAD

**Issue by Shilpa-Badekila** [freedombox/Plinth#935]
**Complexity**: 3 points
Let's Encrypt should automatically obtain certificates for new domains

- Assumption: Let's Encrypt can already obtain certificates.
- Assumption: When new domains are created, a new Django signal is sent to all listeners.
- [x] Make Let's Encrypt module listen for Django signal on new domain creation and trigger obtaining a new certificate.
- [x] Ignore the obtaining step if a certificate for that domain already exists.
- [x] Ignore domains for which Let's Encrypt certificates can't be obtained (such as .onion domains).

**Comment by jvalleroy** [comment]
Fixed in #988.
