### ISSUE TITLE
All applications: Provide mobile application and web page information

### ISSUE THREAD

**Issue by Shilpa-Badekila** [freedombox/Plinth#936]
**Complexity**: 3 points
For all applications, provide mobile application and web page information.

- Assumption: Framework for providing the information and showing the buttons already exists. See #931.
- [x] For each application, see what mobile, desktop and web application are available, evaluate them, and pick a recommendation (or multiple) for each platform.
- [x] For each of these applications provide information in Plinth using the framework mechanism.

**Comment by JosephKiranBabu** [comment]
Fixed in #1014
