### ISSUE TITLE
Syncthing: Restrict use of Syncthing administration to users in group Syncthing.

### ISSUE THREAD

**Issue by prachisr** [freedombox/Plinth#939]
**Complexity**: 2 points

Assumption: Framework for creating a user group for an application exists. #928 
- [x] Create a 'syncthing' group using the framework in #928.
- [x] Change access to Syncthing application such that administration is only possible for users belonging to the 'syncthing' group.
- [x] Test that this works with SSO.

**Comment by SunilMohanAdapa** [comment]
Minor update to description.

**Comment by SunilMohanAdapa** [comment]
This has been fixed in #1195 .
