### ISSUE TITLE
Travis: Build failure on a failing test

### ISSUE THREAD

**Issue by JosephKiranBabu** [freedombox/Plinth#941]
I am unable to reproduce this on a Debian box with Python 3.5.3-3

Is there a better way to create an empty Apache VirtualHost directive using augeas httpd lens instead of doing this?
`aug.set('$conf/VirtualHost', None)`

![screen shot 2017-08-02 at 12 30 57 pm](https://user-images.githubusercontent.com/4830191/28862277-197944aa-7782-11e7-87d3-855a049bd562.png)

**Comment by SunilMohanAdapa** [comment]
Closing since we have moved away from Travis.
