### ISSUE TITLE
minetest: Show domain information for users to connect to the game server

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#946]
Currently, the minetest page says that users can connect to the server on port 30000 but does not say exactly what are the values to be entered into the game client.  Users are being expected to understand additional information such as domain name.  Instead show full information about how to connect to the server.

- List all the domains and ports on which users can connect to the server. This information is available from names module. See example usages in the code.
- Application does not work on Tor hidden services and Pagekite domains so remove such domains.  This information is available as part of domain type provided by names module.
- Display this information on the application information page along with application's standard port (30000).
- Use the terminology and format that make it easy enter information about domain and port in a Minetest client. For example, if Minetest client says "Game Host/IP", use this as the header field when showing the above information.

This will be part of an effort make application simpler for client configuration.

**Comment by harry-7** [comment]
> List all the domains and ports on which users can connect to the server. This information is available from names module. See example usages in the code.

@SunilMohanAdapa I assume for all the domains the port is same the default port?
> Application does not work on Tor hidden services and Pagekite domains so remove such domains. This information is available as part of domain type provided by names module.

Only those two types right ?

**Comment by JosephKiranBabu** [comment]
Pull request #1162

**Comment by JoKeyser** [comment]
#1162 is closed, so closing here, too
