### ISSUE TITLE
tt-rss: Enable single sign on for tt-rss

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#954]
**Complexity**: 2 points

Currently, when a user is logged into Plinth, they are not automatically logged into tt-rss application.  When tt-rss application is opened, they are asked for another login.  Eliminate this extra login by using the new single sign on framework.

- Assumption: Single sign on framework is already available. See #859.
- This should use the same pubtkt framework as the rest of the Plinth.

**Comment by JosephKiranBabu** [comment]
@SunilMohanAdapa tt-rss already has auth-pubtkt based Single Sign On enabled. 
This issue can be closed.
