### ISSUE TITLE
tt-rss: Make Apache REMOTE_USER work for tt-rss

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#956]
**Complexity**: 2 points

Currently, each users has their own feeds.  The user logins in using simple Apache web authentication.  tt-rss maintains different accounts for each other.  Each user chooses their own feeds.  This task is to make sure this works after single sign on is enabled in #954.

- Each user must get their own feeds.
- Whichever user is logged in using single sign on, that user's feed must be available.
- This has to be done by sending REMOTE_USER header from Apache to the application and the application using that header for authorization.
- Assumption: single sign on is already enabled in #954.
- Assumption: If REMOTE_USER header is not possible, then close this task and create another for exploring alternatives.
- Note: Implementer needs to understand how Apache authentication works and how it sets REMOTE_USER header for applications to consume. They must also investigate into how tt-rss deals with REMOTE_USER header.

**Comment by JosephKiranBabu** [comment]
Tested that this is already working as expected. Apache is already sending the REMOTE_USER header and TT-RSS is using it to maintain different user accounts.
