### ISSUE TITLE
tt-rss: Enable API access for mobile application by default

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#957]
**Complexity**: 1 point

tt-rss has a mobile application.  This application works by connecting to tt-rss server using an API URL.  However, this only works when a user logs into the web interface and checks a checkbox in the settings to enable the mobile application.  This task is to enable the mobile application access by default.

- There is a setting in tt-rss to enable API access. This setting must be enabled by default during setup of tt-rss application.
- Assumption: It is possible to enable API access using a change in configuration. If it is not possible, close this issue and perhaps open another issue for alternatives.

**Comment by JosephKiranBabu** [comment]
#1060 is a duplicate of this and has already been closed. Hence, closing this.
