### ISSUE TITLE
matrixsynapse: Provide an option to turn on/off public registrations

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#968]
I think it is really problematic that **anybody** can create and use my matrix server by default. This invites all sorts of problems.
Matrix accounts should be tied to accounts on plinth just like the jabber server does.

**Comment by SunilMohanAdapa** [comment]
We should provide a feature to turn on and off public registrations.  The implementation is as follows:

**Complexity**: 2 points

* Create a new checkbox in matrix configuration page for enabling and disabling the registrations.
* Read the status of the `enable_registration` value from `/etc/matrix-synapse/homeserver.yaml` and reflect it on the checkbox.
* When the form is submitted, the value needs to be written back into configuration file.  Write code in form submission and `actions/matrixsynapse` to update the configuration file.  Configuration file must be edited using ruamel.yaml library.  See examples of how to do this in other applications.
* Make sure matrix synapse server is restarted after a change.

PS: users looking to disable registrations before this feature lands can do that by editing the configuration file `/etc/matrix-synapse/homeserver.yaml` manually.

**Comment by JosephKiranBabu** [comment]
This has already been done for Diaspora. We missed it for Matrix Synapse.

**Comment by mray** [comment]
Is there a **CLEAR** indication when registration is disabled?

Also, I think it would be great idea to link to a place that allows for account creation (presumably riot.im signup?)

**Comment by harry-7** [comment]
@mray  may be we can close this ? or is there anything left to be fixed here ?

**Comment by JosephKiranBabu** [comment]
@mray Riot will be shown in the list of clients for Matrix Synapse as part of #1014 
The option to disable registrations is a checkbox in the service page. Did you have a better representation in mind for showing that registration is disabled?

**Comment by mray** [comment]
*Thank you for taking care of this!*

@harry-7 A note could mention that this toggle needs to be used to turn registration on and **OFF** again, just in case there is none yet.

@JosephKiranBabu as long as there is any text that helps you understand the process of creating an account things are fine for now imho.

From a UX point of view there is still lots of room for improvement, but having the option with some text how to use it is fine.
