### ISSUE TITLE
matrixsynapse: Enable LDAP integration

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/Plinth#970]
**Currently**: 3 points

Currently, when Matrix Synapse application is enabled, it requires that separate user accounts are created for it using a client application.  There is a separate issue to deal with ability to enable/disable public registrations #968. If matrix is made to work with LDAP, then all existing users of FreedomBox can automatically login without creating and maintaining a separate account.

* Assumption: matrix-synapse-ldap3 package is available in Debian repository now making this possible.
* Add matrix-synapse-ldap3 to list of managed packages in the `matrixsynapse` module.
* During the setup of Matrix Synapse server, configure LDAP parameters.  See ejabberd on how this is typically done.
* Increment the version number of the module so that an upgrade is triggered and LDAP is configured for people upgrading from older versions of Plinth.
* Test that new accounts can be created from clients even when LDAP is enabled and that both accounts work.

**Comment by harry-7** [comment]
> Test that new accounts can be created from clients even when LDAP is enabled and that both accounts work.

@SunilMohanAdapa  is there any way to test these while using a vagrant box.?

**Comment by SunilMohanAdapa** [comment]
On Wednesday 11 October 2017 03:15 PM, Hemanth Kumar Veeranki wrote:
>     Test that new accounts can be created from clients even when LDAP is
>     enabled and that both accounts work.
> 
> @SunilMohanAdapa <https://github.com/sunilmohanadapa> is there any way
> to test these while using a vagrant box.?
> 

It is possible to use a Riot client (Web, Desktop or Mobile) when
running Matrix server on virtualbox developer instance.

1) Ensure that host machine port 4430 is mapped to 443 inside the
running VM.

# ss -nlpt | grep 4430

2) Run a Riot desktop client on host machine and provide localhost:4430
as matrix server address.

or

Join your mobile device into the same network as host machine and use
<host_ip_address>:4430 as matrix server address on Riot mobile app.
Ensure that firewall on host machine is not blocking the port 4430.

3) Register as usual.

-- 
Sunil

**Comment by harry-7** [comment]
@SunilMohanAdapa  may be we can close this now ?

**Comment by JosephKiranBabu** [comment]
@harry-7 Please add your "fixes" or "closes" into one of the commit messages. Then Github will automatically close the issue on merging a pull request. This should actually work even if you write it in a comment or a title in the pull request, but we're manually merging, so Github can only read the commit messages.

I'm closing this issue.
