### ISSUE TITLE
Help page inaccessible as logged-in, non-admin user

### ISSUE THREAD

**Issue by JoKeyser** [freedombox/Plinth#972]
In the current vagrant image and git master, I get a "403 Forbidden" error "You don't have permission to access /plinth/help/ on this server." if I try to access as non-admin user.
Also non-admin users should be able to see the help, if they're logged in.

**Comment by harry-7** [comment]
@JoKeyser  May be we can close this issue now?

**Comment by JoKeyser** [comment]
@harry-7 , sure, sorry I just forgot.
