### ISSUE TITLE
Dashboard system status and traffic

### ISSUE THREAD

**Issue by MargioS** [freedombox/Plinth#978]
Hi I'm new and I don't know how to suggest functionalities, so I write here.
I'm currently using freedombox also as a router, wouldn't be cool to add an option in plinth to see graphically the system usage and traffic like others routers?
I'm a graphic designer so i can help designing the graphic side of things

Hope to see some responses, keep going with the awesome work guys 👍

**Comment by JosephKiranBabu** [comment]
We have plans of integrating a tool called Cockpit into FreedomBox soon. You can see the screenshots of its Network dashboard here. 
https://github.com/cockpit-project/cockpit/wiki/Network

**Comment by JoKeyser** [comment]
@MargioS also thanks for the encouragement, and indeed, here's a good place to suggest things. I'm sure there's lots of other things to design, maybe @mray has an idea what's pressing right now, in case you want to help (which would be greatly appreciated!).

**Comment by JoKeyser** [comment]
Since Integration with CockPit is already tracked in issue #838, I'm closing this one here.
