### ISSUE TITLE
VLANs

### ISSUE THREAD

**Issue by MargioS** [freedombox/Plinth#984]
Hi guys, there are ways to set up VLANs and do stuff like inter-vlan routing and others advanced routing things?

Thanks and keep doing the great work ;)

**Comment by JoKeyser** [comment]
Hi @MargioS , I don't know the answer, and think your question is too general for an issue here to Plinth (which is just the FreedomBox user-interface).
You have a much higher chance of an answer from the wider community, if you post it to the mailinglist or the IRC channel, see https://wiki.debian.org/FreedomBox/Support

**Comment by MargioS** [comment]
@JoKeyser Ok thanks for the quick answer, I'll contact directly the team. 👍

**Comment by JoKeyser** [comment]
Okay great, so I'm closing this "duplicate", hope somebody will help you soon, good luck.
