### ISSUE TITLE
No "OUT OF DISK SPACE" warning

### ISSUE THREAD

**Issue by mray** [freedombox/Plinth#985]
I recently had to witness my FreedomBox first degrading in performance and then crashing several services for no apparent reason. It should be our duty to protect users from having to find out that disk space is a problem.

1. We may set a certain space limit that already triggers a mild warning during the installation process that the current partition is too small

2. We need to detect *in time* when more space is needed and inform the user about the problem, aswell as giving easy to perform steps to solve the problem. (uninstall programs, sudo apt-get clean, grow partition, ...)

**Comment by JoKeyser** [comment]
I agree that this is necessary. Should be part of the upcoming notification system (see #867). Until then, just a banner shown anywhere would do the trick?
I propose there should be 2 stages, a mild and a critical warning, depending on the available space on the /root partition.
The cutoff values to trigger them could be <20% of disk or <2 GiB free space, and the critical at <10% or < 1 GiB.
The warning should state 1) Why it was triggered (including cutoff value that was reached), and 2) where to fix it, with a link to the disks module, which will offer at least one button for relief (e.g. #973 ).

**Comment by mray** [comment]
> Until then, just a banner shown everywhere would do the trick?

Anything will do until we have a proper way.

> Maybe also install-buttons could be disabled if the warning is critical?

I don't think so. There may be small applications that won't create issues. The cause of the warning needs to be addressed, or ignored by the user.

**Comment by JoKeyser** [comment]
Okay great, I agree that disabling buttons would be too much. So I think it's ready for implementation!
