### ISSUE TITLE
[872541] plinth: Sort generated depends list

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#991]

**Comment by jvalleroy** [comment]
BTS_msg_id: <150304909696.13259.9188078248828400376.reportbug@xps>
BTS author: James Valleroy <jvalleroy@mailbox.org>

This is a multi-part MIME message sent by reportbug.


--===============0223892513802539696==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

Package: plinth
Severity: normal
Tags: patch

plinth's control has depends listed in random order, that changes with every build:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/plinth.html

To avoid this, sort the list printed by --list-dependencies.

--===============0223892513802539696==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="0001-Sort-dependency-list-for-essential-modules.patch"

From b4cc9d3fc9e1f74b6d1561d3d0f2266869bfe92c Mon Sep 17 00:00:00 2001
From: James Valleroy <jvalleroy@mailbox.org>
Date: Thu, 17 Aug 2017 22:12:54 -0400
Subject: [PATCH] Sort dependency list for essential modules

---
 debian/rules | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/debian/rules b/debian/rules
index a54942d6..496d0c31 100755
--- a/debian/rules
+++ b/debian/rules
@@ -8,7 +8,7 @@ export PYBUILD_NAME=plinth
 
 override_dh_auto_install-indep:
 	dh_auto_install
-	./run --list-dependencies 2> /dev/null | tr '\n' ', ' | \
+	./run --list-dependencies 2> /dev/null | sort | tr '\n' ', ' | \
 		sed -e 's/^/plinth:Depends=/' >> debian/plinth.substvars
 
 new-upstream:
-- 
2.11.0


--===============0223892513802539696==--

**Comment by jvalleroy** [comment]
BTS_msg_id: <150304909696.13259.9188078248828400376.reportbug@xps>
BTS author: James Valleroy <jvalleroy@mailbox.org>

This is a multi-part MIME message sent by reportbug.


--===============0223892513802539696==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

Package: plinth
Severity: normal
Tags: patch

plinth's control has depends listed in random order, that changes with every build:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/plinth.html

To avoid this, sort the list printed by --list-dependencies.

--===============0223892513802539696==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="0001-Sort-dependency-list-for-essential-modules.patch"

From b4cc9d3fc9e1f74b6d1561d3d0f2266869bfe92c Mon Sep 17 00:00:00 2001
From: James Valleroy <jvalleroy@mailbox.org>
Date: Thu, 17 Aug 2017 22:12:54 -0400
Subject: [PATCH] Sort dependency list for essential modules

---
 debian/rules | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/debian/rules b/debian/rules
index a54942d6..496d0c31 100755
--- a/debian/rules
+++ b/debian/rules
@@ -8,7 +8,7 @@ export PYBUILD_NAME=plinth
 
 override_dh_auto_install-indep:
 	dh_auto_install
-	./run --list-dependencies 2> /dev/null | tr '\n' ', ' | \
+	./run --list-dependencies 2> /dev/null | sort | tr '\n' ', ' | \
 		sed -e 's/^/plinth:Depends=/' >> debian/plinth.substvars
 
 new-upstream:
-- 
2.11.0


--===============0223892513802539696==--

**Comment by jvalleroy** [comment]
BTS_msg_id: <2b416d81-efc0-1df2-2924-5734f6834135@medhas.org>
BTS author: Sunil Mohan Adapa <sunil@medhas.org>

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--xciEP9FgQwFXmxwhu92okr3QdFKvdMwTp
Content-Type: multipart/mixed; boundary="bpvLoo8StpoD6C0L4KpO65stCV4DNtlj7";
 protected-headers="v1"
From: Sunil Mohan Adapa <sunil@medhas.org>
To: James Valleroy <jvalleroy@mailbox.org>, 872541@bugs.debian.org,
 Debian Bug Tracking System <submit@bugs.debian.org>
Message-ID: <2b416d81-efc0-1df2-2924-5734f6834135@medhas.org>
Subject: Re: Bug#872541: plinth: Sort generated depends list
References: <150304909696.13259.9188078248828400376.reportbug@xps>
In-Reply-To: <150304909696.13259.9188078248828400376.reportbug@xps>

--bpvLoo8StpoD6C0L4KpO65stCV4DNtlj7
Content-Type: text/plain; charset=windows-1252
Content-Language: en-US
Content-Transfer-Encoding: quoted-printable

On Friday 18 August 2017 03:08 PM, James Valleroy wrote:
> Package: plinth
> Severity: normal
> Tags: patch
>=20
> plinth's control has depends listed in random order, that changes with =
every build:
> https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diff=
oscope-results/plinth.html
>=20
> To avoid this, sort the list printed by --list-dependencies.
>=20

Looks good, please apply the patch.

--=20
Sunil


--bpvLoo8StpoD6C0L4KpO65stCV4DNtlj7--

--xciEP9FgQwFXmxwhu92okr3QdFKvdMwTp
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----

iQJFBAEBCgAvFiEE5xPDY9ZyWnWupXSBQ+oc/wqnxfIFAlmWwtcRHHN1bmlsQG1l
ZGhhcy5vcmcACgkQQ+oc/wqnxfKFjQ//fT7GxlDw0tPjMVT8TdvNBrjX1O5IPa6K
r1/tuRGnR9vcQ5Y4E0Xs4YdUkQO6M8U2qIbQUfORIGMYkgzgfFmUPNFvm8bnYxOE
uCihurl7wQDn05vlTrHClbRbypJtKRQJGTcuLKdYa09ZaBQlvf8xqEpFzuNwinQz
teARZEmihPnaz8+w+44e8qyX26HFFKmY6iWryBFVeKwhND2okXmnnV1zKl3MdgUt
4hugKOLk7+aPotsitlPzZCsUOPW0MwlHTTpHB84cWE2lp44gpIxOKFgqUTPegmGc
VL1+s+thatchzOSVskIO7+fh4EgIWxc8t9NyiEEVyqzLjUQeGc6lKUuCCCH3dW1m
GN2ePK3Q5Nn5AvAznSgIdLC7YFKhFCMA+kslB43aMddB+UqfxcxKXpcXaXwzv8fb
sNGHa1qBBquSC3cJZVG9UAGKv/hp4SelDTSPQ4ZOS/3TYTomOxwYtbG7jhmyARlS
orrnEaI69NSdnF+9SBqZjavaKt0nJ7yBp9Uw7Yu/M7AnOPM6xr/Flh0WRHUCmxH1
0V9JqxU6Ax9p8Ammz21QYmaUM71W2ZAjePz3xHyHDMhC/GgraqCcz/jiQ5GEzjfw
eel6wJWZ+qaO4MB7YcZrDIh9fvCdx7Hg/MIqG5d8kEv9yovDroT3YidBv1iczX2p
A7Mf2ICRTp4=
=w9X0
-----END PGP SIGNATURE-----

--xciEP9FgQwFXmxwhu92okr3QdFKvdMwTp--

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <150304909696.13259.9188078248828400376.reportbug@xps>
BTS author: James Valleroy <jvalleroy@mailbox.org>

This is a multi-part MIME message sent by reportbug.


--===============0223892513802539696==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

Package: plinth
Severity: normal
Tags: patch

plinth's control has depends listed in random order, that changes with every build:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/plinth.html

To avoid this, sort the list printed by --list-dependencies.

--===============0223892513802539696==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="0001-Sort-dependency-list-for-essential-modules.patch"

From b4cc9d3fc9e1f74b6d1561d3d0f2266869bfe92c Mon Sep 17 00:00:00 2001
From: James Valleroy <jvalleroy@mailbox.org>
Date: Thu, 17 Aug 2017 22:12:54 -0400
Subject: [PATCH] Sort dependency list for essential modules

---
 debian/rules | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/debian/rules b/debian/rules
index a54942d6..496d0c31 100755
--- a/debian/rules
+++ b/debian/rules
@@ -8,7 +8,7 @@ export PYBUILD_NAME=plinth
 
 override_dh_auto_install-indep:
 	dh_auto_install
-	./run --list-dependencies 2> /dev/null | tr '\n' ', ' | \
+	./run --list-dependencies 2> /dev/null | sort | tr '\n' ', ' | \
 		sed -e 's/^/plinth:Depends=/' >> debian/plinth.substvars
 
 new-upstream:
-- 
2.11.0


--===============0223892513802539696==--
